/*
Monte Carlo AI API

Programmatic access to the Monte Carlo AI platform.  Every response with a status of 400 or higher is `application/problem+json`, and carries a `code` naming the failure. That includes failures no single operation declares, such as calling a path with a method it does not support, which returns 405.  Every response carries an `X-Request-Id` header, and an error body repeats it as `request_id`. Quote it when reporting a problem. To choose the value yourself, send an `x-correlation-id` header; a value we cannot accept is replaced by a generated one.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package montecarlo

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the CurrentUserOut type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CurrentUserOut{}

// CurrentUserOut The identity the request was authenticated as, and the account it resolved to.
type CurrentUserOut struct {
	// Whether the account is paused. While it is, this endpoint still answers but every other one returns 403 with the code `account_frozen`.
	AccountFrozen bool `json:"account_frozen"`
	// Unique identifier of the caller's account.
	AccountId string `json:"account_id"`
	// Display name of the account. Null when the account has no name.
	AccountName NullableString `json:"account_name,omitempty"`
	// Names of the authorization groups this user belongs to. They determine what the user is permitted to do.
	AuthGroups []string `json:"auth_groups,omitempty"`
	// Email address of the user. An identity with no mailbox of its own, such as an AI agent, carries a display label here instead.
	Email string `json:"email"`
	// Given name of the user. Null when it is not set.
	FirstName NullableString `json:"first_name,omitempty"`
	// What kind of identity this is. It does not decide what the identity may do — that comes from the authorization groups it belongs to.
	IdentityType IdentityType `json:"identity_type"`
	// Family name of the user. Null when it is not set.
	LastName NullableString `json:"last_name,omitempty"`
	// Unique identifier of the user.
	UserId string `json:"user_id"`
}

type _CurrentUserOut CurrentUserOut

// NewCurrentUserOut instantiates a new CurrentUserOut object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCurrentUserOut(accountFrozen bool, accountId string, email string, identityType IdentityType, userId string) *CurrentUserOut {
	this := CurrentUserOut{}
	this.AccountFrozen = accountFrozen
	this.AccountId = accountId
	this.Email = email
	this.IdentityType = identityType
	this.UserId = userId
	return &this
}

// NewCurrentUserOutWithDefaults instantiates a new CurrentUserOut object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCurrentUserOutWithDefaults() *CurrentUserOut {
	this := CurrentUserOut{}
	return &this
}

// GetAccountFrozen returns the AccountFrozen field value
func (o *CurrentUserOut) GetAccountFrozen() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.AccountFrozen
}

// GetAccountFrozenOk returns a tuple with the AccountFrozen field value
// and a boolean to check if the value has been set.
func (o *CurrentUserOut) GetAccountFrozenOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccountFrozen, true
}

// SetAccountFrozen sets field value
func (o *CurrentUserOut) SetAccountFrozen(v bool) {
	o.AccountFrozen = v
}

// GetAccountId returns the AccountId field value
func (o *CurrentUserOut) GetAccountId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AccountId
}

// GetAccountIdOk returns a tuple with the AccountId field value
// and a boolean to check if the value has been set.
func (o *CurrentUserOut) GetAccountIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccountId, true
}

// SetAccountId sets field value
func (o *CurrentUserOut) SetAccountId(v string) {
	o.AccountId = v
}

// GetAccountName returns the AccountName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CurrentUserOut) GetAccountName() string {
	if o == nil || IsNil(o.AccountName.Get()) {
		var ret string
		return ret
	}
	return *o.AccountName.Get()
}

// GetAccountNameOk returns a tuple with the AccountName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CurrentUserOut) GetAccountNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.AccountName.Get(), o.AccountName.IsSet()
}

// HasAccountName returns a boolean if a field has been set.
func (o *CurrentUserOut) HasAccountName() bool {
	if o != nil && o.AccountName.IsSet() {
		return true
	}

	return false
}

// SetAccountName gets a reference to the given NullableString and assigns it to the AccountName field.
func (o *CurrentUserOut) SetAccountName(v string) {
	o.AccountName.Set(&v)
}

// SetAccountNameNil sets the value for AccountName to be an explicit nil
func (o *CurrentUserOut) SetAccountNameNil() {
	o.AccountName.Set(nil)
}

// UnsetAccountName ensures that no value is present for AccountName, not even an explicit nil
func (o *CurrentUserOut) UnsetAccountName() {
	o.AccountName.Unset()
}

// GetAuthGroups returns the AuthGroups field value if set, zero value otherwise.
func (o *CurrentUserOut) GetAuthGroups() []string {
	if o == nil || IsNil(o.AuthGroups) {
		var ret []string
		return ret
	}
	return o.AuthGroups
}

// GetAuthGroupsOk returns a tuple with the AuthGroups field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CurrentUserOut) GetAuthGroupsOk() ([]string, bool) {
	if o == nil || IsNil(o.AuthGroups) {
		return nil, false
	}
	return o.AuthGroups, true
}

// HasAuthGroups returns a boolean if a field has been set.
func (o *CurrentUserOut) HasAuthGroups() bool {
	if o != nil && !IsNil(o.AuthGroups) {
		return true
	}

	return false
}

// SetAuthGroups gets a reference to the given []string and assigns it to the AuthGroups field.
func (o *CurrentUserOut) SetAuthGroups(v []string) {
	o.AuthGroups = v
}

// GetEmail returns the Email field value
func (o *CurrentUserOut) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *CurrentUserOut) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *CurrentUserOut) SetEmail(v string) {
	o.Email = v
}

// GetFirstName returns the FirstName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CurrentUserOut) GetFirstName() string {
	if o == nil || IsNil(o.FirstName.Get()) {
		var ret string
		return ret
	}
	return *o.FirstName.Get()
}

// GetFirstNameOk returns a tuple with the FirstName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CurrentUserOut) GetFirstNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.FirstName.Get(), o.FirstName.IsSet()
}

// HasFirstName returns a boolean if a field has been set.
func (o *CurrentUserOut) HasFirstName() bool {
	if o != nil && o.FirstName.IsSet() {
		return true
	}

	return false
}

// SetFirstName gets a reference to the given NullableString and assigns it to the FirstName field.
func (o *CurrentUserOut) SetFirstName(v string) {
	o.FirstName.Set(&v)
}

// SetFirstNameNil sets the value for FirstName to be an explicit nil
func (o *CurrentUserOut) SetFirstNameNil() {
	o.FirstName.Set(nil)
}

// UnsetFirstName ensures that no value is present for FirstName, not even an explicit nil
func (o *CurrentUserOut) UnsetFirstName() {
	o.FirstName.Unset()
}

// GetIdentityType returns the IdentityType field value
func (o *CurrentUserOut) GetIdentityType() IdentityType {
	if o == nil {
		var ret IdentityType
		return ret
	}

	return o.IdentityType
}

// GetIdentityTypeOk returns a tuple with the IdentityType field value
// and a boolean to check if the value has been set.
func (o *CurrentUserOut) GetIdentityTypeOk() (*IdentityType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IdentityType, true
}

// SetIdentityType sets field value
func (o *CurrentUserOut) SetIdentityType(v IdentityType) {
	o.IdentityType = v
}

// GetLastName returns the LastName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CurrentUserOut) GetLastName() string {
	if o == nil || IsNil(o.LastName.Get()) {
		var ret string
		return ret
	}
	return *o.LastName.Get()
}

// GetLastNameOk returns a tuple with the LastName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CurrentUserOut) GetLastNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.LastName.Get(), o.LastName.IsSet()
}

// HasLastName returns a boolean if a field has been set.
func (o *CurrentUserOut) HasLastName() bool {
	if o != nil && o.LastName.IsSet() {
		return true
	}

	return false
}

// SetLastName gets a reference to the given NullableString and assigns it to the LastName field.
func (o *CurrentUserOut) SetLastName(v string) {
	o.LastName.Set(&v)
}

// SetLastNameNil sets the value for LastName to be an explicit nil
func (o *CurrentUserOut) SetLastNameNil() {
	o.LastName.Set(nil)
}

// UnsetLastName ensures that no value is present for LastName, not even an explicit nil
func (o *CurrentUserOut) UnsetLastName() {
	o.LastName.Unset()
}

// GetUserId returns the UserId field value
func (o *CurrentUserOut) GetUserId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value
// and a boolean to check if the value has been set.
func (o *CurrentUserOut) GetUserIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UserId, true
}

// SetUserId sets field value
func (o *CurrentUserOut) SetUserId(v string) {
	o.UserId = v
}

func (o CurrentUserOut) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CurrentUserOut) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["account_frozen"] = o.AccountFrozen
	toSerialize["account_id"] = o.AccountId
	if o.AccountName.IsSet() {
		toSerialize["account_name"] = o.AccountName.Get()
	}
	if !IsNil(o.AuthGroups) {
		toSerialize["auth_groups"] = o.AuthGroups
	}
	toSerialize["email"] = o.Email
	if o.FirstName.IsSet() {
		toSerialize["first_name"] = o.FirstName.Get()
	}
	toSerialize["identity_type"] = o.IdentityType
	if o.LastName.IsSet() {
		toSerialize["last_name"] = o.LastName.Get()
	}
	toSerialize["user_id"] = o.UserId
	return toSerialize, nil
}

func (o *CurrentUserOut) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"account_frozen",
		"account_id",
		"email",
		"identity_type",
		"user_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCurrentUserOut := _CurrentUserOut{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCurrentUserOut)

	if err != nil {
		return err
	}

	*o = CurrentUserOut(varCurrentUserOut)

	return err
}

type NullableCurrentUserOut struct {
	value *CurrentUserOut
	isSet bool
}

func (v NullableCurrentUserOut) Get() *CurrentUserOut {
	return v.value
}

func (v *NullableCurrentUserOut) Set(val *CurrentUserOut) {
	v.value = val
	v.isSet = true
}

func (v NullableCurrentUserOut) IsSet() bool {
	return v.isSet
}

func (v *NullableCurrentUserOut) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCurrentUserOut(val *CurrentUserOut) *NullableCurrentUserOut {
	return &NullableCurrentUserOut{value: val, isSet: true}
}

func (v NullableCurrentUserOut) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCurrentUserOut) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
