/*
Monte Carlo AI API

Programmatic access to the Monte Carlo AI platform.  Every response with a status of 400 or higher is `application/problem+json`, and carries a `code` naming the failure. That includes failures no single operation declares, such as calling a path with a method it does not support, which returns 405.  Every response carries an `X-Request-Id` header, and an error body repeats it as `request_id`. Quote it when reporting a problem. To choose the value yourself, send an `x-correlation-id` header; a value we cannot accept is replaced by a generated one.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package montecarlo

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"
)

// checks if the AwsCollectionDataStoreOut type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AwsCollectionDataStoreOut{}

// AwsCollectionDataStoreOut A data store held in an S3 bucket.
type AwsCollectionDataStoreOut struct {
	// How Monte Carlo authenticates when it reaches the data store.
	AuthenticationType AuthenticationType `json:"authentication_type"`
	// Name of the S3 bucket Monte Carlo uses. Empty until it has been registered.
	BucketName string `json:"bucket_name"`
	// When the data store was created, which is when its deployment was provisioned.
	CreatedTime NullableTime `json:"created_time,omitempty"`
	// Identifier of the deployment this data store belongs to.
	DeploymentId string `json:"deployment_id"`
	// Whether Monte Carlo is using this data store. One that is unregistered, or whose validation failed, is not enabled.
	Enabled bool `json:"enabled"`
	// Value to put in the trust policy of the role Monte Carlo assumes to access the bucket. Null before Monte Carlo has generated one, and for a caller who cannot register a data store. Also null if the value could not be read just now, so retry once before treating it as absent.
	ExternalId NullableString `json:"external_id,omitempty"`
	// Unique identifier of the data store.
	Id string `json:"id"`
	// When the data store was last registered, renamed, or given a different bucket or role. Null until one of those has happened.
	LastUpdatedTime NullableTime `json:"last_updated_time,omitempty"`
	// Display name of the data store. Null when it has no name.
	Name NullableString `json:"name,omitempty"`
	// Which kind of storage the data store keeps its data in.
	StorageType StorageType `json:"storage_type"`
}

type _AwsCollectionDataStoreOut AwsCollectionDataStoreOut

// NewAwsCollectionDataStoreOut instantiates a new AwsCollectionDataStoreOut object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAwsCollectionDataStoreOut(authenticationType AuthenticationType, bucketName string, deploymentId string, enabled bool, id string, storageType StorageType) *AwsCollectionDataStoreOut {
	this := AwsCollectionDataStoreOut{}
	this.AuthenticationType = authenticationType
	this.BucketName = bucketName
	this.DeploymentId = deploymentId
	this.Enabled = enabled
	this.Id = id
	this.StorageType = storageType
	return &this
}

// NewAwsCollectionDataStoreOutWithDefaults instantiates a new AwsCollectionDataStoreOut object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAwsCollectionDataStoreOutWithDefaults() *AwsCollectionDataStoreOut {
	this := AwsCollectionDataStoreOut{}
	return &this
}

// GetAuthenticationType returns the AuthenticationType field value
func (o *AwsCollectionDataStoreOut) GetAuthenticationType() AuthenticationType {
	if o == nil {
		var ret AuthenticationType
		return ret
	}

	return o.AuthenticationType
}

// GetAuthenticationTypeOk returns a tuple with the AuthenticationType field value
// and a boolean to check if the value has been set.
func (o *AwsCollectionDataStoreOut) GetAuthenticationTypeOk() (*AuthenticationType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AuthenticationType, true
}

// SetAuthenticationType sets field value
func (o *AwsCollectionDataStoreOut) SetAuthenticationType(v AuthenticationType) {
	o.AuthenticationType = v
}

// GetBucketName returns the BucketName field value
func (o *AwsCollectionDataStoreOut) GetBucketName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BucketName
}

// GetBucketNameOk returns a tuple with the BucketName field value
// and a boolean to check if the value has been set.
func (o *AwsCollectionDataStoreOut) GetBucketNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BucketName, true
}

// SetBucketName sets field value
func (o *AwsCollectionDataStoreOut) SetBucketName(v string) {
	o.BucketName = v
}

// GetCreatedTime returns the CreatedTime field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AwsCollectionDataStoreOut) GetCreatedTime() time.Time {
	if o == nil || IsNil(o.CreatedTime.Get()) {
		var ret time.Time
		return ret
	}
	return *o.CreatedTime.Get()
}

// GetCreatedTimeOk returns a tuple with the CreatedTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AwsCollectionDataStoreOut) GetCreatedTimeOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.CreatedTime.Get(), o.CreatedTime.IsSet()
}

// HasCreatedTime returns a boolean if a field has been set.
func (o *AwsCollectionDataStoreOut) HasCreatedTime() bool {
	if o != nil && o.CreatedTime.IsSet() {
		return true
	}

	return false
}

// SetCreatedTime gets a reference to the given NullableTime and assigns it to the CreatedTime field.
func (o *AwsCollectionDataStoreOut) SetCreatedTime(v time.Time) {
	o.CreatedTime.Set(&v)
}

// SetCreatedTimeNil sets the value for CreatedTime to be an explicit nil
func (o *AwsCollectionDataStoreOut) SetCreatedTimeNil() {
	o.CreatedTime.Set(nil)
}

// UnsetCreatedTime ensures that no value is present for CreatedTime, not even an explicit nil
func (o *AwsCollectionDataStoreOut) UnsetCreatedTime() {
	o.CreatedTime.Unset()
}

// GetDeploymentId returns the DeploymentId field value
func (o *AwsCollectionDataStoreOut) GetDeploymentId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DeploymentId
}

// GetDeploymentIdOk returns a tuple with the DeploymentId field value
// and a boolean to check if the value has been set.
func (o *AwsCollectionDataStoreOut) GetDeploymentIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DeploymentId, true
}

// SetDeploymentId sets field value
func (o *AwsCollectionDataStoreOut) SetDeploymentId(v string) {
	o.DeploymentId = v
}

// GetEnabled returns the Enabled field value
func (o *AwsCollectionDataStoreOut) GetEnabled() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value
// and a boolean to check if the value has been set.
func (o *AwsCollectionDataStoreOut) GetEnabledOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Enabled, true
}

// SetEnabled sets field value
func (o *AwsCollectionDataStoreOut) SetEnabled(v bool) {
	o.Enabled = v
}

// GetExternalId returns the ExternalId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AwsCollectionDataStoreOut) GetExternalId() string {
	if o == nil || IsNil(o.ExternalId.Get()) {
		var ret string
		return ret
	}
	return *o.ExternalId.Get()
}

// GetExternalIdOk returns a tuple with the ExternalId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AwsCollectionDataStoreOut) GetExternalIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ExternalId.Get(), o.ExternalId.IsSet()
}

// HasExternalId returns a boolean if a field has been set.
func (o *AwsCollectionDataStoreOut) HasExternalId() bool {
	if o != nil && o.ExternalId.IsSet() {
		return true
	}

	return false
}

// SetExternalId gets a reference to the given NullableString and assigns it to the ExternalId field.
func (o *AwsCollectionDataStoreOut) SetExternalId(v string) {
	o.ExternalId.Set(&v)
}

// SetExternalIdNil sets the value for ExternalId to be an explicit nil
func (o *AwsCollectionDataStoreOut) SetExternalIdNil() {
	o.ExternalId.Set(nil)
}

// UnsetExternalId ensures that no value is present for ExternalId, not even an explicit nil
func (o *AwsCollectionDataStoreOut) UnsetExternalId() {
	o.ExternalId.Unset()
}

// GetId returns the Id field value
func (o *AwsCollectionDataStoreOut) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *AwsCollectionDataStoreOut) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *AwsCollectionDataStoreOut) SetId(v string) {
	o.Id = v
}

// GetLastUpdatedTime returns the LastUpdatedTime field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AwsCollectionDataStoreOut) GetLastUpdatedTime() time.Time {
	if o == nil || IsNil(o.LastUpdatedTime.Get()) {
		var ret time.Time
		return ret
	}
	return *o.LastUpdatedTime.Get()
}

// GetLastUpdatedTimeOk returns a tuple with the LastUpdatedTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AwsCollectionDataStoreOut) GetLastUpdatedTimeOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.LastUpdatedTime.Get(), o.LastUpdatedTime.IsSet()
}

// HasLastUpdatedTime returns a boolean if a field has been set.
func (o *AwsCollectionDataStoreOut) HasLastUpdatedTime() bool {
	if o != nil && o.LastUpdatedTime.IsSet() {
		return true
	}

	return false
}

// SetLastUpdatedTime gets a reference to the given NullableTime and assigns it to the LastUpdatedTime field.
func (o *AwsCollectionDataStoreOut) SetLastUpdatedTime(v time.Time) {
	o.LastUpdatedTime.Set(&v)
}

// SetLastUpdatedTimeNil sets the value for LastUpdatedTime to be an explicit nil
func (o *AwsCollectionDataStoreOut) SetLastUpdatedTimeNil() {
	o.LastUpdatedTime.Set(nil)
}

// UnsetLastUpdatedTime ensures that no value is present for LastUpdatedTime, not even an explicit nil
func (o *AwsCollectionDataStoreOut) UnsetLastUpdatedTime() {
	o.LastUpdatedTime.Unset()
}

// GetName returns the Name field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AwsCollectionDataStoreOut) GetName() string {
	if o == nil || IsNil(o.Name.Get()) {
		var ret string
		return ret
	}
	return *o.Name.Get()
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AwsCollectionDataStoreOut) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Name.Get(), o.Name.IsSet()
}

// HasName returns a boolean if a field has been set.
func (o *AwsCollectionDataStoreOut) HasName() bool {
	if o != nil && o.Name.IsSet() {
		return true
	}

	return false
}

// SetName gets a reference to the given NullableString and assigns it to the Name field.
func (o *AwsCollectionDataStoreOut) SetName(v string) {
	o.Name.Set(&v)
}

// SetNameNil sets the value for Name to be an explicit nil
func (o *AwsCollectionDataStoreOut) SetNameNil() {
	o.Name.Set(nil)
}

// UnsetName ensures that no value is present for Name, not even an explicit nil
func (o *AwsCollectionDataStoreOut) UnsetName() {
	o.Name.Unset()
}

// GetStorageType returns the StorageType field value
func (o *AwsCollectionDataStoreOut) GetStorageType() StorageType {
	if o == nil {
		var ret StorageType
		return ret
	}

	return o.StorageType
}

// GetStorageTypeOk returns a tuple with the StorageType field value
// and a boolean to check if the value has been set.
func (o *AwsCollectionDataStoreOut) GetStorageTypeOk() (*StorageType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StorageType, true
}

// SetStorageType sets field value
func (o *AwsCollectionDataStoreOut) SetStorageType(v StorageType) {
	o.StorageType = v
}

func (o AwsCollectionDataStoreOut) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AwsCollectionDataStoreOut) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["authentication_type"] = o.AuthenticationType
	toSerialize["bucket_name"] = o.BucketName
	if o.CreatedTime.IsSet() {
		toSerialize["created_time"] = o.CreatedTime.Get()
	}
	toSerialize["deployment_id"] = o.DeploymentId
	toSerialize["enabled"] = o.Enabled
	if o.ExternalId.IsSet() {
		toSerialize["external_id"] = o.ExternalId.Get()
	}
	toSerialize["id"] = o.Id
	if o.LastUpdatedTime.IsSet() {
		toSerialize["last_updated_time"] = o.LastUpdatedTime.Get()
	}
	if o.Name.IsSet() {
		toSerialize["name"] = o.Name.Get()
	}
	toSerialize["storage_type"] = o.StorageType
	return toSerialize, nil
}

func (o *AwsCollectionDataStoreOut) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"authentication_type",
		"bucket_name",
		"deployment_id",
		"enabled",
		"id",
		"storage_type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAwsCollectionDataStoreOut := _AwsCollectionDataStoreOut{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAwsCollectionDataStoreOut)

	if err != nil {
		return err
	}

	*o = AwsCollectionDataStoreOut(varAwsCollectionDataStoreOut)

	return err
}

type NullableAwsCollectionDataStoreOut struct {
	value *AwsCollectionDataStoreOut
	isSet bool
}

func (v NullableAwsCollectionDataStoreOut) Get() *AwsCollectionDataStoreOut {
	return v.value
}

func (v *NullableAwsCollectionDataStoreOut) Set(val *AwsCollectionDataStoreOut) {
	v.value = val
	v.isSet = true
}

func (v NullableAwsCollectionDataStoreOut) IsSet() bool {
	return v.isSet
}

func (v *NullableAwsCollectionDataStoreOut) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAwsCollectionDataStoreOut(val *AwsCollectionDataStoreOut) *NullableAwsCollectionDataStoreOut {
	return &NullableAwsCollectionDataStoreOut{value: val, isSet: true}
}

func (v NullableAwsCollectionDataStoreOut) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAwsCollectionDataStoreOut) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
