/*
Monte Carlo AI API

Programmatic access to the Monte Carlo AI platform.  Every response with a status of 400 or higher is `application/problem+json`, and carries a `code` naming the failure. That includes failures no single operation declares, such as calling a path with a method it does not support, which returns 405.  Every response carries an `X-Request-Id` header, and an error body repeats it as `request_id`. Quote it when reporting a problem. To choose the value yourself, send an `x-correlation-id` header; a value we cannot accept is replaced by a generated one.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package montecarlo

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the AwsCollectionAgentIn type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AwsCollectionAgentIn{}

// AwsCollectionAgentIn Details Monte Carlo needs to reach a collection agent you have deployed on AWS.
type AwsCollectionAgentIn struct {
	// Deployment to register the collection agent on. It must already hold an unregistered AWS collection agent.
	DeploymentId string `json:"deployment_id"`
	// ARN of the Lambda function Monte Carlo should invoke.
	LambdaFunctionArn string `json:"lambda_function_arn"`
	// ARN of the role Monte Carlo assumes to invoke the function. Its trust policy must already carry the deployment's external id.
	RoleArn string `json:"role_arn" validate:"regexp=^arn:(aws[a-zA-Z-]*)?:iam::\\\\d{12}:role\\/.+$"`
}

type _AwsCollectionAgentIn AwsCollectionAgentIn

// NewAwsCollectionAgentIn instantiates a new AwsCollectionAgentIn object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAwsCollectionAgentIn(deploymentId string, lambdaFunctionArn string, roleArn string) *AwsCollectionAgentIn {
	this := AwsCollectionAgentIn{}
	this.DeploymentId = deploymentId
	this.LambdaFunctionArn = lambdaFunctionArn
	this.RoleArn = roleArn
	return &this
}

// NewAwsCollectionAgentInWithDefaults instantiates a new AwsCollectionAgentIn object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAwsCollectionAgentInWithDefaults() *AwsCollectionAgentIn {
	this := AwsCollectionAgentIn{}
	return &this
}

// GetDeploymentId returns the DeploymentId field value
func (o *AwsCollectionAgentIn) GetDeploymentId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DeploymentId
}

// GetDeploymentIdOk returns a tuple with the DeploymentId field value
// and a boolean to check if the value has been set.
func (o *AwsCollectionAgentIn) GetDeploymentIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DeploymentId, true
}

// SetDeploymentId sets field value
func (o *AwsCollectionAgentIn) SetDeploymentId(v string) {
	o.DeploymentId = v
}

// GetLambdaFunctionArn returns the LambdaFunctionArn field value
func (o *AwsCollectionAgentIn) GetLambdaFunctionArn() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.LambdaFunctionArn
}

// GetLambdaFunctionArnOk returns a tuple with the LambdaFunctionArn field value
// and a boolean to check if the value has been set.
func (o *AwsCollectionAgentIn) GetLambdaFunctionArnOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LambdaFunctionArn, true
}

// SetLambdaFunctionArn sets field value
func (o *AwsCollectionAgentIn) SetLambdaFunctionArn(v string) {
	o.LambdaFunctionArn = v
}

// GetRoleArn returns the RoleArn field value
func (o *AwsCollectionAgentIn) GetRoleArn() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RoleArn
}

// GetRoleArnOk returns a tuple with the RoleArn field value
// and a boolean to check if the value has been set.
func (o *AwsCollectionAgentIn) GetRoleArnOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RoleArn, true
}

// SetRoleArn sets field value
func (o *AwsCollectionAgentIn) SetRoleArn(v string) {
	o.RoleArn = v
}

func (o AwsCollectionAgentIn) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AwsCollectionAgentIn) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["deployment_id"] = o.DeploymentId
	toSerialize["lambda_function_arn"] = o.LambdaFunctionArn
	toSerialize["role_arn"] = o.RoleArn
	return toSerialize, nil
}

func (o *AwsCollectionAgentIn) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"deployment_id",
		"lambda_function_arn",
		"role_arn",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAwsCollectionAgentIn := _AwsCollectionAgentIn{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAwsCollectionAgentIn)

	if err != nil {
		return err
	}

	*o = AwsCollectionAgentIn(varAwsCollectionAgentIn)

	return err
}

type NullableAwsCollectionAgentIn struct {
	value *AwsCollectionAgentIn
	isSet bool
}

func (v NullableAwsCollectionAgentIn) Get() *AwsCollectionAgentIn {
	return v.value
}

func (v *NullableAwsCollectionAgentIn) Set(val *AwsCollectionAgentIn) {
	v.value = val
	v.isSet = true
}

func (v NullableAwsCollectionAgentIn) IsSet() bool {
	return v.isSet
}

func (v *NullableAwsCollectionAgentIn) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAwsCollectionAgentIn(val *AwsCollectionAgentIn) *NullableAwsCollectionAgentIn {
	return &NullableAwsCollectionAgentIn{value: val, isSet: true}
}

func (v NullableAwsCollectionAgentIn) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAwsCollectionAgentIn) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
