/*
Monte Carlo AI API

Programmatic access to the Monte Carlo AI platform.  Every response with a status of 400 or higher is `application/problem+json`, and carries a `code` naming the failure. That includes failures no single operation declares, such as calling a path with a method it does not support, which returns 405.  Every response carries an `X-Request-Id` header, and an error body repeats it as `request_id`. Quote it when reporting a problem. To choose the value yourself, send an `x-correlation-id` header; a value we cannot accept is replaced by a generated one.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package montecarlo

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the MulesoftCredentialsValidateIn type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MulesoftCredentialsValidateIn{}

// MulesoftCredentialsValidateIn Candidate MuleSoft Anypoint credentials to validate.
type MulesoftCredentialsValidateIn struct {
	// Deployment that runs the validations. It has to be one `GET /deployments` lists, and it has to be able to reach the system the credentials are for.
	DeploymentId string `json:"deployment_id"`
	// Client ID of the Anypoint connected app. The app needs the View Environment, Read Deployments and Exchange Viewer scopes.
	AppClientId string `json:"app_client_id"`
	// Secret of the Anypoint connected app. Used for this check and not kept.
	AppClientSecret string `json:"app_client_secret"`
	// Anypoint Platform instance the organization lives on. US when left out.
	Region NullableMulesoftRegion `json:"region,omitempty"`
	// Anypoint organization or business group to collect from. Set it when your Mule applications are deployed in a business group. Leave it out to collect the organization that owns the connected app.
	OrgId NullableString `json:"org_id,omitempty"`
}

type _MulesoftCredentialsValidateIn MulesoftCredentialsValidateIn

// NewMulesoftCredentialsValidateIn instantiates a new MulesoftCredentialsValidateIn object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMulesoftCredentialsValidateIn(deploymentId string, appClientId string, appClientSecret string) *MulesoftCredentialsValidateIn {
	this := MulesoftCredentialsValidateIn{}
	this.DeploymentId = deploymentId
	this.AppClientId = appClientId
	this.AppClientSecret = appClientSecret
	return &this
}

// NewMulesoftCredentialsValidateInWithDefaults instantiates a new MulesoftCredentialsValidateIn object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMulesoftCredentialsValidateInWithDefaults() *MulesoftCredentialsValidateIn {
	this := MulesoftCredentialsValidateIn{}
	return &this
}

// GetDeploymentId returns the DeploymentId field value
func (o *MulesoftCredentialsValidateIn) GetDeploymentId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DeploymentId
}

// GetDeploymentIdOk returns a tuple with the DeploymentId field value
// and a boolean to check if the value has been set.
func (o *MulesoftCredentialsValidateIn) GetDeploymentIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DeploymentId, true
}

// SetDeploymentId sets field value
func (o *MulesoftCredentialsValidateIn) SetDeploymentId(v string) {
	o.DeploymentId = v
}

// GetAppClientId returns the AppClientId field value
func (o *MulesoftCredentialsValidateIn) GetAppClientId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AppClientId
}

// GetAppClientIdOk returns a tuple with the AppClientId field value
// and a boolean to check if the value has been set.
func (o *MulesoftCredentialsValidateIn) GetAppClientIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AppClientId, true
}

// SetAppClientId sets field value
func (o *MulesoftCredentialsValidateIn) SetAppClientId(v string) {
	o.AppClientId = v
}

// GetAppClientSecret returns the AppClientSecret field value
func (o *MulesoftCredentialsValidateIn) GetAppClientSecret() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AppClientSecret
}

// GetAppClientSecretOk returns a tuple with the AppClientSecret field value
// and a boolean to check if the value has been set.
func (o *MulesoftCredentialsValidateIn) GetAppClientSecretOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AppClientSecret, true
}

// SetAppClientSecret sets field value
func (o *MulesoftCredentialsValidateIn) SetAppClientSecret(v string) {
	o.AppClientSecret = v
}

// GetRegion returns the Region field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MulesoftCredentialsValidateIn) GetRegion() MulesoftRegion {
	if o == nil || IsNil(o.Region.Get()) {
		var ret MulesoftRegion
		return ret
	}
	return *o.Region.Get()
}

// GetRegionOk returns a tuple with the Region field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MulesoftCredentialsValidateIn) GetRegionOk() (*MulesoftRegion, bool) {
	if o == nil {
		return nil, false
	}
	return o.Region.Get(), o.Region.IsSet()
}

// HasRegion returns a boolean if a field has been set.
func (o *MulesoftCredentialsValidateIn) HasRegion() bool {
	if o != nil && o.Region.IsSet() {
		return true
	}

	return false
}

// SetRegion gets a reference to the given NullableMulesoftRegion and assigns it to the Region field.
func (o *MulesoftCredentialsValidateIn) SetRegion(v MulesoftRegion) {
	o.Region.Set(&v)
}

// SetRegionNil sets the value for Region to be an explicit nil
func (o *MulesoftCredentialsValidateIn) SetRegionNil() {
	o.Region.Set(nil)
}

// UnsetRegion ensures that no value is present for Region, not even an explicit nil
func (o *MulesoftCredentialsValidateIn) UnsetRegion() {
	o.Region.Unset()
}

// GetOrgId returns the OrgId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MulesoftCredentialsValidateIn) GetOrgId() string {
	if o == nil || IsNil(o.OrgId.Get()) {
		var ret string
		return ret
	}
	return *o.OrgId.Get()
}

// GetOrgIdOk returns a tuple with the OrgId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MulesoftCredentialsValidateIn) GetOrgIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.OrgId.Get(), o.OrgId.IsSet()
}

// HasOrgId returns a boolean if a field has been set.
func (o *MulesoftCredentialsValidateIn) HasOrgId() bool {
	if o != nil && o.OrgId.IsSet() {
		return true
	}

	return false
}

// SetOrgId gets a reference to the given NullableString and assigns it to the OrgId field.
func (o *MulesoftCredentialsValidateIn) SetOrgId(v string) {
	o.OrgId.Set(&v)
}

// SetOrgIdNil sets the value for OrgId to be an explicit nil
func (o *MulesoftCredentialsValidateIn) SetOrgIdNil() {
	o.OrgId.Set(nil)
}

// UnsetOrgId ensures that no value is present for OrgId, not even an explicit nil
func (o *MulesoftCredentialsValidateIn) UnsetOrgId() {
	o.OrgId.Unset()
}

func (o MulesoftCredentialsValidateIn) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MulesoftCredentialsValidateIn) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["deployment_id"] = o.DeploymentId
	toSerialize["app_client_id"] = o.AppClientId
	toSerialize["app_client_secret"] = o.AppClientSecret
	if o.Region.IsSet() {
		toSerialize["region"] = o.Region.Get()
	}
	if o.OrgId.IsSet() {
		toSerialize["org_id"] = o.OrgId.Get()
	}
	return toSerialize, nil
}

func (o *MulesoftCredentialsValidateIn) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"deployment_id",
		"app_client_id",
		"app_client_secret",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMulesoftCredentialsValidateIn := _MulesoftCredentialsValidateIn{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMulesoftCredentialsValidateIn)

	if err != nil {
		return err
	}

	*o = MulesoftCredentialsValidateIn(varMulesoftCredentialsValidateIn)

	return err
}

type NullableMulesoftCredentialsValidateIn struct {
	value *MulesoftCredentialsValidateIn
	isSet bool
}

func (v NullableMulesoftCredentialsValidateIn) Get() *MulesoftCredentialsValidateIn {
	return v.value
}

func (v *NullableMulesoftCredentialsValidateIn) Set(val *MulesoftCredentialsValidateIn) {
	v.value = val
	v.isSet = true
}

func (v NullableMulesoftCredentialsValidateIn) IsSet() bool {
	return v.isSet
}

func (v *NullableMulesoftCredentialsValidateIn) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMulesoftCredentialsValidateIn(val *MulesoftCredentialsValidateIn) *NullableMulesoftCredentialsValidateIn {
	return &NullableMulesoftCredentialsValidateIn{value: val, isSet: true}
}

func (v NullableMulesoftCredentialsValidateIn) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMulesoftCredentialsValidateIn) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
