/*
Monte Carlo AI API

Programmatic access to the Monte Carlo AI platform.  Every response with a status of 400 or higher is `application/problem+json`, and carries a `code` naming the failure. That includes failures no single operation declares, such as calling a path with a method it does not support, which returns 405.  Every response carries an `X-Request-Id` header, and an error body repeats it as `request_id`. Quote it when reporting a problem. To choose the value yourself, send an `x-correlation-id` header; a value we cannot accept is replaced by a generated one.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package montecarlo

import (
	"encoding/json"
	"fmt"
	"time"
)

// checks if the AzureKeyVaultCredentialsOut type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AzureKeyVaultCredentialsOut{}

// AzureKeyVaultCredentialsOut Where in Azure Key Vault a connection's credentials live.
type AzureKeyVaultCredentialsOut struct {
	// Unique identifier of the credentials.
	Id string `json:"id"`
	// The connection type the credentials are for, such as `snowflake`. Fixed once created.
	ConnectionType string `json:"connection_type"`
	// Where the secret lives. Fixed once created.
	StorageType CredentialsStorageType `json:"storage_type"`
	// When the credentials were created.
	CreatedTime time.Time `json:"created_time"`
	// BigQuery project the connection reads from. Null unless set.
	BqProjectId NullableString `json:"bq_project_id"`
	// Databricks SQL warehouse the connection runs queries on. Null unless set.
	SqlWarehouseId NullableString `json:"sql_warehouse_id"`
	// Name of the Azure Key Vault secret holding the connection's credentials.
	AkvSecret string `json:"akv_secret"`
	// Name of the key vault. Null when unset.
	AkvVaultName NullableString `json:"akv_vault_name"`
	// URL of the key vault. Null when unset.
	AkvVaultUrl          NullableString `json:"akv_vault_url"`
	AdditionalProperties map[string]interface{}
}

type _AzureKeyVaultCredentialsOut AzureKeyVaultCredentialsOut

// NewAzureKeyVaultCredentialsOut instantiates a new AzureKeyVaultCredentialsOut object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAzureKeyVaultCredentialsOut(id string, connectionType string, storageType CredentialsStorageType, createdTime time.Time, bqProjectId NullableString, sqlWarehouseId NullableString, akvSecret string, akvVaultName NullableString, akvVaultUrl NullableString) *AzureKeyVaultCredentialsOut {
	this := AzureKeyVaultCredentialsOut{}
	this.Id = id
	this.ConnectionType = connectionType
	this.StorageType = storageType
	this.CreatedTime = createdTime
	this.BqProjectId = bqProjectId
	this.SqlWarehouseId = sqlWarehouseId
	this.AkvSecret = akvSecret
	this.AkvVaultName = akvVaultName
	this.AkvVaultUrl = akvVaultUrl
	return &this
}

// NewAzureKeyVaultCredentialsOutWithDefaults instantiates a new AzureKeyVaultCredentialsOut object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAzureKeyVaultCredentialsOutWithDefaults() *AzureKeyVaultCredentialsOut {
	this := AzureKeyVaultCredentialsOut{}
	return &this
}

// GetId returns the Id field value
func (o *AzureKeyVaultCredentialsOut) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *AzureKeyVaultCredentialsOut) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *AzureKeyVaultCredentialsOut) SetId(v string) {
	o.Id = v
}

// GetConnectionType returns the ConnectionType field value
func (o *AzureKeyVaultCredentialsOut) GetConnectionType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ConnectionType
}

// GetConnectionTypeOk returns a tuple with the ConnectionType field value
// and a boolean to check if the value has been set.
func (o *AzureKeyVaultCredentialsOut) GetConnectionTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ConnectionType, true
}

// SetConnectionType sets field value
func (o *AzureKeyVaultCredentialsOut) SetConnectionType(v string) {
	o.ConnectionType = v
}

// GetStorageType returns the StorageType field value
func (o *AzureKeyVaultCredentialsOut) GetStorageType() CredentialsStorageType {
	if o == nil {
		var ret CredentialsStorageType
		return ret
	}

	return o.StorageType
}

// GetStorageTypeOk returns a tuple with the StorageType field value
// and a boolean to check if the value has been set.
func (o *AzureKeyVaultCredentialsOut) GetStorageTypeOk() (*CredentialsStorageType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StorageType, true
}

// SetStorageType sets field value
func (o *AzureKeyVaultCredentialsOut) SetStorageType(v CredentialsStorageType) {
	o.StorageType = v
}

// GetCreatedTime returns the CreatedTime field value
func (o *AzureKeyVaultCredentialsOut) GetCreatedTime() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedTime
}

// GetCreatedTimeOk returns a tuple with the CreatedTime field value
// and a boolean to check if the value has been set.
func (o *AzureKeyVaultCredentialsOut) GetCreatedTimeOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedTime, true
}

// SetCreatedTime sets field value
func (o *AzureKeyVaultCredentialsOut) SetCreatedTime(v time.Time) {
	o.CreatedTime = v
}

// GetBqProjectId returns the BqProjectId field value
// If the value is explicit nil, the zero value for string will be returned
func (o *AzureKeyVaultCredentialsOut) GetBqProjectId() string {
	if o == nil || o.BqProjectId.Get() == nil {
		var ret string
		return ret
	}

	return *o.BqProjectId.Get()
}

// GetBqProjectIdOk returns a tuple with the BqProjectId field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AzureKeyVaultCredentialsOut) GetBqProjectIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.BqProjectId.Get(), o.BqProjectId.IsSet()
}

// SetBqProjectId sets field value
func (o *AzureKeyVaultCredentialsOut) SetBqProjectId(v string) {
	o.BqProjectId.Set(&v)
}

// GetSqlWarehouseId returns the SqlWarehouseId field value
// If the value is explicit nil, the zero value for string will be returned
func (o *AzureKeyVaultCredentialsOut) GetSqlWarehouseId() string {
	if o == nil || o.SqlWarehouseId.Get() == nil {
		var ret string
		return ret
	}

	return *o.SqlWarehouseId.Get()
}

// GetSqlWarehouseIdOk returns a tuple with the SqlWarehouseId field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AzureKeyVaultCredentialsOut) GetSqlWarehouseIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SqlWarehouseId.Get(), o.SqlWarehouseId.IsSet()
}

// SetSqlWarehouseId sets field value
func (o *AzureKeyVaultCredentialsOut) SetSqlWarehouseId(v string) {
	o.SqlWarehouseId.Set(&v)
}

// GetAkvSecret returns the AkvSecret field value
func (o *AzureKeyVaultCredentialsOut) GetAkvSecret() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AkvSecret
}

// GetAkvSecretOk returns a tuple with the AkvSecret field value
// and a boolean to check if the value has been set.
func (o *AzureKeyVaultCredentialsOut) GetAkvSecretOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AkvSecret, true
}

// SetAkvSecret sets field value
func (o *AzureKeyVaultCredentialsOut) SetAkvSecret(v string) {
	o.AkvSecret = v
}

// GetAkvVaultName returns the AkvVaultName field value
// If the value is explicit nil, the zero value for string will be returned
func (o *AzureKeyVaultCredentialsOut) GetAkvVaultName() string {
	if o == nil || o.AkvVaultName.Get() == nil {
		var ret string
		return ret
	}

	return *o.AkvVaultName.Get()
}

// GetAkvVaultNameOk returns a tuple with the AkvVaultName field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AzureKeyVaultCredentialsOut) GetAkvVaultNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.AkvVaultName.Get(), o.AkvVaultName.IsSet()
}

// SetAkvVaultName sets field value
func (o *AzureKeyVaultCredentialsOut) SetAkvVaultName(v string) {
	o.AkvVaultName.Set(&v)
}

// GetAkvVaultUrl returns the AkvVaultUrl field value
// If the value is explicit nil, the zero value for string will be returned
func (o *AzureKeyVaultCredentialsOut) GetAkvVaultUrl() string {
	if o == nil || o.AkvVaultUrl.Get() == nil {
		var ret string
		return ret
	}

	return *o.AkvVaultUrl.Get()
}

// GetAkvVaultUrlOk returns a tuple with the AkvVaultUrl field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AzureKeyVaultCredentialsOut) GetAkvVaultUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.AkvVaultUrl.Get(), o.AkvVaultUrl.IsSet()
}

// SetAkvVaultUrl sets field value
func (o *AzureKeyVaultCredentialsOut) SetAkvVaultUrl(v string) {
	o.AkvVaultUrl.Set(&v)
}

func (o AzureKeyVaultCredentialsOut) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AzureKeyVaultCredentialsOut) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["connection_type"] = o.ConnectionType
	toSerialize["storage_type"] = o.StorageType
	toSerialize["created_time"] = o.CreatedTime
	toSerialize["bq_project_id"] = o.BqProjectId.Get()
	toSerialize["sql_warehouse_id"] = o.SqlWarehouseId.Get()
	toSerialize["akv_secret"] = o.AkvSecret
	toSerialize["akv_vault_name"] = o.AkvVaultName.Get()
	toSerialize["akv_vault_url"] = o.AkvVaultUrl.Get()

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *AzureKeyVaultCredentialsOut) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"connection_type",
		"storage_type",
		"created_time",
		"bq_project_id",
		"sql_warehouse_id",
		"akv_secret",
		"akv_vault_name",
		"akv_vault_url",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAzureKeyVaultCredentialsOut := _AzureKeyVaultCredentialsOut{}

	err = json.Unmarshal(data, &varAzureKeyVaultCredentialsOut)

	if err != nil {
		return err
	}

	*o = AzureKeyVaultCredentialsOut(varAzureKeyVaultCredentialsOut)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "connection_type")
		delete(additionalProperties, "storage_type")
		delete(additionalProperties, "created_time")
		delete(additionalProperties, "bq_project_id")
		delete(additionalProperties, "sql_warehouse_id")
		delete(additionalProperties, "akv_secret")
		delete(additionalProperties, "akv_vault_name")
		delete(additionalProperties, "akv_vault_url")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAzureKeyVaultCredentialsOut struct {
	value *AzureKeyVaultCredentialsOut
	isSet bool
}

func (v NullableAzureKeyVaultCredentialsOut) Get() *AzureKeyVaultCredentialsOut {
	return v.value
}

func (v *NullableAzureKeyVaultCredentialsOut) Set(val *AzureKeyVaultCredentialsOut) {
	v.value = val
	v.isSet = true
}

func (v NullableAzureKeyVaultCredentialsOut) IsSet() bool {
	return v.isSet
}

func (v *NullableAzureKeyVaultCredentialsOut) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAzureKeyVaultCredentialsOut(val *AzureKeyVaultCredentialsOut) *NullableAzureKeyVaultCredentialsOut {
	return &NullableAzureKeyVaultCredentialsOut{value: val, isSet: true}
}

func (v NullableAzureKeyVaultCredentialsOut) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAzureKeyVaultCredentialsOut) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
