/*
Monte Carlo AI API

Programmatic access to the Monte Carlo AI platform.  Every response with a status of 400 or higher is `application/problem+json`, and carries a `code` naming the failure. That includes failures no single operation declares, such as calling a path with a method it does not support, which returns 405.  Every response carries an `X-Request-Id` header, and an error body repeats it as `request_id`. Quote it when reporting a problem. To choose the value yourself, send an `x-correlation-id` header; a value we cannot accept is replaced by a generated one.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package montecarlo

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the StarburstGalaxyCredentialsIn type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StarburstGalaxyCredentialsIn{}

// StarburstGalaxyCredentialsIn What to create Starburst Galaxy credentials with.
type StarburstGalaxyCredentialsIn struct {
	// Hostname of the database endpoint.
	Host string `json:"host"`
	// Port the database listens on.
	Port int32 `json:"port"`
	// Database user Monte Carlo logs in as.
	User string `json:"user"`
	// Password of the database user. Stored by Monte Carlo and never returned.
	Password string `json:"password"`
	// Database to connect to.
	DbName NullableString `json:"db_name,omitempty"`
}

type _StarburstGalaxyCredentialsIn StarburstGalaxyCredentialsIn

// NewStarburstGalaxyCredentialsIn instantiates a new StarburstGalaxyCredentialsIn object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStarburstGalaxyCredentialsIn(host string, port int32, user string, password string) *StarburstGalaxyCredentialsIn {
	this := StarburstGalaxyCredentialsIn{}
	this.Host = host
	this.Port = port
	this.User = user
	this.Password = password
	return &this
}

// NewStarburstGalaxyCredentialsInWithDefaults instantiates a new StarburstGalaxyCredentialsIn object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStarburstGalaxyCredentialsInWithDefaults() *StarburstGalaxyCredentialsIn {
	this := StarburstGalaxyCredentialsIn{}
	return &this
}

// GetHost returns the Host field value
func (o *StarburstGalaxyCredentialsIn) GetHost() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Host
}

// GetHostOk returns a tuple with the Host field value
// and a boolean to check if the value has been set.
func (o *StarburstGalaxyCredentialsIn) GetHostOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Host, true
}

// SetHost sets field value
func (o *StarburstGalaxyCredentialsIn) SetHost(v string) {
	o.Host = v
}

// GetPort returns the Port field value
func (o *StarburstGalaxyCredentialsIn) GetPort() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Port
}

// GetPortOk returns a tuple with the Port field value
// and a boolean to check if the value has been set.
func (o *StarburstGalaxyCredentialsIn) GetPortOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Port, true
}

// SetPort sets field value
func (o *StarburstGalaxyCredentialsIn) SetPort(v int32) {
	o.Port = v
}

// GetUser returns the User field value
func (o *StarburstGalaxyCredentialsIn) GetUser() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.User
}

// GetUserOk returns a tuple with the User field value
// and a boolean to check if the value has been set.
func (o *StarburstGalaxyCredentialsIn) GetUserOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.User, true
}

// SetUser sets field value
func (o *StarburstGalaxyCredentialsIn) SetUser(v string) {
	o.User = v
}

// GetPassword returns the Password field value
func (o *StarburstGalaxyCredentialsIn) GetPassword() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Password
}

// GetPasswordOk returns a tuple with the Password field value
// and a boolean to check if the value has been set.
func (o *StarburstGalaxyCredentialsIn) GetPasswordOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Password, true
}

// SetPassword sets field value
func (o *StarburstGalaxyCredentialsIn) SetPassword(v string) {
	o.Password = v
}

// GetDbName returns the DbName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *StarburstGalaxyCredentialsIn) GetDbName() string {
	if o == nil || IsNil(o.DbName.Get()) {
		var ret string
		return ret
	}
	return *o.DbName.Get()
}

// GetDbNameOk returns a tuple with the DbName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *StarburstGalaxyCredentialsIn) GetDbNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DbName.Get(), o.DbName.IsSet()
}

// HasDbName returns a boolean if a field has been set.
func (o *StarburstGalaxyCredentialsIn) HasDbName() bool {
	if o != nil && o.DbName.IsSet() {
		return true
	}

	return false
}

// SetDbName gets a reference to the given NullableString and assigns it to the DbName field.
func (o *StarburstGalaxyCredentialsIn) SetDbName(v string) {
	o.DbName.Set(&v)
}

// SetDbNameNil sets the value for DbName to be an explicit nil
func (o *StarburstGalaxyCredentialsIn) SetDbNameNil() {
	o.DbName.Set(nil)
}

// UnsetDbName ensures that no value is present for DbName, not even an explicit nil
func (o *StarburstGalaxyCredentialsIn) UnsetDbName() {
	o.DbName.Unset()
}

func (o StarburstGalaxyCredentialsIn) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StarburstGalaxyCredentialsIn) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["host"] = o.Host
	toSerialize["port"] = o.Port
	toSerialize["user"] = o.User
	toSerialize["password"] = o.Password
	if o.DbName.IsSet() {
		toSerialize["db_name"] = o.DbName.Get()
	}
	return toSerialize, nil
}

func (o *StarburstGalaxyCredentialsIn) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"host",
		"port",
		"user",
		"password",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varStarburstGalaxyCredentialsIn := _StarburstGalaxyCredentialsIn{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varStarburstGalaxyCredentialsIn)

	if err != nil {
		return err
	}

	*o = StarburstGalaxyCredentialsIn(varStarburstGalaxyCredentialsIn)

	return err
}

type NullableStarburstGalaxyCredentialsIn struct {
	value *StarburstGalaxyCredentialsIn
	isSet bool
}

func (v NullableStarburstGalaxyCredentialsIn) Get() *StarburstGalaxyCredentialsIn {
	return v.value
}

func (v *NullableStarburstGalaxyCredentialsIn) Set(val *StarburstGalaxyCredentialsIn) {
	v.value = val
	v.isSet = true
}

func (v NullableStarburstGalaxyCredentialsIn) IsSet() bool {
	return v.isSet
}

func (v *NullableStarburstGalaxyCredentialsIn) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStarburstGalaxyCredentialsIn(val *StarburstGalaxyCredentialsIn) *NullableStarburstGalaxyCredentialsIn {
	return &NullableStarburstGalaxyCredentialsIn{value: val, isSet: true}
}

func (v NullableStarburstGalaxyCredentialsIn) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStarburstGalaxyCredentialsIn) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
