/*
Monte Carlo AI API

Programmatic access to the Monte Carlo AI platform.  Every response with a status of 400 or higher is `application/problem+json`, and carries a `code` naming the failure. That includes failures no single operation declares, such as calling a path with a method it does not support, which returns 405.  Every response carries an `X-Request-Id` header, and an error body repeats it as `request_id`. Quote it when reporting a problem. To choose the value yourself, send an `x-correlation-id` header; a value we cannot accept is replaced by a generated one.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package montecarlo

import (
	"encoding/json"
	"fmt"
	"time"
)

// checks if the SnowflakeCredentialsOut type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SnowflakeCredentialsOut{}

// SnowflakeCredentialsOut Snowflake key pair credentials Monte Carlo stores. The key itself is never returned.
type SnowflakeCredentialsOut struct {
	// Unique identifier of the credentials.
	Id string `json:"id"`
	// The connection type the credentials are for, such as `snowflake`. Fixed once created.
	ConnectionType string `json:"connection_type"`
	// Where the secret lives. Fixed once created.
	StorageType CredentialsStorageType `json:"storage_type"`
	// When the credentials were created.
	CreatedTime time.Time `json:"created_time"`
	// Snowflake account identifier, without the host suffix.
	Account string `json:"account"`
	// Snowflake user the key pair belongs to.
	User string `json:"user"`
	// Snowflake virtual warehouse queries run in. Null when none is set.
	Warehouse            NullableString `json:"warehouse"`
	AdditionalProperties map[string]interface{}
}

type _SnowflakeCredentialsOut SnowflakeCredentialsOut

// NewSnowflakeCredentialsOut instantiates a new SnowflakeCredentialsOut object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSnowflakeCredentialsOut(id string, connectionType string, storageType CredentialsStorageType, createdTime time.Time, account string, user string, warehouse NullableString) *SnowflakeCredentialsOut {
	this := SnowflakeCredentialsOut{}
	this.Id = id
	this.ConnectionType = connectionType
	this.StorageType = storageType
	this.CreatedTime = createdTime
	this.Account = account
	this.User = user
	this.Warehouse = warehouse
	return &this
}

// NewSnowflakeCredentialsOutWithDefaults instantiates a new SnowflakeCredentialsOut object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSnowflakeCredentialsOutWithDefaults() *SnowflakeCredentialsOut {
	this := SnowflakeCredentialsOut{}
	return &this
}

// GetId returns the Id field value
func (o *SnowflakeCredentialsOut) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *SnowflakeCredentialsOut) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *SnowflakeCredentialsOut) SetId(v string) {
	o.Id = v
}

// GetConnectionType returns the ConnectionType field value
func (o *SnowflakeCredentialsOut) GetConnectionType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ConnectionType
}

// GetConnectionTypeOk returns a tuple with the ConnectionType field value
// and a boolean to check if the value has been set.
func (o *SnowflakeCredentialsOut) GetConnectionTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ConnectionType, true
}

// SetConnectionType sets field value
func (o *SnowflakeCredentialsOut) SetConnectionType(v string) {
	o.ConnectionType = v
}

// GetStorageType returns the StorageType field value
func (o *SnowflakeCredentialsOut) GetStorageType() CredentialsStorageType {
	if o == nil {
		var ret CredentialsStorageType
		return ret
	}

	return o.StorageType
}

// GetStorageTypeOk returns a tuple with the StorageType field value
// and a boolean to check if the value has been set.
func (o *SnowflakeCredentialsOut) GetStorageTypeOk() (*CredentialsStorageType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StorageType, true
}

// SetStorageType sets field value
func (o *SnowflakeCredentialsOut) SetStorageType(v CredentialsStorageType) {
	o.StorageType = v
}

// GetCreatedTime returns the CreatedTime field value
func (o *SnowflakeCredentialsOut) GetCreatedTime() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedTime
}

// GetCreatedTimeOk returns a tuple with the CreatedTime field value
// and a boolean to check if the value has been set.
func (o *SnowflakeCredentialsOut) GetCreatedTimeOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedTime, true
}

// SetCreatedTime sets field value
func (o *SnowflakeCredentialsOut) SetCreatedTime(v time.Time) {
	o.CreatedTime = v
}

// GetAccount returns the Account field value
func (o *SnowflakeCredentialsOut) GetAccount() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Account
}

// GetAccountOk returns a tuple with the Account field value
// and a boolean to check if the value has been set.
func (o *SnowflakeCredentialsOut) GetAccountOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Account, true
}

// SetAccount sets field value
func (o *SnowflakeCredentialsOut) SetAccount(v string) {
	o.Account = v
}

// GetUser returns the User field value
func (o *SnowflakeCredentialsOut) GetUser() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.User
}

// GetUserOk returns a tuple with the User field value
// and a boolean to check if the value has been set.
func (o *SnowflakeCredentialsOut) GetUserOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.User, true
}

// SetUser sets field value
func (o *SnowflakeCredentialsOut) SetUser(v string) {
	o.User = v
}

// GetWarehouse returns the Warehouse field value
// If the value is explicit nil, the zero value for string will be returned
func (o *SnowflakeCredentialsOut) GetWarehouse() string {
	if o == nil || o.Warehouse.Get() == nil {
		var ret string
		return ret
	}

	return *o.Warehouse.Get()
}

// GetWarehouseOk returns a tuple with the Warehouse field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SnowflakeCredentialsOut) GetWarehouseOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Warehouse.Get(), o.Warehouse.IsSet()
}

// SetWarehouse sets field value
func (o *SnowflakeCredentialsOut) SetWarehouse(v string) {
	o.Warehouse.Set(&v)
}

func (o SnowflakeCredentialsOut) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SnowflakeCredentialsOut) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["connection_type"] = o.ConnectionType
	toSerialize["storage_type"] = o.StorageType
	toSerialize["created_time"] = o.CreatedTime
	toSerialize["account"] = o.Account
	toSerialize["user"] = o.User
	toSerialize["warehouse"] = o.Warehouse.Get()

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *SnowflakeCredentialsOut) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"connection_type",
		"storage_type",
		"created_time",
		"account",
		"user",
		"warehouse",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSnowflakeCredentialsOut := _SnowflakeCredentialsOut{}

	err = json.Unmarshal(data, &varSnowflakeCredentialsOut)

	if err != nil {
		return err
	}

	*o = SnowflakeCredentialsOut(varSnowflakeCredentialsOut)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "connection_type")
		delete(additionalProperties, "storage_type")
		delete(additionalProperties, "created_time")
		delete(additionalProperties, "account")
		delete(additionalProperties, "user")
		delete(additionalProperties, "warehouse")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSnowflakeCredentialsOut struct {
	value *SnowflakeCredentialsOut
	isSet bool
}

func (v NullableSnowflakeCredentialsOut) Get() *SnowflakeCredentialsOut {
	return v.value
}

func (v *NullableSnowflakeCredentialsOut) Set(val *SnowflakeCredentialsOut) {
	v.value = val
	v.isSet = true
}

func (v NullableSnowflakeCredentialsOut) IsSet() bool {
	return v.isSet
}

func (v *NullableSnowflakeCredentialsOut) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSnowflakeCredentialsOut(val *SnowflakeCredentialsOut) *NullableSnowflakeCredentialsOut {
	return &NullableSnowflakeCredentialsOut{value: val, isSet: true}
}

func (v NullableSnowflakeCredentialsOut) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSnowflakeCredentialsOut) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
