/*
Monte Carlo AI API

Programmatic access to the Monte Carlo AI platform.  Every response with a status of 400 or higher is `application/problem+json`, and carries a `code` naming the failure. That includes failures no single operation declares, such as calling a path with a method it does not support, which returns 405.  Every response carries an `X-Request-Id` header, and an error body repeats it as `request_id`. Quote it when reporting a problem. To choose the value yourself, send an `x-correlation-id` header; a value we cannot accept is replaced by a generated one.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package montecarlo

import (
	"encoding/json"
	"fmt"
)

// ValidationStatus Whether one validation ran.  `completed`, `failed` and `timed_out` each carry a verdict, in `passed`. `pending`, `running` and `skipped` do not.
type ValidationStatus string

// List of ValidationStatus
const (
	VALIDATIONSTATUS_PENDING   ValidationStatus = "pending"
	VALIDATIONSTATUS_RUNNING   ValidationStatus = "running"
	VALIDATIONSTATUS_COMPLETED ValidationStatus = "completed"
	VALIDATIONSTATUS_FAILED    ValidationStatus = "failed"
	VALIDATIONSTATUS_TIMED_OUT ValidationStatus = "timed_out"
	VALIDATIONSTATUS_SKIPPED   ValidationStatus = "skipped"
)

// All allowed values of ValidationStatus enum
var AllowedValidationStatusEnumValues = []ValidationStatus{
	"pending",
	"running",
	"completed",
	"failed",
	"timed_out",
	"skipped",
}

func (v *ValidationStatus) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := ValidationStatus(value)
	for _, existing := range AllowedValidationStatusEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	*v = enumTypeValue
	return nil
}

// NewValidationStatusFromValue returns a pointer to a valid ValidationStatus
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewValidationStatusFromValue(v string) (*ValidationStatus, error) {
	ev := ValidationStatus(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for ValidationStatus: valid values are %v", v, AllowedValidationStatusEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v ValidationStatus) IsValid() bool {
	for _, existing := range AllowedValidationStatusEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to ValidationStatus value
func (v ValidationStatus) Ptr() *ValidationStatus {
	return &v
}

type NullableValidationStatus struct {
	value *ValidationStatus
	isSet bool
}

func (v NullableValidationStatus) Get() *ValidationStatus {
	return v.value
}

func (v *NullableValidationStatus) Set(val *ValidationStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableValidationStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableValidationStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableValidationStatus(val *ValidationStatus) *NullableValidationStatus {
	return &NullableValidationStatus{value: val, isSet: true}
}

func (v NullableValidationStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableValidationStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
