/*
Monte Carlo AI API

Programmatic access to the Monte Carlo AI platform.  Every response with a status of 400 or higher is `application/problem+json`, and carries a `code` naming the failure. That includes failures no single operation declares, such as calling a path with a method it does not support, which returns 405.  Every response carries an `X-Request-Id` header, and an error body repeats it as `request_id`. Quote it when reporting a problem. To choose the value yourself, send an `x-correlation-id` header; a value we cannot accept is replaced by a generated one.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package montecarlo

import (
	"encoding/json"
)

// checks if the AzureCollectionDataStorePatch type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AzureCollectionDataStorePatch{}

// AzureCollectionDataStorePatch Details to change on an Azure data store. Only what you send is changed.  A credentials object is the exception: it replaces the stored credentials instead of merging into them, so send every field of the object you send, along with the matching `authentication_type`. Sending only `name` skips the checks against your storage, since a name is not validated against it.
type AzureCollectionDataStorePatch struct {
	// Credentials for `AZURE_STORAGE_ACCOUNT_KEYS`. Send this or `service_principal`, never both.
	StorageAccountKeys NullableStorageAccountKeysCredentialsIn `json:"storage_account_keys,omitempty"`
	// Credentials for `AZURE_STORAGE_SERVICE_PRINCIPAL`. Send this or `storage_account_keys`, never both.
	ServicePrincipal NullableStorageServicePrincipalCredentialsIn `json:"service_principal,omitempty"`
	// Name of the blob container Monte Carlo should use.
	ContainerName NullableString `json:"container_name,omitempty" validate:"regexp=^[a-z0-9][a-z0-9-]{1,61}[a-z0-9]$"`
	// Display name for the data store. Replaces the name its deployment gave it.
	Name NullableString `json:"name,omitempty"`
	// How Monte Carlo authenticates to the storage account. Send it together with the matching credentials object.
	AuthenticationType NullableAzureDataStoreAuthenticationType `json:"authentication_type,omitempty"`
}

// NewAzureCollectionDataStorePatch instantiates a new AzureCollectionDataStorePatch object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAzureCollectionDataStorePatch() *AzureCollectionDataStorePatch {
	this := AzureCollectionDataStorePatch{}
	return &this
}

// NewAzureCollectionDataStorePatchWithDefaults instantiates a new AzureCollectionDataStorePatch object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAzureCollectionDataStorePatchWithDefaults() *AzureCollectionDataStorePatch {
	this := AzureCollectionDataStorePatch{}
	return &this
}

// GetStorageAccountKeys returns the StorageAccountKeys field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AzureCollectionDataStorePatch) GetStorageAccountKeys() StorageAccountKeysCredentialsIn {
	if o == nil || IsNil(o.StorageAccountKeys.Get()) {
		var ret StorageAccountKeysCredentialsIn
		return ret
	}
	return *o.StorageAccountKeys.Get()
}

// GetStorageAccountKeysOk returns a tuple with the StorageAccountKeys field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AzureCollectionDataStorePatch) GetStorageAccountKeysOk() (*StorageAccountKeysCredentialsIn, bool) {
	if o == nil {
		return nil, false
	}
	return o.StorageAccountKeys.Get(), o.StorageAccountKeys.IsSet()
}

// HasStorageAccountKeys returns a boolean if a field has been set.
func (o *AzureCollectionDataStorePatch) HasStorageAccountKeys() bool {
	if o != nil && o.StorageAccountKeys.IsSet() {
		return true
	}

	return false
}

// SetStorageAccountKeys gets a reference to the given NullableStorageAccountKeysCredentialsIn and assigns it to the StorageAccountKeys field.
func (o *AzureCollectionDataStorePatch) SetStorageAccountKeys(v StorageAccountKeysCredentialsIn) {
	o.StorageAccountKeys.Set(&v)
}

// SetStorageAccountKeysNil sets the value for StorageAccountKeys to be an explicit nil
func (o *AzureCollectionDataStorePatch) SetStorageAccountKeysNil() {
	o.StorageAccountKeys.Set(nil)
}

// UnsetStorageAccountKeys ensures that no value is present for StorageAccountKeys, not even an explicit nil
func (o *AzureCollectionDataStorePatch) UnsetStorageAccountKeys() {
	o.StorageAccountKeys.Unset()
}

// GetServicePrincipal returns the ServicePrincipal field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AzureCollectionDataStorePatch) GetServicePrincipal() StorageServicePrincipalCredentialsIn {
	if o == nil || IsNil(o.ServicePrincipal.Get()) {
		var ret StorageServicePrincipalCredentialsIn
		return ret
	}
	return *o.ServicePrincipal.Get()
}

// GetServicePrincipalOk returns a tuple with the ServicePrincipal field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AzureCollectionDataStorePatch) GetServicePrincipalOk() (*StorageServicePrincipalCredentialsIn, bool) {
	if o == nil {
		return nil, false
	}
	return o.ServicePrincipal.Get(), o.ServicePrincipal.IsSet()
}

// HasServicePrincipal returns a boolean if a field has been set.
func (o *AzureCollectionDataStorePatch) HasServicePrincipal() bool {
	if o != nil && o.ServicePrincipal.IsSet() {
		return true
	}

	return false
}

// SetServicePrincipal gets a reference to the given NullableStorageServicePrincipalCredentialsIn and assigns it to the ServicePrincipal field.
func (o *AzureCollectionDataStorePatch) SetServicePrincipal(v StorageServicePrincipalCredentialsIn) {
	o.ServicePrincipal.Set(&v)
}

// SetServicePrincipalNil sets the value for ServicePrincipal to be an explicit nil
func (o *AzureCollectionDataStorePatch) SetServicePrincipalNil() {
	o.ServicePrincipal.Set(nil)
}

// UnsetServicePrincipal ensures that no value is present for ServicePrincipal, not even an explicit nil
func (o *AzureCollectionDataStorePatch) UnsetServicePrincipal() {
	o.ServicePrincipal.Unset()
}

// GetContainerName returns the ContainerName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AzureCollectionDataStorePatch) GetContainerName() string {
	if o == nil || IsNil(o.ContainerName.Get()) {
		var ret string
		return ret
	}
	return *o.ContainerName.Get()
}

// GetContainerNameOk returns a tuple with the ContainerName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AzureCollectionDataStorePatch) GetContainerNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ContainerName.Get(), o.ContainerName.IsSet()
}

// HasContainerName returns a boolean if a field has been set.
func (o *AzureCollectionDataStorePatch) HasContainerName() bool {
	if o != nil && o.ContainerName.IsSet() {
		return true
	}

	return false
}

// SetContainerName gets a reference to the given NullableString and assigns it to the ContainerName field.
func (o *AzureCollectionDataStorePatch) SetContainerName(v string) {
	o.ContainerName.Set(&v)
}

// SetContainerNameNil sets the value for ContainerName to be an explicit nil
func (o *AzureCollectionDataStorePatch) SetContainerNameNil() {
	o.ContainerName.Set(nil)
}

// UnsetContainerName ensures that no value is present for ContainerName, not even an explicit nil
func (o *AzureCollectionDataStorePatch) UnsetContainerName() {
	o.ContainerName.Unset()
}

// GetName returns the Name field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AzureCollectionDataStorePatch) GetName() string {
	if o == nil || IsNil(o.Name.Get()) {
		var ret string
		return ret
	}
	return *o.Name.Get()
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AzureCollectionDataStorePatch) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Name.Get(), o.Name.IsSet()
}

// HasName returns a boolean if a field has been set.
func (o *AzureCollectionDataStorePatch) HasName() bool {
	if o != nil && o.Name.IsSet() {
		return true
	}

	return false
}

// SetName gets a reference to the given NullableString and assigns it to the Name field.
func (o *AzureCollectionDataStorePatch) SetName(v string) {
	o.Name.Set(&v)
}

// SetNameNil sets the value for Name to be an explicit nil
func (o *AzureCollectionDataStorePatch) SetNameNil() {
	o.Name.Set(nil)
}

// UnsetName ensures that no value is present for Name, not even an explicit nil
func (o *AzureCollectionDataStorePatch) UnsetName() {
	o.Name.Unset()
}

// GetAuthenticationType returns the AuthenticationType field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AzureCollectionDataStorePatch) GetAuthenticationType() AzureDataStoreAuthenticationType {
	if o == nil || IsNil(o.AuthenticationType.Get()) {
		var ret AzureDataStoreAuthenticationType
		return ret
	}
	return *o.AuthenticationType.Get()
}

// GetAuthenticationTypeOk returns a tuple with the AuthenticationType field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AzureCollectionDataStorePatch) GetAuthenticationTypeOk() (*AzureDataStoreAuthenticationType, bool) {
	if o == nil {
		return nil, false
	}
	return o.AuthenticationType.Get(), o.AuthenticationType.IsSet()
}

// HasAuthenticationType returns a boolean if a field has been set.
func (o *AzureCollectionDataStorePatch) HasAuthenticationType() bool {
	if o != nil && o.AuthenticationType.IsSet() {
		return true
	}

	return false
}

// SetAuthenticationType gets a reference to the given NullableAzureDataStoreAuthenticationType and assigns it to the AuthenticationType field.
func (o *AzureCollectionDataStorePatch) SetAuthenticationType(v AzureDataStoreAuthenticationType) {
	o.AuthenticationType.Set(&v)
}

// SetAuthenticationTypeNil sets the value for AuthenticationType to be an explicit nil
func (o *AzureCollectionDataStorePatch) SetAuthenticationTypeNil() {
	o.AuthenticationType.Set(nil)
}

// UnsetAuthenticationType ensures that no value is present for AuthenticationType, not even an explicit nil
func (o *AzureCollectionDataStorePatch) UnsetAuthenticationType() {
	o.AuthenticationType.Unset()
}

func (o AzureCollectionDataStorePatch) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AzureCollectionDataStorePatch) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.StorageAccountKeys.IsSet() {
		toSerialize["storage_account_keys"] = o.StorageAccountKeys.Get()
	}
	if o.ServicePrincipal.IsSet() {
		toSerialize["service_principal"] = o.ServicePrincipal.Get()
	}
	if o.ContainerName.IsSet() {
		toSerialize["container_name"] = o.ContainerName.Get()
	}
	if o.Name.IsSet() {
		toSerialize["name"] = o.Name.Get()
	}
	if o.AuthenticationType.IsSet() {
		toSerialize["authentication_type"] = o.AuthenticationType.Get()
	}
	return toSerialize, nil
}

type NullableAzureCollectionDataStorePatch struct {
	value *AzureCollectionDataStorePatch
	isSet bool
}

func (v NullableAzureCollectionDataStorePatch) Get() *AzureCollectionDataStorePatch {
	return v.value
}

func (v *NullableAzureCollectionDataStorePatch) Set(val *AzureCollectionDataStorePatch) {
	v.value = val
	v.isSet = true
}

func (v NullableAzureCollectionDataStorePatch) IsSet() bool {
	return v.isSet
}

func (v *NullableAzureCollectionDataStorePatch) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAzureCollectionDataStorePatch(val *AzureCollectionDataStorePatch) *NullableAzureCollectionDataStorePatch {
	return &NullableAzureCollectionDataStorePatch{value: val, isSet: true}
}

func (v NullableAzureCollectionDataStorePatch) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAzureCollectionDataStorePatch) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
