/*
Monte Carlo AI API

Programmatic access to the Monte Carlo AI platform.  Every response with a status of 400 or higher is `application/problem+json`, and carries a `code` naming the failure. That includes failures no single operation declares, such as calling a path with a method it does not support, which returns 405.  Every response carries an `X-Request-Id` header, and an error body repeats it as `request_id`. Quote it when reporting a problem. To choose the value yourself, send an `x-correlation-id` header; a value we cannot accept is replaced by a generated one.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package montecarlo

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the StarburstGalaxyCredentialsValidateIn type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StarburstGalaxyCredentialsValidateIn{}

// StarburstGalaxyCredentialsValidateIn Candidate Starburst Galaxy credentials to validate.
type StarburstGalaxyCredentialsValidateIn struct {
	// Deployment that runs the validations. It has to be one `GET /deployments` lists, and it has to be able to reach the system the credentials are for.
	DeploymentId string `json:"deployment_id"`
	// Hostname of the database endpoint.
	Host string `json:"host"`
	// Port the database listens on.
	Port int32 `json:"port"`
	// Database user Monte Carlo logs in as.
	User string `json:"user"`
	// Password of the database user. Used for this check and not kept.
	Password string `json:"password"`
	// Database to connect to.
	DbName NullableString `json:"db_name,omitempty"`
}

type _StarburstGalaxyCredentialsValidateIn StarburstGalaxyCredentialsValidateIn

// NewStarburstGalaxyCredentialsValidateIn instantiates a new StarburstGalaxyCredentialsValidateIn object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStarburstGalaxyCredentialsValidateIn(deploymentId string, host string, port int32, user string, password string) *StarburstGalaxyCredentialsValidateIn {
	this := StarburstGalaxyCredentialsValidateIn{}
	this.DeploymentId = deploymentId
	this.Host = host
	this.Port = port
	this.User = user
	this.Password = password
	return &this
}

// NewStarburstGalaxyCredentialsValidateInWithDefaults instantiates a new StarburstGalaxyCredentialsValidateIn object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStarburstGalaxyCredentialsValidateInWithDefaults() *StarburstGalaxyCredentialsValidateIn {
	this := StarburstGalaxyCredentialsValidateIn{}
	return &this
}

// GetDeploymentId returns the DeploymentId field value
func (o *StarburstGalaxyCredentialsValidateIn) GetDeploymentId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DeploymentId
}

// GetDeploymentIdOk returns a tuple with the DeploymentId field value
// and a boolean to check if the value has been set.
func (o *StarburstGalaxyCredentialsValidateIn) GetDeploymentIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DeploymentId, true
}

// SetDeploymentId sets field value
func (o *StarburstGalaxyCredentialsValidateIn) SetDeploymentId(v string) {
	o.DeploymentId = v
}

// GetHost returns the Host field value
func (o *StarburstGalaxyCredentialsValidateIn) GetHost() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Host
}

// GetHostOk returns a tuple with the Host field value
// and a boolean to check if the value has been set.
func (o *StarburstGalaxyCredentialsValidateIn) GetHostOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Host, true
}

// SetHost sets field value
func (o *StarburstGalaxyCredentialsValidateIn) SetHost(v string) {
	o.Host = v
}

// GetPort returns the Port field value
func (o *StarburstGalaxyCredentialsValidateIn) GetPort() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Port
}

// GetPortOk returns a tuple with the Port field value
// and a boolean to check if the value has been set.
func (o *StarburstGalaxyCredentialsValidateIn) GetPortOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Port, true
}

// SetPort sets field value
func (o *StarburstGalaxyCredentialsValidateIn) SetPort(v int32) {
	o.Port = v
}

// GetUser returns the User field value
func (o *StarburstGalaxyCredentialsValidateIn) GetUser() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.User
}

// GetUserOk returns a tuple with the User field value
// and a boolean to check if the value has been set.
func (o *StarburstGalaxyCredentialsValidateIn) GetUserOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.User, true
}

// SetUser sets field value
func (o *StarburstGalaxyCredentialsValidateIn) SetUser(v string) {
	o.User = v
}

// GetPassword returns the Password field value
func (o *StarburstGalaxyCredentialsValidateIn) GetPassword() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Password
}

// GetPasswordOk returns a tuple with the Password field value
// and a boolean to check if the value has been set.
func (o *StarburstGalaxyCredentialsValidateIn) GetPasswordOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Password, true
}

// SetPassword sets field value
func (o *StarburstGalaxyCredentialsValidateIn) SetPassword(v string) {
	o.Password = v
}

// GetDbName returns the DbName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *StarburstGalaxyCredentialsValidateIn) GetDbName() string {
	if o == nil || IsNil(o.DbName.Get()) {
		var ret string
		return ret
	}
	return *o.DbName.Get()
}

// GetDbNameOk returns a tuple with the DbName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *StarburstGalaxyCredentialsValidateIn) GetDbNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DbName.Get(), o.DbName.IsSet()
}

// HasDbName returns a boolean if a field has been set.
func (o *StarburstGalaxyCredentialsValidateIn) HasDbName() bool {
	if o != nil && o.DbName.IsSet() {
		return true
	}

	return false
}

// SetDbName gets a reference to the given NullableString and assigns it to the DbName field.
func (o *StarburstGalaxyCredentialsValidateIn) SetDbName(v string) {
	o.DbName.Set(&v)
}

// SetDbNameNil sets the value for DbName to be an explicit nil
func (o *StarburstGalaxyCredentialsValidateIn) SetDbNameNil() {
	o.DbName.Set(nil)
}

// UnsetDbName ensures that no value is present for DbName, not even an explicit nil
func (o *StarburstGalaxyCredentialsValidateIn) UnsetDbName() {
	o.DbName.Unset()
}

func (o StarburstGalaxyCredentialsValidateIn) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StarburstGalaxyCredentialsValidateIn) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["deployment_id"] = o.DeploymentId
	toSerialize["host"] = o.Host
	toSerialize["port"] = o.Port
	toSerialize["user"] = o.User
	toSerialize["password"] = o.Password
	if o.DbName.IsSet() {
		toSerialize["db_name"] = o.DbName.Get()
	}
	return toSerialize, nil
}

func (o *StarburstGalaxyCredentialsValidateIn) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"deployment_id",
		"host",
		"port",
		"user",
		"password",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varStarburstGalaxyCredentialsValidateIn := _StarburstGalaxyCredentialsValidateIn{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varStarburstGalaxyCredentialsValidateIn)

	if err != nil {
		return err
	}

	*o = StarburstGalaxyCredentialsValidateIn(varStarburstGalaxyCredentialsValidateIn)

	return err
}

type NullableStarburstGalaxyCredentialsValidateIn struct {
	value *StarburstGalaxyCredentialsValidateIn
	isSet bool
}

func (v NullableStarburstGalaxyCredentialsValidateIn) Get() *StarburstGalaxyCredentialsValidateIn {
	return v.value
}

func (v *NullableStarburstGalaxyCredentialsValidateIn) Set(val *StarburstGalaxyCredentialsValidateIn) {
	v.value = val
	v.isSet = true
}

func (v NullableStarburstGalaxyCredentialsValidateIn) IsSet() bool {
	return v.isSet
}

func (v *NullableStarburstGalaxyCredentialsValidateIn) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStarburstGalaxyCredentialsValidateIn(val *StarburstGalaxyCredentialsValidateIn) *NullableStarburstGalaxyCredentialsValidateIn {
	return &NullableStarburstGalaxyCredentialsValidateIn{value: val, isSet: true}
}

func (v NullableStarburstGalaxyCredentialsValidateIn) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStarburstGalaxyCredentialsValidateIn) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
