/*
Monte Carlo AI API

Programmatic access to the Monte Carlo AI platform.  Every response with a status of 400 or higher is `application/problem+json`, and carries a `code` naming the failure. That includes failures no single operation declares, such as calling a path with a method it does not support, which returns 405.  Every response carries an `X-Request-Id` header, and an error body repeats it as `request_id`. Quote it when reporting a problem. To choose the value yourself, send an `x-correlation-id` header; a value we cannot accept is replaced by a generated one.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package montecarlo

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the DatabricksSqlWarehouseCredentialsIn type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DatabricksSqlWarehouseCredentialsIn{}

// DatabricksSqlWarehouseCredentialsIn What to create Databricks credentials for running queries with.
type DatabricksSqlWarehouseCredentialsIn struct {
	// URL of the Databricks workspace, or its host name.
	WorkspaceUrl string `json:"workspace_url"`
	// ID of the Databricks SQL warehouse the connection runs on.
	SqlWarehouseId string `json:"sql_warehouse_id"`
	// ID of the Databricks workspace.
	WorkspaceId NullableString `json:"workspace_id,omitempty"`
	// Personal access token or service principal token. Send this, or `oauth_client_id` and `oauth_client_secret`. Stored by Monte Carlo and never returned.
	Token NullableString `json:"token,omitempty"`
	// Client ID of the service principal Monte Carlo signs in as with OAuth. Send it with `oauth_client_secret`, instead of `token`.
	OauthClientId NullableString `json:"oauth_client_id,omitempty"`
	// OAuth secret of the service principal in `oauth_client_id`. Stored by Monte Carlo and never returned.
	OauthClientSecret NullableString `json:"oauth_client_secret,omitempty"`
	// Microsoft Entra ID tenant, for a service principal Azure manages. Send it with `azure_workspace_resource_id` and the OAuth client.
	AzureTenantId NullableString `json:"azure_tenant_id,omitempty"`
	// Azure resource ID of the workspace, for a service principal Azure manages. Send it with `azure_tenant_id` and the OAuth client.
	AzureWorkspaceResourceId NullableString `json:"azure_workspace_resource_id,omitempty"`
}

type _DatabricksSqlWarehouseCredentialsIn DatabricksSqlWarehouseCredentialsIn

// NewDatabricksSqlWarehouseCredentialsIn instantiates a new DatabricksSqlWarehouseCredentialsIn object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDatabricksSqlWarehouseCredentialsIn(workspaceUrl string, sqlWarehouseId string) *DatabricksSqlWarehouseCredentialsIn {
	this := DatabricksSqlWarehouseCredentialsIn{}
	this.WorkspaceUrl = workspaceUrl
	this.SqlWarehouseId = sqlWarehouseId
	return &this
}

// NewDatabricksSqlWarehouseCredentialsInWithDefaults instantiates a new DatabricksSqlWarehouseCredentialsIn object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDatabricksSqlWarehouseCredentialsInWithDefaults() *DatabricksSqlWarehouseCredentialsIn {
	this := DatabricksSqlWarehouseCredentialsIn{}
	return &this
}

// GetWorkspaceUrl returns the WorkspaceUrl field value
func (o *DatabricksSqlWarehouseCredentialsIn) GetWorkspaceUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.WorkspaceUrl
}

// GetWorkspaceUrlOk returns a tuple with the WorkspaceUrl field value
// and a boolean to check if the value has been set.
func (o *DatabricksSqlWarehouseCredentialsIn) GetWorkspaceUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.WorkspaceUrl, true
}

// SetWorkspaceUrl sets field value
func (o *DatabricksSqlWarehouseCredentialsIn) SetWorkspaceUrl(v string) {
	o.WorkspaceUrl = v
}

// GetSqlWarehouseId returns the SqlWarehouseId field value
func (o *DatabricksSqlWarehouseCredentialsIn) GetSqlWarehouseId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SqlWarehouseId
}

// GetSqlWarehouseIdOk returns a tuple with the SqlWarehouseId field value
// and a boolean to check if the value has been set.
func (o *DatabricksSqlWarehouseCredentialsIn) GetSqlWarehouseIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SqlWarehouseId, true
}

// SetSqlWarehouseId sets field value
func (o *DatabricksSqlWarehouseCredentialsIn) SetSqlWarehouseId(v string) {
	o.SqlWarehouseId = v
}

// GetWorkspaceId returns the WorkspaceId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DatabricksSqlWarehouseCredentialsIn) GetWorkspaceId() string {
	if o == nil || IsNil(o.WorkspaceId.Get()) {
		var ret string
		return ret
	}
	return *o.WorkspaceId.Get()
}

// GetWorkspaceIdOk returns a tuple with the WorkspaceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DatabricksSqlWarehouseCredentialsIn) GetWorkspaceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.WorkspaceId.Get(), o.WorkspaceId.IsSet()
}

// HasWorkspaceId returns a boolean if a field has been set.
func (o *DatabricksSqlWarehouseCredentialsIn) HasWorkspaceId() bool {
	if o != nil && o.WorkspaceId.IsSet() {
		return true
	}

	return false
}

// SetWorkspaceId gets a reference to the given NullableString and assigns it to the WorkspaceId field.
func (o *DatabricksSqlWarehouseCredentialsIn) SetWorkspaceId(v string) {
	o.WorkspaceId.Set(&v)
}

// SetWorkspaceIdNil sets the value for WorkspaceId to be an explicit nil
func (o *DatabricksSqlWarehouseCredentialsIn) SetWorkspaceIdNil() {
	o.WorkspaceId.Set(nil)
}

// UnsetWorkspaceId ensures that no value is present for WorkspaceId, not even an explicit nil
func (o *DatabricksSqlWarehouseCredentialsIn) UnsetWorkspaceId() {
	o.WorkspaceId.Unset()
}

// GetToken returns the Token field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DatabricksSqlWarehouseCredentialsIn) GetToken() string {
	if o == nil || IsNil(o.Token.Get()) {
		var ret string
		return ret
	}
	return *o.Token.Get()
}

// GetTokenOk returns a tuple with the Token field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DatabricksSqlWarehouseCredentialsIn) GetTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Token.Get(), o.Token.IsSet()
}

// HasToken returns a boolean if a field has been set.
func (o *DatabricksSqlWarehouseCredentialsIn) HasToken() bool {
	if o != nil && o.Token.IsSet() {
		return true
	}

	return false
}

// SetToken gets a reference to the given NullableString and assigns it to the Token field.
func (o *DatabricksSqlWarehouseCredentialsIn) SetToken(v string) {
	o.Token.Set(&v)
}

// SetTokenNil sets the value for Token to be an explicit nil
func (o *DatabricksSqlWarehouseCredentialsIn) SetTokenNil() {
	o.Token.Set(nil)
}

// UnsetToken ensures that no value is present for Token, not even an explicit nil
func (o *DatabricksSqlWarehouseCredentialsIn) UnsetToken() {
	o.Token.Unset()
}

// GetOauthClientId returns the OauthClientId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DatabricksSqlWarehouseCredentialsIn) GetOauthClientId() string {
	if o == nil || IsNil(o.OauthClientId.Get()) {
		var ret string
		return ret
	}
	return *o.OauthClientId.Get()
}

// GetOauthClientIdOk returns a tuple with the OauthClientId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DatabricksSqlWarehouseCredentialsIn) GetOauthClientIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.OauthClientId.Get(), o.OauthClientId.IsSet()
}

// HasOauthClientId returns a boolean if a field has been set.
func (o *DatabricksSqlWarehouseCredentialsIn) HasOauthClientId() bool {
	if o != nil && o.OauthClientId.IsSet() {
		return true
	}

	return false
}

// SetOauthClientId gets a reference to the given NullableString and assigns it to the OauthClientId field.
func (o *DatabricksSqlWarehouseCredentialsIn) SetOauthClientId(v string) {
	o.OauthClientId.Set(&v)
}

// SetOauthClientIdNil sets the value for OauthClientId to be an explicit nil
func (o *DatabricksSqlWarehouseCredentialsIn) SetOauthClientIdNil() {
	o.OauthClientId.Set(nil)
}

// UnsetOauthClientId ensures that no value is present for OauthClientId, not even an explicit nil
func (o *DatabricksSqlWarehouseCredentialsIn) UnsetOauthClientId() {
	o.OauthClientId.Unset()
}

// GetOauthClientSecret returns the OauthClientSecret field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DatabricksSqlWarehouseCredentialsIn) GetOauthClientSecret() string {
	if o == nil || IsNil(o.OauthClientSecret.Get()) {
		var ret string
		return ret
	}
	return *o.OauthClientSecret.Get()
}

// GetOauthClientSecretOk returns a tuple with the OauthClientSecret field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DatabricksSqlWarehouseCredentialsIn) GetOauthClientSecretOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.OauthClientSecret.Get(), o.OauthClientSecret.IsSet()
}

// HasOauthClientSecret returns a boolean if a field has been set.
func (o *DatabricksSqlWarehouseCredentialsIn) HasOauthClientSecret() bool {
	if o != nil && o.OauthClientSecret.IsSet() {
		return true
	}

	return false
}

// SetOauthClientSecret gets a reference to the given NullableString and assigns it to the OauthClientSecret field.
func (o *DatabricksSqlWarehouseCredentialsIn) SetOauthClientSecret(v string) {
	o.OauthClientSecret.Set(&v)
}

// SetOauthClientSecretNil sets the value for OauthClientSecret to be an explicit nil
func (o *DatabricksSqlWarehouseCredentialsIn) SetOauthClientSecretNil() {
	o.OauthClientSecret.Set(nil)
}

// UnsetOauthClientSecret ensures that no value is present for OauthClientSecret, not even an explicit nil
func (o *DatabricksSqlWarehouseCredentialsIn) UnsetOauthClientSecret() {
	o.OauthClientSecret.Unset()
}

// GetAzureTenantId returns the AzureTenantId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DatabricksSqlWarehouseCredentialsIn) GetAzureTenantId() string {
	if o == nil || IsNil(o.AzureTenantId.Get()) {
		var ret string
		return ret
	}
	return *o.AzureTenantId.Get()
}

// GetAzureTenantIdOk returns a tuple with the AzureTenantId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DatabricksSqlWarehouseCredentialsIn) GetAzureTenantIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.AzureTenantId.Get(), o.AzureTenantId.IsSet()
}

// HasAzureTenantId returns a boolean if a field has been set.
func (o *DatabricksSqlWarehouseCredentialsIn) HasAzureTenantId() bool {
	if o != nil && o.AzureTenantId.IsSet() {
		return true
	}

	return false
}

// SetAzureTenantId gets a reference to the given NullableString and assigns it to the AzureTenantId field.
func (o *DatabricksSqlWarehouseCredentialsIn) SetAzureTenantId(v string) {
	o.AzureTenantId.Set(&v)
}

// SetAzureTenantIdNil sets the value for AzureTenantId to be an explicit nil
func (o *DatabricksSqlWarehouseCredentialsIn) SetAzureTenantIdNil() {
	o.AzureTenantId.Set(nil)
}

// UnsetAzureTenantId ensures that no value is present for AzureTenantId, not even an explicit nil
func (o *DatabricksSqlWarehouseCredentialsIn) UnsetAzureTenantId() {
	o.AzureTenantId.Unset()
}

// GetAzureWorkspaceResourceId returns the AzureWorkspaceResourceId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DatabricksSqlWarehouseCredentialsIn) GetAzureWorkspaceResourceId() string {
	if o == nil || IsNil(o.AzureWorkspaceResourceId.Get()) {
		var ret string
		return ret
	}
	return *o.AzureWorkspaceResourceId.Get()
}

// GetAzureWorkspaceResourceIdOk returns a tuple with the AzureWorkspaceResourceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DatabricksSqlWarehouseCredentialsIn) GetAzureWorkspaceResourceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.AzureWorkspaceResourceId.Get(), o.AzureWorkspaceResourceId.IsSet()
}

// HasAzureWorkspaceResourceId returns a boolean if a field has been set.
func (o *DatabricksSqlWarehouseCredentialsIn) HasAzureWorkspaceResourceId() bool {
	if o != nil && o.AzureWorkspaceResourceId.IsSet() {
		return true
	}

	return false
}

// SetAzureWorkspaceResourceId gets a reference to the given NullableString and assigns it to the AzureWorkspaceResourceId field.
func (o *DatabricksSqlWarehouseCredentialsIn) SetAzureWorkspaceResourceId(v string) {
	o.AzureWorkspaceResourceId.Set(&v)
}

// SetAzureWorkspaceResourceIdNil sets the value for AzureWorkspaceResourceId to be an explicit nil
func (o *DatabricksSqlWarehouseCredentialsIn) SetAzureWorkspaceResourceIdNil() {
	o.AzureWorkspaceResourceId.Set(nil)
}

// UnsetAzureWorkspaceResourceId ensures that no value is present for AzureWorkspaceResourceId, not even an explicit nil
func (o *DatabricksSqlWarehouseCredentialsIn) UnsetAzureWorkspaceResourceId() {
	o.AzureWorkspaceResourceId.Unset()
}

func (o DatabricksSqlWarehouseCredentialsIn) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DatabricksSqlWarehouseCredentialsIn) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["workspace_url"] = o.WorkspaceUrl
	toSerialize["sql_warehouse_id"] = o.SqlWarehouseId
	if o.WorkspaceId.IsSet() {
		toSerialize["workspace_id"] = o.WorkspaceId.Get()
	}
	if o.Token.IsSet() {
		toSerialize["token"] = o.Token.Get()
	}
	if o.OauthClientId.IsSet() {
		toSerialize["oauth_client_id"] = o.OauthClientId.Get()
	}
	if o.OauthClientSecret.IsSet() {
		toSerialize["oauth_client_secret"] = o.OauthClientSecret.Get()
	}
	if o.AzureTenantId.IsSet() {
		toSerialize["azure_tenant_id"] = o.AzureTenantId.Get()
	}
	if o.AzureWorkspaceResourceId.IsSet() {
		toSerialize["azure_workspace_resource_id"] = o.AzureWorkspaceResourceId.Get()
	}
	return toSerialize, nil
}

func (o *DatabricksSqlWarehouseCredentialsIn) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"workspace_url",
		"sql_warehouse_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDatabricksSqlWarehouseCredentialsIn := _DatabricksSqlWarehouseCredentialsIn{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDatabricksSqlWarehouseCredentialsIn)

	if err != nil {
		return err
	}

	*o = DatabricksSqlWarehouseCredentialsIn(varDatabricksSqlWarehouseCredentialsIn)

	return err
}

type NullableDatabricksSqlWarehouseCredentialsIn struct {
	value *DatabricksSqlWarehouseCredentialsIn
	isSet bool
}

func (v NullableDatabricksSqlWarehouseCredentialsIn) Get() *DatabricksSqlWarehouseCredentialsIn {
	return v.value
}

func (v *NullableDatabricksSqlWarehouseCredentialsIn) Set(val *DatabricksSqlWarehouseCredentialsIn) {
	v.value = val
	v.isSet = true
}

func (v NullableDatabricksSqlWarehouseCredentialsIn) IsSet() bool {
	return v.isSet
}

func (v *NullableDatabricksSqlWarehouseCredentialsIn) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDatabricksSqlWarehouseCredentialsIn(val *DatabricksSqlWarehouseCredentialsIn) *NullableDatabricksSqlWarehouseCredentialsIn {
	return &NullableDatabricksSqlWarehouseCredentialsIn{value: val, isSet: true}
}

func (v NullableDatabricksSqlWarehouseCredentialsIn) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDatabricksSqlWarehouseCredentialsIn) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
