/*
Monte Carlo AI API

Programmatic access to the Monte Carlo AI platform.  Every response with a status of 400 or higher is `application/problem+json`, and carries a `code` naming the failure. That includes failures no single operation declares, such as calling a path with a method it does not support, which returns 405.  Every response carries an `X-Request-Id` header, and an error body repeats it as `request_id`. Quote it when reporting a problem. To choose the value yourself, send an `x-correlation-id` header; a value we cannot accept is replaced by a generated one.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package montecarlo

import (
	"encoding/json"
)

// checks if the PostgresCredentialsPatch type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PostgresCredentialsPatch{}

// PostgresCredentialsPatch A change to existing PostgreSQL credentials.  A field left out is unchanged. A setting or an `ssl_*` field set to null is cleared. `password` set to null is unchanged. `host`, `port`, `db_name` and `user` cannot be cleared. Sending an empty body returns the credentials as they are.
type PostgresCredentialsPatch struct {
	// Hostname of the database endpoint.
	Host NullableString `json:"host,omitempty"`
	// Port the database listens on.
	Port NullableInt32 `json:"port,omitempty"`
	// Database to connect to.
	DbName NullableString `json:"db_name,omitempty"`
	// Database user Monte Carlo logs in as.
	User NullableString `json:"user,omitempty"`
	// New password of the database user.
	Password NullableString `json:"password,omitempty"`
	// PEM text of the CA certificate the server's certificate is checked against.
	SslCaData NullableString `json:"ssl_ca_data,omitempty"`
	// Connect without TLS.
	SslDisabled NullableBool `json:"ssl_disabled,omitempty"`
	// Check the server's certificate against the CA.
	SslVerifyCert NullableBool `json:"ssl_verify_cert,omitempty"`
	// Check the certificate and that it names the host.
	SslVerifyIdentity NullableBool `json:"ssl_verify_identity,omitempty"`
	// Encrypt the connection without checking the server's certificate.
	SslSkipCertVerification NullableBool `json:"ssl_skip_cert_verification,omitempty"`
	// Whether `host` is an Amazon RDS Proxy endpoint.
	RdsProxy NullableBool `json:"rds_proxy,omitempty"`
}

// NewPostgresCredentialsPatch instantiates a new PostgresCredentialsPatch object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPostgresCredentialsPatch() *PostgresCredentialsPatch {
	this := PostgresCredentialsPatch{}
	return &this
}

// NewPostgresCredentialsPatchWithDefaults instantiates a new PostgresCredentialsPatch object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPostgresCredentialsPatchWithDefaults() *PostgresCredentialsPatch {
	this := PostgresCredentialsPatch{}
	return &this
}

// GetHost returns the Host field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PostgresCredentialsPatch) GetHost() string {
	if o == nil || IsNil(o.Host.Get()) {
		var ret string
		return ret
	}
	return *o.Host.Get()
}

// GetHostOk returns a tuple with the Host field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PostgresCredentialsPatch) GetHostOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Host.Get(), o.Host.IsSet()
}

// HasHost returns a boolean if a field has been set.
func (o *PostgresCredentialsPatch) HasHost() bool {
	if o != nil && o.Host.IsSet() {
		return true
	}

	return false
}

// SetHost gets a reference to the given NullableString and assigns it to the Host field.
func (o *PostgresCredentialsPatch) SetHost(v string) {
	o.Host.Set(&v)
}

// SetHostNil sets the value for Host to be an explicit nil
func (o *PostgresCredentialsPatch) SetHostNil() {
	o.Host.Set(nil)
}

// UnsetHost ensures that no value is present for Host, not even an explicit nil
func (o *PostgresCredentialsPatch) UnsetHost() {
	o.Host.Unset()
}

// GetPort returns the Port field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PostgresCredentialsPatch) GetPort() int32 {
	if o == nil || IsNil(o.Port.Get()) {
		var ret int32
		return ret
	}
	return *o.Port.Get()
}

// GetPortOk returns a tuple with the Port field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PostgresCredentialsPatch) GetPortOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Port.Get(), o.Port.IsSet()
}

// HasPort returns a boolean if a field has been set.
func (o *PostgresCredentialsPatch) HasPort() bool {
	if o != nil && o.Port.IsSet() {
		return true
	}

	return false
}

// SetPort gets a reference to the given NullableInt32 and assigns it to the Port field.
func (o *PostgresCredentialsPatch) SetPort(v int32) {
	o.Port.Set(&v)
}

// SetPortNil sets the value for Port to be an explicit nil
func (o *PostgresCredentialsPatch) SetPortNil() {
	o.Port.Set(nil)
}

// UnsetPort ensures that no value is present for Port, not even an explicit nil
func (o *PostgresCredentialsPatch) UnsetPort() {
	o.Port.Unset()
}

// GetDbName returns the DbName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PostgresCredentialsPatch) GetDbName() string {
	if o == nil || IsNil(o.DbName.Get()) {
		var ret string
		return ret
	}
	return *o.DbName.Get()
}

// GetDbNameOk returns a tuple with the DbName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PostgresCredentialsPatch) GetDbNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DbName.Get(), o.DbName.IsSet()
}

// HasDbName returns a boolean if a field has been set.
func (o *PostgresCredentialsPatch) HasDbName() bool {
	if o != nil && o.DbName.IsSet() {
		return true
	}

	return false
}

// SetDbName gets a reference to the given NullableString and assigns it to the DbName field.
func (o *PostgresCredentialsPatch) SetDbName(v string) {
	o.DbName.Set(&v)
}

// SetDbNameNil sets the value for DbName to be an explicit nil
func (o *PostgresCredentialsPatch) SetDbNameNil() {
	o.DbName.Set(nil)
}

// UnsetDbName ensures that no value is present for DbName, not even an explicit nil
func (o *PostgresCredentialsPatch) UnsetDbName() {
	o.DbName.Unset()
}

// GetUser returns the User field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PostgresCredentialsPatch) GetUser() string {
	if o == nil || IsNil(o.User.Get()) {
		var ret string
		return ret
	}
	return *o.User.Get()
}

// GetUserOk returns a tuple with the User field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PostgresCredentialsPatch) GetUserOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.User.Get(), o.User.IsSet()
}

// HasUser returns a boolean if a field has been set.
func (o *PostgresCredentialsPatch) HasUser() bool {
	if o != nil && o.User.IsSet() {
		return true
	}

	return false
}

// SetUser gets a reference to the given NullableString and assigns it to the User field.
func (o *PostgresCredentialsPatch) SetUser(v string) {
	o.User.Set(&v)
}

// SetUserNil sets the value for User to be an explicit nil
func (o *PostgresCredentialsPatch) SetUserNil() {
	o.User.Set(nil)
}

// UnsetUser ensures that no value is present for User, not even an explicit nil
func (o *PostgresCredentialsPatch) UnsetUser() {
	o.User.Unset()
}

// GetPassword returns the Password field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PostgresCredentialsPatch) GetPassword() string {
	if o == nil || IsNil(o.Password.Get()) {
		var ret string
		return ret
	}
	return *o.Password.Get()
}

// GetPasswordOk returns a tuple with the Password field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PostgresCredentialsPatch) GetPasswordOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Password.Get(), o.Password.IsSet()
}

// HasPassword returns a boolean if a field has been set.
func (o *PostgresCredentialsPatch) HasPassword() bool {
	if o != nil && o.Password.IsSet() {
		return true
	}

	return false
}

// SetPassword gets a reference to the given NullableString and assigns it to the Password field.
func (o *PostgresCredentialsPatch) SetPassword(v string) {
	o.Password.Set(&v)
}

// SetPasswordNil sets the value for Password to be an explicit nil
func (o *PostgresCredentialsPatch) SetPasswordNil() {
	o.Password.Set(nil)
}

// UnsetPassword ensures that no value is present for Password, not even an explicit nil
func (o *PostgresCredentialsPatch) UnsetPassword() {
	o.Password.Unset()
}

// GetSslCaData returns the SslCaData field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PostgresCredentialsPatch) GetSslCaData() string {
	if o == nil || IsNil(o.SslCaData.Get()) {
		var ret string
		return ret
	}
	return *o.SslCaData.Get()
}

// GetSslCaDataOk returns a tuple with the SslCaData field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PostgresCredentialsPatch) GetSslCaDataOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SslCaData.Get(), o.SslCaData.IsSet()
}

// HasSslCaData returns a boolean if a field has been set.
func (o *PostgresCredentialsPatch) HasSslCaData() bool {
	if o != nil && o.SslCaData.IsSet() {
		return true
	}

	return false
}

// SetSslCaData gets a reference to the given NullableString and assigns it to the SslCaData field.
func (o *PostgresCredentialsPatch) SetSslCaData(v string) {
	o.SslCaData.Set(&v)
}

// SetSslCaDataNil sets the value for SslCaData to be an explicit nil
func (o *PostgresCredentialsPatch) SetSslCaDataNil() {
	o.SslCaData.Set(nil)
}

// UnsetSslCaData ensures that no value is present for SslCaData, not even an explicit nil
func (o *PostgresCredentialsPatch) UnsetSslCaData() {
	o.SslCaData.Unset()
}

// GetSslDisabled returns the SslDisabled field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PostgresCredentialsPatch) GetSslDisabled() bool {
	if o == nil || IsNil(o.SslDisabled.Get()) {
		var ret bool
		return ret
	}
	return *o.SslDisabled.Get()
}

// GetSslDisabledOk returns a tuple with the SslDisabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PostgresCredentialsPatch) GetSslDisabledOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.SslDisabled.Get(), o.SslDisabled.IsSet()
}

// HasSslDisabled returns a boolean if a field has been set.
func (o *PostgresCredentialsPatch) HasSslDisabled() bool {
	if o != nil && o.SslDisabled.IsSet() {
		return true
	}

	return false
}

// SetSslDisabled gets a reference to the given NullableBool and assigns it to the SslDisabled field.
func (o *PostgresCredentialsPatch) SetSslDisabled(v bool) {
	o.SslDisabled.Set(&v)
}

// SetSslDisabledNil sets the value for SslDisabled to be an explicit nil
func (o *PostgresCredentialsPatch) SetSslDisabledNil() {
	o.SslDisabled.Set(nil)
}

// UnsetSslDisabled ensures that no value is present for SslDisabled, not even an explicit nil
func (o *PostgresCredentialsPatch) UnsetSslDisabled() {
	o.SslDisabled.Unset()
}

// GetSslVerifyCert returns the SslVerifyCert field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PostgresCredentialsPatch) GetSslVerifyCert() bool {
	if o == nil || IsNil(o.SslVerifyCert.Get()) {
		var ret bool
		return ret
	}
	return *o.SslVerifyCert.Get()
}

// GetSslVerifyCertOk returns a tuple with the SslVerifyCert field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PostgresCredentialsPatch) GetSslVerifyCertOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.SslVerifyCert.Get(), o.SslVerifyCert.IsSet()
}

// HasSslVerifyCert returns a boolean if a field has been set.
func (o *PostgresCredentialsPatch) HasSslVerifyCert() bool {
	if o != nil && o.SslVerifyCert.IsSet() {
		return true
	}

	return false
}

// SetSslVerifyCert gets a reference to the given NullableBool and assigns it to the SslVerifyCert field.
func (o *PostgresCredentialsPatch) SetSslVerifyCert(v bool) {
	o.SslVerifyCert.Set(&v)
}

// SetSslVerifyCertNil sets the value for SslVerifyCert to be an explicit nil
func (o *PostgresCredentialsPatch) SetSslVerifyCertNil() {
	o.SslVerifyCert.Set(nil)
}

// UnsetSslVerifyCert ensures that no value is present for SslVerifyCert, not even an explicit nil
func (o *PostgresCredentialsPatch) UnsetSslVerifyCert() {
	o.SslVerifyCert.Unset()
}

// GetSslVerifyIdentity returns the SslVerifyIdentity field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PostgresCredentialsPatch) GetSslVerifyIdentity() bool {
	if o == nil || IsNil(o.SslVerifyIdentity.Get()) {
		var ret bool
		return ret
	}
	return *o.SslVerifyIdentity.Get()
}

// GetSslVerifyIdentityOk returns a tuple with the SslVerifyIdentity field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PostgresCredentialsPatch) GetSslVerifyIdentityOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.SslVerifyIdentity.Get(), o.SslVerifyIdentity.IsSet()
}

// HasSslVerifyIdentity returns a boolean if a field has been set.
func (o *PostgresCredentialsPatch) HasSslVerifyIdentity() bool {
	if o != nil && o.SslVerifyIdentity.IsSet() {
		return true
	}

	return false
}

// SetSslVerifyIdentity gets a reference to the given NullableBool and assigns it to the SslVerifyIdentity field.
func (o *PostgresCredentialsPatch) SetSslVerifyIdentity(v bool) {
	o.SslVerifyIdentity.Set(&v)
}

// SetSslVerifyIdentityNil sets the value for SslVerifyIdentity to be an explicit nil
func (o *PostgresCredentialsPatch) SetSslVerifyIdentityNil() {
	o.SslVerifyIdentity.Set(nil)
}

// UnsetSslVerifyIdentity ensures that no value is present for SslVerifyIdentity, not even an explicit nil
func (o *PostgresCredentialsPatch) UnsetSslVerifyIdentity() {
	o.SslVerifyIdentity.Unset()
}

// GetSslSkipCertVerification returns the SslSkipCertVerification field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PostgresCredentialsPatch) GetSslSkipCertVerification() bool {
	if o == nil || IsNil(o.SslSkipCertVerification.Get()) {
		var ret bool
		return ret
	}
	return *o.SslSkipCertVerification.Get()
}

// GetSslSkipCertVerificationOk returns a tuple with the SslSkipCertVerification field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PostgresCredentialsPatch) GetSslSkipCertVerificationOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.SslSkipCertVerification.Get(), o.SslSkipCertVerification.IsSet()
}

// HasSslSkipCertVerification returns a boolean if a field has been set.
func (o *PostgresCredentialsPatch) HasSslSkipCertVerification() bool {
	if o != nil && o.SslSkipCertVerification.IsSet() {
		return true
	}

	return false
}

// SetSslSkipCertVerification gets a reference to the given NullableBool and assigns it to the SslSkipCertVerification field.
func (o *PostgresCredentialsPatch) SetSslSkipCertVerification(v bool) {
	o.SslSkipCertVerification.Set(&v)
}

// SetSslSkipCertVerificationNil sets the value for SslSkipCertVerification to be an explicit nil
func (o *PostgresCredentialsPatch) SetSslSkipCertVerificationNil() {
	o.SslSkipCertVerification.Set(nil)
}

// UnsetSslSkipCertVerification ensures that no value is present for SslSkipCertVerification, not even an explicit nil
func (o *PostgresCredentialsPatch) UnsetSslSkipCertVerification() {
	o.SslSkipCertVerification.Unset()
}

// GetRdsProxy returns the RdsProxy field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PostgresCredentialsPatch) GetRdsProxy() bool {
	if o == nil || IsNil(o.RdsProxy.Get()) {
		var ret bool
		return ret
	}
	return *o.RdsProxy.Get()
}

// GetRdsProxyOk returns a tuple with the RdsProxy field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PostgresCredentialsPatch) GetRdsProxyOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.RdsProxy.Get(), o.RdsProxy.IsSet()
}

// HasRdsProxy returns a boolean if a field has been set.
func (o *PostgresCredentialsPatch) HasRdsProxy() bool {
	if o != nil && o.RdsProxy.IsSet() {
		return true
	}

	return false
}

// SetRdsProxy gets a reference to the given NullableBool and assigns it to the RdsProxy field.
func (o *PostgresCredentialsPatch) SetRdsProxy(v bool) {
	o.RdsProxy.Set(&v)
}

// SetRdsProxyNil sets the value for RdsProxy to be an explicit nil
func (o *PostgresCredentialsPatch) SetRdsProxyNil() {
	o.RdsProxy.Set(nil)
}

// UnsetRdsProxy ensures that no value is present for RdsProxy, not even an explicit nil
func (o *PostgresCredentialsPatch) UnsetRdsProxy() {
	o.RdsProxy.Unset()
}

func (o PostgresCredentialsPatch) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PostgresCredentialsPatch) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Host.IsSet() {
		toSerialize["host"] = o.Host.Get()
	}
	if o.Port.IsSet() {
		toSerialize["port"] = o.Port.Get()
	}
	if o.DbName.IsSet() {
		toSerialize["db_name"] = o.DbName.Get()
	}
	if o.User.IsSet() {
		toSerialize["user"] = o.User.Get()
	}
	if o.Password.IsSet() {
		toSerialize["password"] = o.Password.Get()
	}
	if o.SslCaData.IsSet() {
		toSerialize["ssl_ca_data"] = o.SslCaData.Get()
	}
	if o.SslDisabled.IsSet() {
		toSerialize["ssl_disabled"] = o.SslDisabled.Get()
	}
	if o.SslVerifyCert.IsSet() {
		toSerialize["ssl_verify_cert"] = o.SslVerifyCert.Get()
	}
	if o.SslVerifyIdentity.IsSet() {
		toSerialize["ssl_verify_identity"] = o.SslVerifyIdentity.Get()
	}
	if o.SslSkipCertVerification.IsSet() {
		toSerialize["ssl_skip_cert_verification"] = o.SslSkipCertVerification.Get()
	}
	if o.RdsProxy.IsSet() {
		toSerialize["rds_proxy"] = o.RdsProxy.Get()
	}
	return toSerialize, nil
}

type NullablePostgresCredentialsPatch struct {
	value *PostgresCredentialsPatch
	isSet bool
}

func (v NullablePostgresCredentialsPatch) Get() *PostgresCredentialsPatch {
	return v.value
}

func (v *NullablePostgresCredentialsPatch) Set(val *PostgresCredentialsPatch) {
	v.value = val
	v.isSet = true
}

func (v NullablePostgresCredentialsPatch) IsSet() bool {
	return v.isSet
}

func (v *NullablePostgresCredentialsPatch) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePostgresCredentialsPatch(val *PostgresCredentialsPatch) *NullablePostgresCredentialsPatch {
	return &NullablePostgresCredentialsPatch{value: val, isSet: true}
}

func (v NullablePostgresCredentialsPatch) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePostgresCredentialsPatch) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
