/*
Monte Carlo AI API

Programmatic access to the Monte Carlo AI platform.  Every response with a status of 400 or higher is `application/problem+json`, and carries a `code` naming the failure. That includes failures no single operation declares, such as calling a path with a method it does not support, which returns 405.  Every response carries an `X-Request-Id` header, and an error body repeats it as `request_id`. Quote it when reporting a problem. To choose the value yourself, send an `x-correlation-id` header; a value we cannot accept is replaced by a generated one.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package montecarlo

import (
	"encoding/json"
	"fmt"
)

// TeradataSslMode How the Teradata connection uses TLS.
type TeradataSslMode string

// List of TeradataSslMode
const (
	TERADATASSLMODE_DISABLE     TeradataSslMode = "DISABLE"
	TERADATASSLMODE_ALLOW       TeradataSslMode = "ALLOW"
	TERADATASSLMODE_PREFER      TeradataSslMode = "PREFER"
	TERADATASSLMODE_REQUIRE     TeradataSslMode = "REQUIRE"
	TERADATASSLMODE_VERIFY_CA   TeradataSslMode = "VERIFY-CA"
	TERADATASSLMODE_VERIFY_FULL TeradataSslMode = "VERIFY-FULL"
)

// All allowed values of TeradataSslMode enum
var AllowedTeradataSslModeEnumValues = []TeradataSslMode{
	"DISABLE",
	"ALLOW",
	"PREFER",
	"REQUIRE",
	"VERIFY-CA",
	"VERIFY-FULL",
}

func (v *TeradataSslMode) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := TeradataSslMode(value)
	for _, existing := range AllowedTeradataSslModeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid TeradataSslMode", value)
}

// NewTeradataSslModeFromValue returns a pointer to a valid TeradataSslMode
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewTeradataSslModeFromValue(v string) (*TeradataSslMode, error) {
	ev := TeradataSslMode(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for TeradataSslMode: valid values are %v", v, AllowedTeradataSslModeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v TeradataSslMode) IsValid() bool {
	for _, existing := range AllowedTeradataSslModeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to TeradataSslMode value
func (v TeradataSslMode) Ptr() *TeradataSslMode {
	return &v
}

type NullableTeradataSslMode struct {
	value *TeradataSslMode
	isSet bool
}

func (v NullableTeradataSslMode) Get() *TeradataSslMode {
	return v.value
}

func (v *NullableTeradataSslMode) Set(val *TeradataSslMode) {
	v.value = val
	v.isSet = true
}

func (v NullableTeradataSslMode) IsSet() bool {
	return v.isSet
}

func (v *NullableTeradataSslMode) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTeradataSslMode(val *TeradataSslMode) *NullableTeradataSslMode {
	return &NullableTeradataSslMode{value: val, isSet: true}
}

func (v NullableTeradataSslMode) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTeradataSslMode) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
