/*
Monte Carlo AI API

Programmatic access to the Monte Carlo AI platform.  Every response with a status of 400 or higher is `application/problem+json`, and carries a `code` naming the failure. That includes failures no single operation declares, such as calling a path with a method it does not support, which returns 405.  Every response carries an `X-Request-Id` header, and an error body repeats it as `request_id`. Quote it when reporting a problem. To choose the value yourself, send an `x-correlation-id` header; a value we cannot accept is replaced by a generated one.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package montecarlo

import (
	"encoding/json"
)

// checks if the LookerGitCloneCredentialsPatch type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LookerGitCloneCredentialsPatch{}

// LookerGitCloneCredentialsPatch A change to existing LookML repository credentials.  A field left out is unchanged. `username` and the `ssl_*` fields set to null are cleared. A secret set to null is unchanged. `repo_url` cannot be cleared. Sending `ssh_key` drops a stored username and token, and sending `username` or `token` drops a stored key. Sending an empty body returns the credentials as they are.
type LookerGitCloneCredentialsPatch struct {
	// Git user for an HTTPS clone. Send it with `token`.
	Username NullableString `json:"username,omitempty"`
	// PEM certificate of the CA that signed the git server's certificate.
	SslCaData NullableString `json:"ssl_ca_data,omitempty"`
	// Skip verifying the git server's TLS certificate.
	SslSkipCertVerification NullableBool `json:"ssl_skip_cert_verification,omitempty"`
	// Access token of `username`, for an HTTPS clone. Send this or `ssh_key`. Stored by Monte Carlo and never returned.
	Token NullableString `json:"token,omitempty"`
	// Private key for an SSH clone, as PEM text including its BEGIN and END lines. Send this or `username` and `token`. Stored by Monte Carlo and never returned.
	SshKey NullableString `json:"ssh_key,omitempty"`
	// Clone URL of the LookML repository, over HTTPS or SSH.
	RepoUrl NullableString `json:"repo_url,omitempty"`
}

// NewLookerGitCloneCredentialsPatch instantiates a new LookerGitCloneCredentialsPatch object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLookerGitCloneCredentialsPatch() *LookerGitCloneCredentialsPatch {
	this := LookerGitCloneCredentialsPatch{}
	return &this
}

// NewLookerGitCloneCredentialsPatchWithDefaults instantiates a new LookerGitCloneCredentialsPatch object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLookerGitCloneCredentialsPatchWithDefaults() *LookerGitCloneCredentialsPatch {
	this := LookerGitCloneCredentialsPatch{}
	return &this
}

// GetUsername returns the Username field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *LookerGitCloneCredentialsPatch) GetUsername() string {
	if o == nil || IsNil(o.Username.Get()) {
		var ret string
		return ret
	}
	return *o.Username.Get()
}

// GetUsernameOk returns a tuple with the Username field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *LookerGitCloneCredentialsPatch) GetUsernameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Username.Get(), o.Username.IsSet()
}

// HasUsername returns a boolean if a field has been set.
func (o *LookerGitCloneCredentialsPatch) HasUsername() bool {
	if o != nil && o.Username.IsSet() {
		return true
	}

	return false
}

// SetUsername gets a reference to the given NullableString and assigns it to the Username field.
func (o *LookerGitCloneCredentialsPatch) SetUsername(v string) {
	o.Username.Set(&v)
}

// SetUsernameNil sets the value for Username to be an explicit nil
func (o *LookerGitCloneCredentialsPatch) SetUsernameNil() {
	o.Username.Set(nil)
}

// UnsetUsername ensures that no value is present for Username, not even an explicit nil
func (o *LookerGitCloneCredentialsPatch) UnsetUsername() {
	o.Username.Unset()
}

// GetSslCaData returns the SslCaData field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *LookerGitCloneCredentialsPatch) GetSslCaData() string {
	if o == nil || IsNil(o.SslCaData.Get()) {
		var ret string
		return ret
	}
	return *o.SslCaData.Get()
}

// GetSslCaDataOk returns a tuple with the SslCaData field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *LookerGitCloneCredentialsPatch) GetSslCaDataOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SslCaData.Get(), o.SslCaData.IsSet()
}

// HasSslCaData returns a boolean if a field has been set.
func (o *LookerGitCloneCredentialsPatch) HasSslCaData() bool {
	if o != nil && o.SslCaData.IsSet() {
		return true
	}

	return false
}

// SetSslCaData gets a reference to the given NullableString and assigns it to the SslCaData field.
func (o *LookerGitCloneCredentialsPatch) SetSslCaData(v string) {
	o.SslCaData.Set(&v)
}

// SetSslCaDataNil sets the value for SslCaData to be an explicit nil
func (o *LookerGitCloneCredentialsPatch) SetSslCaDataNil() {
	o.SslCaData.Set(nil)
}

// UnsetSslCaData ensures that no value is present for SslCaData, not even an explicit nil
func (o *LookerGitCloneCredentialsPatch) UnsetSslCaData() {
	o.SslCaData.Unset()
}

// GetSslSkipCertVerification returns the SslSkipCertVerification field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *LookerGitCloneCredentialsPatch) GetSslSkipCertVerification() bool {
	if o == nil || IsNil(o.SslSkipCertVerification.Get()) {
		var ret bool
		return ret
	}
	return *o.SslSkipCertVerification.Get()
}

// GetSslSkipCertVerificationOk returns a tuple with the SslSkipCertVerification field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *LookerGitCloneCredentialsPatch) GetSslSkipCertVerificationOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.SslSkipCertVerification.Get(), o.SslSkipCertVerification.IsSet()
}

// HasSslSkipCertVerification returns a boolean if a field has been set.
func (o *LookerGitCloneCredentialsPatch) HasSslSkipCertVerification() bool {
	if o != nil && o.SslSkipCertVerification.IsSet() {
		return true
	}

	return false
}

// SetSslSkipCertVerification gets a reference to the given NullableBool and assigns it to the SslSkipCertVerification field.
func (o *LookerGitCloneCredentialsPatch) SetSslSkipCertVerification(v bool) {
	o.SslSkipCertVerification.Set(&v)
}

// SetSslSkipCertVerificationNil sets the value for SslSkipCertVerification to be an explicit nil
func (o *LookerGitCloneCredentialsPatch) SetSslSkipCertVerificationNil() {
	o.SslSkipCertVerification.Set(nil)
}

// UnsetSslSkipCertVerification ensures that no value is present for SslSkipCertVerification, not even an explicit nil
func (o *LookerGitCloneCredentialsPatch) UnsetSslSkipCertVerification() {
	o.SslSkipCertVerification.Unset()
}

// GetToken returns the Token field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *LookerGitCloneCredentialsPatch) GetToken() string {
	if o == nil || IsNil(o.Token.Get()) {
		var ret string
		return ret
	}
	return *o.Token.Get()
}

// GetTokenOk returns a tuple with the Token field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *LookerGitCloneCredentialsPatch) GetTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Token.Get(), o.Token.IsSet()
}

// HasToken returns a boolean if a field has been set.
func (o *LookerGitCloneCredentialsPatch) HasToken() bool {
	if o != nil && o.Token.IsSet() {
		return true
	}

	return false
}

// SetToken gets a reference to the given NullableString and assigns it to the Token field.
func (o *LookerGitCloneCredentialsPatch) SetToken(v string) {
	o.Token.Set(&v)
}

// SetTokenNil sets the value for Token to be an explicit nil
func (o *LookerGitCloneCredentialsPatch) SetTokenNil() {
	o.Token.Set(nil)
}

// UnsetToken ensures that no value is present for Token, not even an explicit nil
func (o *LookerGitCloneCredentialsPatch) UnsetToken() {
	o.Token.Unset()
}

// GetSshKey returns the SshKey field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *LookerGitCloneCredentialsPatch) GetSshKey() string {
	if o == nil || IsNil(o.SshKey.Get()) {
		var ret string
		return ret
	}
	return *o.SshKey.Get()
}

// GetSshKeyOk returns a tuple with the SshKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *LookerGitCloneCredentialsPatch) GetSshKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SshKey.Get(), o.SshKey.IsSet()
}

// HasSshKey returns a boolean if a field has been set.
func (o *LookerGitCloneCredentialsPatch) HasSshKey() bool {
	if o != nil && o.SshKey.IsSet() {
		return true
	}

	return false
}

// SetSshKey gets a reference to the given NullableString and assigns it to the SshKey field.
func (o *LookerGitCloneCredentialsPatch) SetSshKey(v string) {
	o.SshKey.Set(&v)
}

// SetSshKeyNil sets the value for SshKey to be an explicit nil
func (o *LookerGitCloneCredentialsPatch) SetSshKeyNil() {
	o.SshKey.Set(nil)
}

// UnsetSshKey ensures that no value is present for SshKey, not even an explicit nil
func (o *LookerGitCloneCredentialsPatch) UnsetSshKey() {
	o.SshKey.Unset()
}

// GetRepoUrl returns the RepoUrl field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *LookerGitCloneCredentialsPatch) GetRepoUrl() string {
	if o == nil || IsNil(o.RepoUrl.Get()) {
		var ret string
		return ret
	}
	return *o.RepoUrl.Get()
}

// GetRepoUrlOk returns a tuple with the RepoUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *LookerGitCloneCredentialsPatch) GetRepoUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.RepoUrl.Get(), o.RepoUrl.IsSet()
}

// HasRepoUrl returns a boolean if a field has been set.
func (o *LookerGitCloneCredentialsPatch) HasRepoUrl() bool {
	if o != nil && o.RepoUrl.IsSet() {
		return true
	}

	return false
}

// SetRepoUrl gets a reference to the given NullableString and assigns it to the RepoUrl field.
func (o *LookerGitCloneCredentialsPatch) SetRepoUrl(v string) {
	o.RepoUrl.Set(&v)
}

// SetRepoUrlNil sets the value for RepoUrl to be an explicit nil
func (o *LookerGitCloneCredentialsPatch) SetRepoUrlNil() {
	o.RepoUrl.Set(nil)
}

// UnsetRepoUrl ensures that no value is present for RepoUrl, not even an explicit nil
func (o *LookerGitCloneCredentialsPatch) UnsetRepoUrl() {
	o.RepoUrl.Unset()
}

func (o LookerGitCloneCredentialsPatch) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LookerGitCloneCredentialsPatch) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Username.IsSet() {
		toSerialize["username"] = o.Username.Get()
	}
	if o.SslCaData.IsSet() {
		toSerialize["ssl_ca_data"] = o.SslCaData.Get()
	}
	if o.SslSkipCertVerification.IsSet() {
		toSerialize["ssl_skip_cert_verification"] = o.SslSkipCertVerification.Get()
	}
	if o.Token.IsSet() {
		toSerialize["token"] = o.Token.Get()
	}
	if o.SshKey.IsSet() {
		toSerialize["ssh_key"] = o.SshKey.Get()
	}
	if o.RepoUrl.IsSet() {
		toSerialize["repo_url"] = o.RepoUrl.Get()
	}
	return toSerialize, nil
}

type NullableLookerGitCloneCredentialsPatch struct {
	value *LookerGitCloneCredentialsPatch
	isSet bool
}

func (v NullableLookerGitCloneCredentialsPatch) Get() *LookerGitCloneCredentialsPatch {
	return v.value
}

func (v *NullableLookerGitCloneCredentialsPatch) Set(val *LookerGitCloneCredentialsPatch) {
	v.value = val
	v.isSet = true
}

func (v NullableLookerGitCloneCredentialsPatch) IsSet() bool {
	return v.isSet
}

func (v *NullableLookerGitCloneCredentialsPatch) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLookerGitCloneCredentialsPatch(val *LookerGitCloneCredentialsPatch) *NullableLookerGitCloneCredentialsPatch {
	return &NullableLookerGitCloneCredentialsPatch{value: val, isSet: true}
}

func (v NullableLookerGitCloneCredentialsPatch) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLookerGitCloneCredentialsPatch) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
