/*
Monte Carlo AI API

Programmatic access to the Monte Carlo AI platform.  Every response with a status of 400 or higher is `application/problem+json`, and carries a `code` naming the failure. That includes failures no single operation declares, such as calling a path with a method it does not support, which returns 405.  Every response carries an `X-Request-Id` header, and an error body repeats it as `request_id`. Quote it when reporting a problem. To choose the value yourself, send an `x-correlation-id` header; a value we cannot accept is replaced by a generated one.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package montecarlo

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"
)

// checks if the GenericCollectionAgentTokenCreatedOut type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GenericCollectionAgentTokenCreatedOut{}

// GenericCollectionAgentTokenCreatedOut A token as it comes back from its create, the only time the secret is available.
type GenericCollectionAgentTokenCreatedOut struct {
	// Unique identifier of the credential. For a token this is also its key id; for an OAuth client, its client id.
	Id string `json:"id"`
	// Identifier of the deployment whose agent presents this credential.
	DeploymentId string `json:"deployment_id"`
	// Which kind of credential this is.
	Type CredentialType `json:"type"`
	// What this credential is for.
	Description string `json:"description"`
	// When the credential was created.
	CreatedTime time.Time `json:"created_time"`
	// Key id the agent presents, as `mcd_id` in its configuration. The same value as `id`.
	McdId string `json:"mcd_id"`
	// Secret the agent presents, as `mcd_token` in its configuration. Returned once, by this call. It is not retrievable afterwards, and Terraform holds it in state like any generated credential. To rotate, create a new credential and delete this one.
	McdToken string `json:"mcd_token"`
}

type _GenericCollectionAgentTokenCreatedOut GenericCollectionAgentTokenCreatedOut

// NewGenericCollectionAgentTokenCreatedOut instantiates a new GenericCollectionAgentTokenCreatedOut object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGenericCollectionAgentTokenCreatedOut(id string, deploymentId string, type_ CredentialType, description string, createdTime time.Time, mcdId string, mcdToken string) *GenericCollectionAgentTokenCreatedOut {
	this := GenericCollectionAgentTokenCreatedOut{}
	this.Id = id
	this.DeploymentId = deploymentId
	this.Type = type_
	this.Description = description
	this.CreatedTime = createdTime
	this.McdId = mcdId
	this.McdToken = mcdToken
	return &this
}

// NewGenericCollectionAgentTokenCreatedOutWithDefaults instantiates a new GenericCollectionAgentTokenCreatedOut object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGenericCollectionAgentTokenCreatedOutWithDefaults() *GenericCollectionAgentTokenCreatedOut {
	this := GenericCollectionAgentTokenCreatedOut{}
	return &this
}

// GetId returns the Id field value
func (o *GenericCollectionAgentTokenCreatedOut) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *GenericCollectionAgentTokenCreatedOut) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *GenericCollectionAgentTokenCreatedOut) SetId(v string) {
	o.Id = v
}

// GetDeploymentId returns the DeploymentId field value
func (o *GenericCollectionAgentTokenCreatedOut) GetDeploymentId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DeploymentId
}

// GetDeploymentIdOk returns a tuple with the DeploymentId field value
// and a boolean to check if the value has been set.
func (o *GenericCollectionAgentTokenCreatedOut) GetDeploymentIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DeploymentId, true
}

// SetDeploymentId sets field value
func (o *GenericCollectionAgentTokenCreatedOut) SetDeploymentId(v string) {
	o.DeploymentId = v
}

// GetType returns the Type field value
func (o *GenericCollectionAgentTokenCreatedOut) GetType() CredentialType {
	if o == nil {
		var ret CredentialType
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *GenericCollectionAgentTokenCreatedOut) GetTypeOk() (*CredentialType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *GenericCollectionAgentTokenCreatedOut) SetType(v CredentialType) {
	o.Type = v
}

// GetDescription returns the Description field value
func (o *GenericCollectionAgentTokenCreatedOut) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *GenericCollectionAgentTokenCreatedOut) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *GenericCollectionAgentTokenCreatedOut) SetDescription(v string) {
	o.Description = v
}

// GetCreatedTime returns the CreatedTime field value
func (o *GenericCollectionAgentTokenCreatedOut) GetCreatedTime() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedTime
}

// GetCreatedTimeOk returns a tuple with the CreatedTime field value
// and a boolean to check if the value has been set.
func (o *GenericCollectionAgentTokenCreatedOut) GetCreatedTimeOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedTime, true
}

// SetCreatedTime sets field value
func (o *GenericCollectionAgentTokenCreatedOut) SetCreatedTime(v time.Time) {
	o.CreatedTime = v
}

// GetMcdId returns the McdId field value
func (o *GenericCollectionAgentTokenCreatedOut) GetMcdId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.McdId
}

// GetMcdIdOk returns a tuple with the McdId field value
// and a boolean to check if the value has been set.
func (o *GenericCollectionAgentTokenCreatedOut) GetMcdIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.McdId, true
}

// SetMcdId sets field value
func (o *GenericCollectionAgentTokenCreatedOut) SetMcdId(v string) {
	o.McdId = v
}

// GetMcdToken returns the McdToken field value
func (o *GenericCollectionAgentTokenCreatedOut) GetMcdToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.McdToken
}

// GetMcdTokenOk returns a tuple with the McdToken field value
// and a boolean to check if the value has been set.
func (o *GenericCollectionAgentTokenCreatedOut) GetMcdTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.McdToken, true
}

// SetMcdToken sets field value
func (o *GenericCollectionAgentTokenCreatedOut) SetMcdToken(v string) {
	o.McdToken = v
}

func (o GenericCollectionAgentTokenCreatedOut) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GenericCollectionAgentTokenCreatedOut) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["deployment_id"] = o.DeploymentId
	toSerialize["type"] = o.Type
	toSerialize["description"] = o.Description
	toSerialize["created_time"] = o.CreatedTime
	toSerialize["mcd_id"] = o.McdId
	toSerialize["mcd_token"] = o.McdToken
	return toSerialize, nil
}

func (o *GenericCollectionAgentTokenCreatedOut) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"deployment_id",
		"type",
		"description",
		"created_time",
		"mcd_id",
		"mcd_token",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGenericCollectionAgentTokenCreatedOut := _GenericCollectionAgentTokenCreatedOut{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGenericCollectionAgentTokenCreatedOut)

	if err != nil {
		return err
	}

	*o = GenericCollectionAgentTokenCreatedOut(varGenericCollectionAgentTokenCreatedOut)

	return err
}

type NullableGenericCollectionAgentTokenCreatedOut struct {
	value *GenericCollectionAgentTokenCreatedOut
	isSet bool
}

func (v NullableGenericCollectionAgentTokenCreatedOut) Get() *GenericCollectionAgentTokenCreatedOut {
	return v.value
}

func (v *NullableGenericCollectionAgentTokenCreatedOut) Set(val *GenericCollectionAgentTokenCreatedOut) {
	v.value = val
	v.isSet = true
}

func (v NullableGenericCollectionAgentTokenCreatedOut) IsSet() bool {
	return v.isSet
}

func (v *NullableGenericCollectionAgentTokenCreatedOut) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGenericCollectionAgentTokenCreatedOut(val *GenericCollectionAgentTokenCreatedOut) *NullableGenericCollectionAgentTokenCreatedOut {
	return &NullableGenericCollectionAgentTokenCreatedOut{value: val, isSet: true}
}

func (v NullableGenericCollectionAgentTokenCreatedOut) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGenericCollectionAgentTokenCreatedOut) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
