/*
Monte Carlo AI API

Programmatic access to the Monte Carlo AI platform.  Every response with a status of 400 or higher is `application/problem+json`, and carries a `code` naming the failure. That includes failures no single operation declares, such as calling a path with a method it does not support, which returns 405.  Every response carries an `X-Request-Id` header, and an error body repeats it as `request_id`. Quote it when reporting a problem. To choose the value yourself, send an `x-correlation-id` header; a value we cannot accept is replaced by a generated one.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package montecarlo

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"
)

// checks if the FileCredentialsOut type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FileCredentialsOut{}

// FileCredentialsOut Which file on the deployment holds a connection's credentials.
type FileCredentialsOut struct {
	// Unique identifier of the credentials.
	Id string `json:"id"`
	// The connection type the credentials are for, such as `snowflake`. Fixed once created.
	ConnectionType string `json:"connection_type"`
	// Where the secret lives. Fixed once created.
	StorageType CredentialsStorageType `json:"storage_type"`
	// When the credentials were created.
	CreatedTime time.Time `json:"created_time"`
	// BigQuery project the connection reads from. Null unless set.
	BqProjectId NullableString `json:"bq_project_id"`
	// Databricks SQL warehouse the connection runs queries on. Null unless set.
	SqlWarehouseId NullableString `json:"sql_warehouse_id"`
	// Path of the file on the deployment that holds the connection's credentials.
	FilePath string `json:"file_path"`
}

type _FileCredentialsOut FileCredentialsOut

// NewFileCredentialsOut instantiates a new FileCredentialsOut object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFileCredentialsOut(id string, connectionType string, storageType CredentialsStorageType, createdTime time.Time, bqProjectId NullableString, sqlWarehouseId NullableString, filePath string) *FileCredentialsOut {
	this := FileCredentialsOut{}
	this.Id = id
	this.ConnectionType = connectionType
	this.StorageType = storageType
	this.CreatedTime = createdTime
	this.BqProjectId = bqProjectId
	this.SqlWarehouseId = sqlWarehouseId
	this.FilePath = filePath
	return &this
}

// NewFileCredentialsOutWithDefaults instantiates a new FileCredentialsOut object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFileCredentialsOutWithDefaults() *FileCredentialsOut {
	this := FileCredentialsOut{}
	return &this
}

// GetId returns the Id field value
func (o *FileCredentialsOut) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *FileCredentialsOut) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *FileCredentialsOut) SetId(v string) {
	o.Id = v
}

// GetConnectionType returns the ConnectionType field value
func (o *FileCredentialsOut) GetConnectionType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ConnectionType
}

// GetConnectionTypeOk returns a tuple with the ConnectionType field value
// and a boolean to check if the value has been set.
func (o *FileCredentialsOut) GetConnectionTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ConnectionType, true
}

// SetConnectionType sets field value
func (o *FileCredentialsOut) SetConnectionType(v string) {
	o.ConnectionType = v
}

// GetStorageType returns the StorageType field value
func (o *FileCredentialsOut) GetStorageType() CredentialsStorageType {
	if o == nil {
		var ret CredentialsStorageType
		return ret
	}

	return o.StorageType
}

// GetStorageTypeOk returns a tuple with the StorageType field value
// and a boolean to check if the value has been set.
func (o *FileCredentialsOut) GetStorageTypeOk() (*CredentialsStorageType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StorageType, true
}

// SetStorageType sets field value
func (o *FileCredentialsOut) SetStorageType(v CredentialsStorageType) {
	o.StorageType = v
}

// GetCreatedTime returns the CreatedTime field value
func (o *FileCredentialsOut) GetCreatedTime() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedTime
}

// GetCreatedTimeOk returns a tuple with the CreatedTime field value
// and a boolean to check if the value has been set.
func (o *FileCredentialsOut) GetCreatedTimeOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedTime, true
}

// SetCreatedTime sets field value
func (o *FileCredentialsOut) SetCreatedTime(v time.Time) {
	o.CreatedTime = v
}

// GetBqProjectId returns the BqProjectId field value
// If the value is explicit nil, the zero value for string will be returned
func (o *FileCredentialsOut) GetBqProjectId() string {
	if o == nil || o.BqProjectId.Get() == nil {
		var ret string
		return ret
	}

	return *o.BqProjectId.Get()
}

// GetBqProjectIdOk returns a tuple with the BqProjectId field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *FileCredentialsOut) GetBqProjectIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.BqProjectId.Get(), o.BqProjectId.IsSet()
}

// SetBqProjectId sets field value
func (o *FileCredentialsOut) SetBqProjectId(v string) {
	o.BqProjectId.Set(&v)
}

// GetSqlWarehouseId returns the SqlWarehouseId field value
// If the value is explicit nil, the zero value for string will be returned
func (o *FileCredentialsOut) GetSqlWarehouseId() string {
	if o == nil || o.SqlWarehouseId.Get() == nil {
		var ret string
		return ret
	}

	return *o.SqlWarehouseId.Get()
}

// GetSqlWarehouseIdOk returns a tuple with the SqlWarehouseId field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *FileCredentialsOut) GetSqlWarehouseIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SqlWarehouseId.Get(), o.SqlWarehouseId.IsSet()
}

// SetSqlWarehouseId sets field value
func (o *FileCredentialsOut) SetSqlWarehouseId(v string) {
	o.SqlWarehouseId.Set(&v)
}

// GetFilePath returns the FilePath field value
func (o *FileCredentialsOut) GetFilePath() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FilePath
}

// GetFilePathOk returns a tuple with the FilePath field value
// and a boolean to check if the value has been set.
func (o *FileCredentialsOut) GetFilePathOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FilePath, true
}

// SetFilePath sets field value
func (o *FileCredentialsOut) SetFilePath(v string) {
	o.FilePath = v
}

func (o FileCredentialsOut) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FileCredentialsOut) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["connection_type"] = o.ConnectionType
	toSerialize["storage_type"] = o.StorageType
	toSerialize["created_time"] = o.CreatedTime
	toSerialize["bq_project_id"] = o.BqProjectId.Get()
	toSerialize["sql_warehouse_id"] = o.SqlWarehouseId.Get()
	toSerialize["file_path"] = o.FilePath
	return toSerialize, nil
}

func (o *FileCredentialsOut) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"connection_type",
		"storage_type",
		"created_time",
		"bq_project_id",
		"sql_warehouse_id",
		"file_path",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varFileCredentialsOut := _FileCredentialsOut{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varFileCredentialsOut)

	if err != nil {
		return err
	}

	*o = FileCredentialsOut(varFileCredentialsOut)

	return err
}

type NullableFileCredentialsOut struct {
	value *FileCredentialsOut
	isSet bool
}

func (v NullableFileCredentialsOut) Get() *FileCredentialsOut {
	return v.value
}

func (v *NullableFileCredentialsOut) Set(val *FileCredentialsOut) {
	v.value = val
	v.isSet = true
}

func (v NullableFileCredentialsOut) IsSet() bool {
	return v.isSet
}

func (v *NullableFileCredentialsOut) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFileCredentialsOut(val *FileCredentialsOut) *NullableFileCredentialsOut {
	return &NullableFileCredentialsOut{value: val, isSet: true}
}

func (v NullableFileCredentialsOut) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFileCredentialsOut) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
