/*
Monte Carlo AI API

Programmatic access to the Monte Carlo AI platform.  Every response with a status of 400 or higher is `application/problem+json`, and carries a `code` naming the failure. That includes failures no single operation declares, such as calling a path with a method it does not support, which returns 405.  Every response carries an `X-Request-Id` header, and an error body repeats it as `request_id`. Quote it when reporting a problem. To choose the value yourself, send an `x-correlation-id` header; a value we cannot accept is replaced by a generated one.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package montecarlo

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"
)

// checks if the StarburstEnterpriseCredentialsOut type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StarburstEnterpriseCredentialsOut{}

// StarburstEnterpriseCredentialsOut Starburst Enterprise credentials Monte Carlo stores. The password is never returned.
type StarburstEnterpriseCredentialsOut struct {
	// Unique identifier of the credentials.
	Id string `json:"id"`
	// The connection type the credentials are for, such as `snowflake`. Fixed once created.
	ConnectionType string `json:"connection_type"`
	// Where the secret lives. Fixed once created.
	StorageType CredentialsStorageType `json:"storage_type"`
	// When the credentials were created.
	CreatedTime time.Time `json:"created_time"`
	// Hostname of the database endpoint.
	Host string `json:"host"`
	// Port the database listens on.
	Port int32 `json:"port"`
	// Database to connect to. Null when none is set.
	DbName NullableString `json:"db_name"`
	// Database user Monte Carlo logs in as.
	User string `json:"user"`
	// PEM text of the CA certificate the server's certificate is checked against. Null when none is set.
	SslCaData NullableString `json:"ssl_ca_data"`
	// Skip the check of the server's certificate. The connection always uses TLS. Null when unset.
	SslDisabled NullableBool `json:"ssl_disabled"`
}

type _StarburstEnterpriseCredentialsOut StarburstEnterpriseCredentialsOut

// NewStarburstEnterpriseCredentialsOut instantiates a new StarburstEnterpriseCredentialsOut object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStarburstEnterpriseCredentialsOut(id string, connectionType string, storageType CredentialsStorageType, createdTime time.Time, host string, port int32, dbName NullableString, user string, sslCaData NullableString, sslDisabled NullableBool) *StarburstEnterpriseCredentialsOut {
	this := StarburstEnterpriseCredentialsOut{}
	this.Id = id
	this.ConnectionType = connectionType
	this.StorageType = storageType
	this.CreatedTime = createdTime
	this.Host = host
	this.Port = port
	this.DbName = dbName
	this.User = user
	this.SslCaData = sslCaData
	this.SslDisabled = sslDisabled
	return &this
}

// NewStarburstEnterpriseCredentialsOutWithDefaults instantiates a new StarburstEnterpriseCredentialsOut object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStarburstEnterpriseCredentialsOutWithDefaults() *StarburstEnterpriseCredentialsOut {
	this := StarburstEnterpriseCredentialsOut{}
	return &this
}

// GetId returns the Id field value
func (o *StarburstEnterpriseCredentialsOut) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *StarburstEnterpriseCredentialsOut) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *StarburstEnterpriseCredentialsOut) SetId(v string) {
	o.Id = v
}

// GetConnectionType returns the ConnectionType field value
func (o *StarburstEnterpriseCredentialsOut) GetConnectionType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ConnectionType
}

// GetConnectionTypeOk returns a tuple with the ConnectionType field value
// and a boolean to check if the value has been set.
func (o *StarburstEnterpriseCredentialsOut) GetConnectionTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ConnectionType, true
}

// SetConnectionType sets field value
func (o *StarburstEnterpriseCredentialsOut) SetConnectionType(v string) {
	o.ConnectionType = v
}

// GetStorageType returns the StorageType field value
func (o *StarburstEnterpriseCredentialsOut) GetStorageType() CredentialsStorageType {
	if o == nil {
		var ret CredentialsStorageType
		return ret
	}

	return o.StorageType
}

// GetStorageTypeOk returns a tuple with the StorageType field value
// and a boolean to check if the value has been set.
func (o *StarburstEnterpriseCredentialsOut) GetStorageTypeOk() (*CredentialsStorageType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StorageType, true
}

// SetStorageType sets field value
func (o *StarburstEnterpriseCredentialsOut) SetStorageType(v CredentialsStorageType) {
	o.StorageType = v
}

// GetCreatedTime returns the CreatedTime field value
func (o *StarburstEnterpriseCredentialsOut) GetCreatedTime() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedTime
}

// GetCreatedTimeOk returns a tuple with the CreatedTime field value
// and a boolean to check if the value has been set.
func (o *StarburstEnterpriseCredentialsOut) GetCreatedTimeOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedTime, true
}

// SetCreatedTime sets field value
func (o *StarburstEnterpriseCredentialsOut) SetCreatedTime(v time.Time) {
	o.CreatedTime = v
}

// GetHost returns the Host field value
func (o *StarburstEnterpriseCredentialsOut) GetHost() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Host
}

// GetHostOk returns a tuple with the Host field value
// and a boolean to check if the value has been set.
func (o *StarburstEnterpriseCredentialsOut) GetHostOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Host, true
}

// SetHost sets field value
func (o *StarburstEnterpriseCredentialsOut) SetHost(v string) {
	o.Host = v
}

// GetPort returns the Port field value
func (o *StarburstEnterpriseCredentialsOut) GetPort() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Port
}

// GetPortOk returns a tuple with the Port field value
// and a boolean to check if the value has been set.
func (o *StarburstEnterpriseCredentialsOut) GetPortOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Port, true
}

// SetPort sets field value
func (o *StarburstEnterpriseCredentialsOut) SetPort(v int32) {
	o.Port = v
}

// GetDbName returns the DbName field value
// If the value is explicit nil, the zero value for string will be returned
func (o *StarburstEnterpriseCredentialsOut) GetDbName() string {
	if o == nil || o.DbName.Get() == nil {
		var ret string
		return ret
	}

	return *o.DbName.Get()
}

// GetDbNameOk returns a tuple with the DbName field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *StarburstEnterpriseCredentialsOut) GetDbNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DbName.Get(), o.DbName.IsSet()
}

// SetDbName sets field value
func (o *StarburstEnterpriseCredentialsOut) SetDbName(v string) {
	o.DbName.Set(&v)
}

// GetUser returns the User field value
func (o *StarburstEnterpriseCredentialsOut) GetUser() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.User
}

// GetUserOk returns a tuple with the User field value
// and a boolean to check if the value has been set.
func (o *StarburstEnterpriseCredentialsOut) GetUserOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.User, true
}

// SetUser sets field value
func (o *StarburstEnterpriseCredentialsOut) SetUser(v string) {
	o.User = v
}

// GetSslCaData returns the SslCaData field value
// If the value is explicit nil, the zero value for string will be returned
func (o *StarburstEnterpriseCredentialsOut) GetSslCaData() string {
	if o == nil || o.SslCaData.Get() == nil {
		var ret string
		return ret
	}

	return *o.SslCaData.Get()
}

// GetSslCaDataOk returns a tuple with the SslCaData field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *StarburstEnterpriseCredentialsOut) GetSslCaDataOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SslCaData.Get(), o.SslCaData.IsSet()
}

// SetSslCaData sets field value
func (o *StarburstEnterpriseCredentialsOut) SetSslCaData(v string) {
	o.SslCaData.Set(&v)
}

// GetSslDisabled returns the SslDisabled field value
// If the value is explicit nil, the zero value for bool will be returned
func (o *StarburstEnterpriseCredentialsOut) GetSslDisabled() bool {
	if o == nil || o.SslDisabled.Get() == nil {
		var ret bool
		return ret
	}

	return *o.SslDisabled.Get()
}

// GetSslDisabledOk returns a tuple with the SslDisabled field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *StarburstEnterpriseCredentialsOut) GetSslDisabledOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.SslDisabled.Get(), o.SslDisabled.IsSet()
}

// SetSslDisabled sets field value
func (o *StarburstEnterpriseCredentialsOut) SetSslDisabled(v bool) {
	o.SslDisabled.Set(&v)
}

func (o StarburstEnterpriseCredentialsOut) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StarburstEnterpriseCredentialsOut) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["connection_type"] = o.ConnectionType
	toSerialize["storage_type"] = o.StorageType
	toSerialize["created_time"] = o.CreatedTime
	toSerialize["host"] = o.Host
	toSerialize["port"] = o.Port
	toSerialize["db_name"] = o.DbName.Get()
	toSerialize["user"] = o.User
	toSerialize["ssl_ca_data"] = o.SslCaData.Get()
	toSerialize["ssl_disabled"] = o.SslDisabled.Get()
	return toSerialize, nil
}

func (o *StarburstEnterpriseCredentialsOut) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"connection_type",
		"storage_type",
		"created_time",
		"host",
		"port",
		"db_name",
		"user",
		"ssl_ca_data",
		"ssl_disabled",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varStarburstEnterpriseCredentialsOut := _StarburstEnterpriseCredentialsOut{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varStarburstEnterpriseCredentialsOut)

	if err != nil {
		return err
	}

	*o = StarburstEnterpriseCredentialsOut(varStarburstEnterpriseCredentialsOut)

	return err
}

type NullableStarburstEnterpriseCredentialsOut struct {
	value *StarburstEnterpriseCredentialsOut
	isSet bool
}

func (v NullableStarburstEnterpriseCredentialsOut) Get() *StarburstEnterpriseCredentialsOut {
	return v.value
}

func (v *NullableStarburstEnterpriseCredentialsOut) Set(val *StarburstEnterpriseCredentialsOut) {
	v.value = val
	v.isSet = true
}

func (v NullableStarburstEnterpriseCredentialsOut) IsSet() bool {
	return v.isSet
}

func (v *NullableStarburstEnterpriseCredentialsOut) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStarburstEnterpriseCredentialsOut(val *StarburstEnterpriseCredentialsOut) *NullableStarburstEnterpriseCredentialsOut {
	return &NullableStarburstEnterpriseCredentialsOut{value: val, isSet: true}
}

func (v NullableStarburstEnterpriseCredentialsOut) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStarburstEnterpriseCredentialsOut) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
