/*
Monte Carlo AI API

Programmatic access to the Monte Carlo AI platform.  Every response with a status of 400 or higher is `application/problem+json`, and carries a `code` naming the failure. That includes failures no single operation declares, such as calling a path with a method it does not support, which returns 405.  Every response carries an `X-Request-Id` header, and an error body repeats it as `request_id`. Quote it when reporting a problem. To choose the value yourself, send an `x-correlation-id` header; a value we cannot accept is replaced by a generated one.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package montecarlo

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the FieldErrorOut type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FieldErrorOut{}

// FieldErrorOut One field of a request that failed validation.
type FieldErrorOut struct {
	// Machine-readable code identifying the kind of validation failure.
	Code string `json:"code"`
	// Values that parameterize `message`, for a client that renders its own text instead of showing `message` directly. Absent when there is nothing to report.
	Extra map[string]string `json:"extra,omitempty"`
	// Where the invalid field sits, as the path to it from the top of the request body. For example `['port']`, or `['settings', 'timeout']` for a field nested inside an object.
	Field []string `json:"field"`
	// Human-readable explanation of why this field failed validation.
	Message string `json:"message"`
}

type _FieldErrorOut FieldErrorOut

// NewFieldErrorOut instantiates a new FieldErrorOut object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFieldErrorOut(code string, field []string, message string) *FieldErrorOut {
	this := FieldErrorOut{}
	this.Code = code
	this.Field = field
	this.Message = message
	return &this
}

// NewFieldErrorOutWithDefaults instantiates a new FieldErrorOut object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFieldErrorOutWithDefaults() *FieldErrorOut {
	this := FieldErrorOut{}
	return &this
}

// GetCode returns the Code field value
func (o *FieldErrorOut) GetCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Code
}

// GetCodeOk returns a tuple with the Code field value
// and a boolean to check if the value has been set.
func (o *FieldErrorOut) GetCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Code, true
}

// SetCode sets field value
func (o *FieldErrorOut) SetCode(v string) {
	o.Code = v
}

// GetExtra returns the Extra field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *FieldErrorOut) GetExtra() map[string]string {
	if o == nil {
		var ret map[string]string
		return ret
	}
	return o.Extra
}

// GetExtraOk returns a tuple with the Extra field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *FieldErrorOut) GetExtraOk() (map[string]string, bool) {
	if o == nil || IsNil(o.Extra) {
		return map[string]string{}, false
	}
	return o.Extra, true
}

// HasExtra returns a boolean if a field has been set.
func (o *FieldErrorOut) HasExtra() bool {
	if o != nil && !IsNil(o.Extra) {
		return true
	}

	return false
}

// SetExtra gets a reference to the given map[string]string and assigns it to the Extra field.
func (o *FieldErrorOut) SetExtra(v map[string]string) {
	o.Extra = v
}

// GetField returns the Field field value
func (o *FieldErrorOut) GetField() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Field
}

// GetFieldOk returns a tuple with the Field field value
// and a boolean to check if the value has been set.
func (o *FieldErrorOut) GetFieldOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Field, true
}

// SetField sets field value
func (o *FieldErrorOut) SetField(v []string) {
	o.Field = v
}

// GetMessage returns the Message field value
func (o *FieldErrorOut) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *FieldErrorOut) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *FieldErrorOut) SetMessage(v string) {
	o.Message = v
}

func (o FieldErrorOut) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FieldErrorOut) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["code"] = o.Code
	if o.Extra != nil {
		toSerialize["extra"] = o.Extra
	}
	toSerialize["field"] = o.Field
	toSerialize["message"] = o.Message
	return toSerialize, nil
}

func (o *FieldErrorOut) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"code",
		"field",
		"message",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varFieldErrorOut := _FieldErrorOut{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varFieldErrorOut)

	if err != nil {
		return err
	}

	*o = FieldErrorOut(varFieldErrorOut)

	return err
}

type NullableFieldErrorOut struct {
	value *FieldErrorOut
	isSet bool
}

func (v NullableFieldErrorOut) Get() *FieldErrorOut {
	return v.value
}

func (v *NullableFieldErrorOut) Set(val *FieldErrorOut) {
	v.value = val
	v.isSet = true
}

func (v NullableFieldErrorOut) IsSet() bool {
	return v.isSet
}

func (v *NullableFieldErrorOut) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFieldErrorOut(val *FieldErrorOut) *NullableFieldErrorOut {
	return &NullableFieldErrorOut{value: val, isSet: true}
}

func (v NullableFieldErrorOut) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFieldErrorOut) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
