/*
Monte Carlo AI API

Programmatic access to the Monte Carlo AI platform.  Every response with a status of 400 or higher is `application/problem+json`, and carries a `code` naming the failure. That includes failures no single operation declares, such as calling a path with a method it does not support, which returns 405.  Every response carries an `X-Request-Id` header, and an error body repeats it as `request_id`. Quote it when reporting a problem. To choose the value yourself, send an `x-correlation-id` header; a value we cannot accept is replaced by a generated one.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package montecarlo

import (
	"encoding/json"
	"fmt"
)

// GcpAgentAuthenticationType How Monte Carlo authenticates to a collection agent running on GCP.
type GcpAgentAuthenticationType string

// List of GcpAgentAuthenticationType
const (
	GCPAGENTAUTHENTICATIONTYPE_GCP_JSON_SERVICE_ACCOUNT_KEY GcpAgentAuthenticationType = "GCP_JSON_SERVICE_ACCOUNT_KEY"
	GCPAGENTAUTHENTICATIONTYPE_CUSTOM_AUTH_HEADERS          GcpAgentAuthenticationType = "CUSTOM_AUTH_HEADERS"
)

// All allowed values of GcpAgentAuthenticationType enum
var AllowedGcpAgentAuthenticationTypeEnumValues = []GcpAgentAuthenticationType{
	"GCP_JSON_SERVICE_ACCOUNT_KEY",
	"CUSTOM_AUTH_HEADERS",
}

func (v *GcpAgentAuthenticationType) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := GcpAgentAuthenticationType(value)
	for _, existing := range AllowedGcpAgentAuthenticationTypeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	*v = enumTypeValue
	return nil
}

// NewGcpAgentAuthenticationTypeFromValue returns a pointer to a valid GcpAgentAuthenticationType
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewGcpAgentAuthenticationTypeFromValue(v string) (*GcpAgentAuthenticationType, error) {
	ev := GcpAgentAuthenticationType(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for GcpAgentAuthenticationType: valid values are %v", v, AllowedGcpAgentAuthenticationTypeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v GcpAgentAuthenticationType) IsValid() bool {
	for _, existing := range AllowedGcpAgentAuthenticationTypeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to GcpAgentAuthenticationType value
func (v GcpAgentAuthenticationType) Ptr() *GcpAgentAuthenticationType {
	return &v
}

type NullableGcpAgentAuthenticationType struct {
	value *GcpAgentAuthenticationType
	isSet bool
}

func (v NullableGcpAgentAuthenticationType) Get() *GcpAgentAuthenticationType {
	return v.value
}

func (v *NullableGcpAgentAuthenticationType) Set(val *GcpAgentAuthenticationType) {
	v.value = val
	v.isSet = true
}

func (v NullableGcpAgentAuthenticationType) IsSet() bool {
	return v.isSet
}

func (v *NullableGcpAgentAuthenticationType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGcpAgentAuthenticationType(val *GcpAgentAuthenticationType) *NullableGcpAgentAuthenticationType {
	return &NullableGcpAgentAuthenticationType{value: val, isSet: true}
}

func (v NullableGcpAgentAuthenticationType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGcpAgentAuthenticationType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
