/*
Monte Carlo AI API

Programmatic access to the Monte Carlo AI platform.  Every response with a status of 400 or higher is `application/problem+json`, and carries a `code` naming the failure. That includes failures no single operation declares, such as calling a path with a method it does not support, which returns 405.  Every response carries an `X-Request-Id` header, and an error body repeats it as `request_id`. Quote it when reporting a problem. To choose the value yourself, send an `x-correlation-id` header; a value we cannot accept is replaced by a generated one.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package montecarlo

import (
	"encoding/json"
)

// checks if the ClickHouseCredentialsPatch type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ClickHouseCredentialsPatch{}

// ClickHouseCredentialsPatch A change to existing ClickHouse credentials.  A field left out is unchanged. `password` set to null is unchanged. `db_name` set to null is cleared. `host`, `port` and `user` cannot be cleared. Sending an empty body returns the credentials as they are.
type ClickHouseCredentialsPatch struct {
	// Hostname of the database endpoint.
	Host NullableString `json:"host,omitempty"`
	// Port the database listens on.
	Port NullableInt32 `json:"port,omitempty"`
	// Database to connect to.
	DbName NullableString `json:"db_name,omitempty"`
	// Database user Monte Carlo logs in as.
	User NullableString `json:"user,omitempty"`
	// New password of the database user.
	Password NullableString `json:"password,omitempty"`
}

// NewClickHouseCredentialsPatch instantiates a new ClickHouseCredentialsPatch object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewClickHouseCredentialsPatch() *ClickHouseCredentialsPatch {
	this := ClickHouseCredentialsPatch{}
	return &this
}

// NewClickHouseCredentialsPatchWithDefaults instantiates a new ClickHouseCredentialsPatch object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewClickHouseCredentialsPatchWithDefaults() *ClickHouseCredentialsPatch {
	this := ClickHouseCredentialsPatch{}
	return &this
}

// GetHost returns the Host field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ClickHouseCredentialsPatch) GetHost() string {
	if o == nil || IsNil(o.Host.Get()) {
		var ret string
		return ret
	}
	return *o.Host.Get()
}

// GetHostOk returns a tuple with the Host field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ClickHouseCredentialsPatch) GetHostOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Host.Get(), o.Host.IsSet()
}

// HasHost returns a boolean if a field has been set.
func (o *ClickHouseCredentialsPatch) HasHost() bool {
	if o != nil && o.Host.IsSet() {
		return true
	}

	return false
}

// SetHost gets a reference to the given NullableString and assigns it to the Host field.
func (o *ClickHouseCredentialsPatch) SetHost(v string) {
	o.Host.Set(&v)
}

// SetHostNil sets the value for Host to be an explicit nil
func (o *ClickHouseCredentialsPatch) SetHostNil() {
	o.Host.Set(nil)
}

// UnsetHost ensures that no value is present for Host, not even an explicit nil
func (o *ClickHouseCredentialsPatch) UnsetHost() {
	o.Host.Unset()
}

// GetPort returns the Port field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ClickHouseCredentialsPatch) GetPort() int32 {
	if o == nil || IsNil(o.Port.Get()) {
		var ret int32
		return ret
	}
	return *o.Port.Get()
}

// GetPortOk returns a tuple with the Port field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ClickHouseCredentialsPatch) GetPortOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Port.Get(), o.Port.IsSet()
}

// HasPort returns a boolean if a field has been set.
func (o *ClickHouseCredentialsPatch) HasPort() bool {
	if o != nil && o.Port.IsSet() {
		return true
	}

	return false
}

// SetPort gets a reference to the given NullableInt32 and assigns it to the Port field.
func (o *ClickHouseCredentialsPatch) SetPort(v int32) {
	o.Port.Set(&v)
}

// SetPortNil sets the value for Port to be an explicit nil
func (o *ClickHouseCredentialsPatch) SetPortNil() {
	o.Port.Set(nil)
}

// UnsetPort ensures that no value is present for Port, not even an explicit nil
func (o *ClickHouseCredentialsPatch) UnsetPort() {
	o.Port.Unset()
}

// GetDbName returns the DbName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ClickHouseCredentialsPatch) GetDbName() string {
	if o == nil || IsNil(o.DbName.Get()) {
		var ret string
		return ret
	}
	return *o.DbName.Get()
}

// GetDbNameOk returns a tuple with the DbName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ClickHouseCredentialsPatch) GetDbNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DbName.Get(), o.DbName.IsSet()
}

// HasDbName returns a boolean if a field has been set.
func (o *ClickHouseCredentialsPatch) HasDbName() bool {
	if o != nil && o.DbName.IsSet() {
		return true
	}

	return false
}

// SetDbName gets a reference to the given NullableString and assigns it to the DbName field.
func (o *ClickHouseCredentialsPatch) SetDbName(v string) {
	o.DbName.Set(&v)
}

// SetDbNameNil sets the value for DbName to be an explicit nil
func (o *ClickHouseCredentialsPatch) SetDbNameNil() {
	o.DbName.Set(nil)
}

// UnsetDbName ensures that no value is present for DbName, not even an explicit nil
func (o *ClickHouseCredentialsPatch) UnsetDbName() {
	o.DbName.Unset()
}

// GetUser returns the User field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ClickHouseCredentialsPatch) GetUser() string {
	if o == nil || IsNil(o.User.Get()) {
		var ret string
		return ret
	}
	return *o.User.Get()
}

// GetUserOk returns a tuple with the User field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ClickHouseCredentialsPatch) GetUserOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.User.Get(), o.User.IsSet()
}

// HasUser returns a boolean if a field has been set.
func (o *ClickHouseCredentialsPatch) HasUser() bool {
	if o != nil && o.User.IsSet() {
		return true
	}

	return false
}

// SetUser gets a reference to the given NullableString and assigns it to the User field.
func (o *ClickHouseCredentialsPatch) SetUser(v string) {
	o.User.Set(&v)
}

// SetUserNil sets the value for User to be an explicit nil
func (o *ClickHouseCredentialsPatch) SetUserNil() {
	o.User.Set(nil)
}

// UnsetUser ensures that no value is present for User, not even an explicit nil
func (o *ClickHouseCredentialsPatch) UnsetUser() {
	o.User.Unset()
}

// GetPassword returns the Password field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ClickHouseCredentialsPatch) GetPassword() string {
	if o == nil || IsNil(o.Password.Get()) {
		var ret string
		return ret
	}
	return *o.Password.Get()
}

// GetPasswordOk returns a tuple with the Password field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ClickHouseCredentialsPatch) GetPasswordOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Password.Get(), o.Password.IsSet()
}

// HasPassword returns a boolean if a field has been set.
func (o *ClickHouseCredentialsPatch) HasPassword() bool {
	if o != nil && o.Password.IsSet() {
		return true
	}

	return false
}

// SetPassword gets a reference to the given NullableString and assigns it to the Password field.
func (o *ClickHouseCredentialsPatch) SetPassword(v string) {
	o.Password.Set(&v)
}

// SetPasswordNil sets the value for Password to be an explicit nil
func (o *ClickHouseCredentialsPatch) SetPasswordNil() {
	o.Password.Set(nil)
}

// UnsetPassword ensures that no value is present for Password, not even an explicit nil
func (o *ClickHouseCredentialsPatch) UnsetPassword() {
	o.Password.Unset()
}

func (o ClickHouseCredentialsPatch) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ClickHouseCredentialsPatch) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Host.IsSet() {
		toSerialize["host"] = o.Host.Get()
	}
	if o.Port.IsSet() {
		toSerialize["port"] = o.Port.Get()
	}
	if o.DbName.IsSet() {
		toSerialize["db_name"] = o.DbName.Get()
	}
	if o.User.IsSet() {
		toSerialize["user"] = o.User.Get()
	}
	if o.Password.IsSet() {
		toSerialize["password"] = o.Password.Get()
	}
	return toSerialize, nil
}

type NullableClickHouseCredentialsPatch struct {
	value *ClickHouseCredentialsPatch
	isSet bool
}

func (v NullableClickHouseCredentialsPatch) Get() *ClickHouseCredentialsPatch {
	return v.value
}

func (v *NullableClickHouseCredentialsPatch) Set(val *ClickHouseCredentialsPatch) {
	v.value = val
	v.isSet = true
}

func (v NullableClickHouseCredentialsPatch) IsSet() bool {
	return v.isSet
}

func (v *NullableClickHouseCredentialsPatch) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableClickHouseCredentialsPatch(val *ClickHouseCredentialsPatch) *NullableClickHouseCredentialsPatch {
	return &NullableClickHouseCredentialsPatch{value: val, isSet: true}
}

func (v NullableClickHouseCredentialsPatch) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableClickHouseCredentialsPatch) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
