/*
Monte Carlo AI API

Programmatic access to the Monte Carlo AI platform.  Every response with a status of 400 or higher is `application/problem+json`, and carries a `code` naming the failure. That includes failures no single operation declares, such as calling a path with a method it does not support, which returns 405.  Every response carries an `X-Request-Id` header, and an error body repeats it as `request_id`. Quote it when reporting a problem. To choose the value yourself, send an `x-correlation-id` header; a value we cannot accept is replaced by a generated one.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package montecarlo

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the RedshiftCredentialsValidateIn type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RedshiftCredentialsValidateIn{}

// RedshiftCredentialsValidateIn Candidate Redshift credentials to validate.
type RedshiftCredentialsValidateIn struct {
	// Deployment that runs the validations. It has to be one `GET /deployments` lists, and it has to be able to reach the system the credentials are for.
	DeploymentId string `json:"deployment_id"`
	// Hostname of the database endpoint.
	Host string `json:"host"`
	// Port the database listens on.
	Port int32 `json:"port"`
	// Database user Monte Carlo logs in as.
	User string `json:"user"`
	// Password of the database user. Used for this check and not kept.
	Password string `json:"password"`
	// PEM text of the CA certificate the server's certificate is checked against.
	SslCaData NullableString `json:"ssl_ca_data,omitempty"`
	// Connect without TLS.
	SslDisabled NullableBool `json:"ssl_disabled,omitempty"`
	// Check the server's certificate against the CA.
	SslVerifyCert NullableBool `json:"ssl_verify_cert,omitempty"`
	// Check the certificate and that it names the host.
	SslVerifyIdentity NullableBool `json:"ssl_verify_identity,omitempty"`
	// Encrypt the connection without checking the server's certificate.
	SslSkipCertVerification NullableBool `json:"ssl_skip_cert_verification,omitempty"`
	// Redshift database to connect to.
	DbName string `json:"db_name"`
}

type _RedshiftCredentialsValidateIn RedshiftCredentialsValidateIn

// NewRedshiftCredentialsValidateIn instantiates a new RedshiftCredentialsValidateIn object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRedshiftCredentialsValidateIn(deploymentId string, host string, port int32, user string, password string, dbName string) *RedshiftCredentialsValidateIn {
	this := RedshiftCredentialsValidateIn{}
	this.DeploymentId = deploymentId
	this.Host = host
	this.Port = port
	this.User = user
	this.Password = password
	this.DbName = dbName
	return &this
}

// NewRedshiftCredentialsValidateInWithDefaults instantiates a new RedshiftCredentialsValidateIn object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRedshiftCredentialsValidateInWithDefaults() *RedshiftCredentialsValidateIn {
	this := RedshiftCredentialsValidateIn{}
	return &this
}

// GetDeploymentId returns the DeploymentId field value
func (o *RedshiftCredentialsValidateIn) GetDeploymentId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DeploymentId
}

// GetDeploymentIdOk returns a tuple with the DeploymentId field value
// and a boolean to check if the value has been set.
func (o *RedshiftCredentialsValidateIn) GetDeploymentIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DeploymentId, true
}

// SetDeploymentId sets field value
func (o *RedshiftCredentialsValidateIn) SetDeploymentId(v string) {
	o.DeploymentId = v
}

// GetHost returns the Host field value
func (o *RedshiftCredentialsValidateIn) GetHost() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Host
}

// GetHostOk returns a tuple with the Host field value
// and a boolean to check if the value has been set.
func (o *RedshiftCredentialsValidateIn) GetHostOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Host, true
}

// SetHost sets field value
func (o *RedshiftCredentialsValidateIn) SetHost(v string) {
	o.Host = v
}

// GetPort returns the Port field value
func (o *RedshiftCredentialsValidateIn) GetPort() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Port
}

// GetPortOk returns a tuple with the Port field value
// and a boolean to check if the value has been set.
func (o *RedshiftCredentialsValidateIn) GetPortOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Port, true
}

// SetPort sets field value
func (o *RedshiftCredentialsValidateIn) SetPort(v int32) {
	o.Port = v
}

// GetUser returns the User field value
func (o *RedshiftCredentialsValidateIn) GetUser() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.User
}

// GetUserOk returns a tuple with the User field value
// and a boolean to check if the value has been set.
func (o *RedshiftCredentialsValidateIn) GetUserOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.User, true
}

// SetUser sets field value
func (o *RedshiftCredentialsValidateIn) SetUser(v string) {
	o.User = v
}

// GetPassword returns the Password field value
func (o *RedshiftCredentialsValidateIn) GetPassword() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Password
}

// GetPasswordOk returns a tuple with the Password field value
// and a boolean to check if the value has been set.
func (o *RedshiftCredentialsValidateIn) GetPasswordOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Password, true
}

// SetPassword sets field value
func (o *RedshiftCredentialsValidateIn) SetPassword(v string) {
	o.Password = v
}

// GetSslCaData returns the SslCaData field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RedshiftCredentialsValidateIn) GetSslCaData() string {
	if o == nil || IsNil(o.SslCaData.Get()) {
		var ret string
		return ret
	}
	return *o.SslCaData.Get()
}

// GetSslCaDataOk returns a tuple with the SslCaData field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RedshiftCredentialsValidateIn) GetSslCaDataOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SslCaData.Get(), o.SslCaData.IsSet()
}

// HasSslCaData returns a boolean if a field has been set.
func (o *RedshiftCredentialsValidateIn) HasSslCaData() bool {
	if o != nil && o.SslCaData.IsSet() {
		return true
	}

	return false
}

// SetSslCaData gets a reference to the given NullableString and assigns it to the SslCaData field.
func (o *RedshiftCredentialsValidateIn) SetSslCaData(v string) {
	o.SslCaData.Set(&v)
}

// SetSslCaDataNil sets the value for SslCaData to be an explicit nil
func (o *RedshiftCredentialsValidateIn) SetSslCaDataNil() {
	o.SslCaData.Set(nil)
}

// UnsetSslCaData ensures that no value is present for SslCaData, not even an explicit nil
func (o *RedshiftCredentialsValidateIn) UnsetSslCaData() {
	o.SslCaData.Unset()
}

// GetSslDisabled returns the SslDisabled field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RedshiftCredentialsValidateIn) GetSslDisabled() bool {
	if o == nil || IsNil(o.SslDisabled.Get()) {
		var ret bool
		return ret
	}
	return *o.SslDisabled.Get()
}

// GetSslDisabledOk returns a tuple with the SslDisabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RedshiftCredentialsValidateIn) GetSslDisabledOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.SslDisabled.Get(), o.SslDisabled.IsSet()
}

// HasSslDisabled returns a boolean if a field has been set.
func (o *RedshiftCredentialsValidateIn) HasSslDisabled() bool {
	if o != nil && o.SslDisabled.IsSet() {
		return true
	}

	return false
}

// SetSslDisabled gets a reference to the given NullableBool and assigns it to the SslDisabled field.
func (o *RedshiftCredentialsValidateIn) SetSslDisabled(v bool) {
	o.SslDisabled.Set(&v)
}

// SetSslDisabledNil sets the value for SslDisabled to be an explicit nil
func (o *RedshiftCredentialsValidateIn) SetSslDisabledNil() {
	o.SslDisabled.Set(nil)
}

// UnsetSslDisabled ensures that no value is present for SslDisabled, not even an explicit nil
func (o *RedshiftCredentialsValidateIn) UnsetSslDisabled() {
	o.SslDisabled.Unset()
}

// GetSslVerifyCert returns the SslVerifyCert field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RedshiftCredentialsValidateIn) GetSslVerifyCert() bool {
	if o == nil || IsNil(o.SslVerifyCert.Get()) {
		var ret bool
		return ret
	}
	return *o.SslVerifyCert.Get()
}

// GetSslVerifyCertOk returns a tuple with the SslVerifyCert field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RedshiftCredentialsValidateIn) GetSslVerifyCertOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.SslVerifyCert.Get(), o.SslVerifyCert.IsSet()
}

// HasSslVerifyCert returns a boolean if a field has been set.
func (o *RedshiftCredentialsValidateIn) HasSslVerifyCert() bool {
	if o != nil && o.SslVerifyCert.IsSet() {
		return true
	}

	return false
}

// SetSslVerifyCert gets a reference to the given NullableBool and assigns it to the SslVerifyCert field.
func (o *RedshiftCredentialsValidateIn) SetSslVerifyCert(v bool) {
	o.SslVerifyCert.Set(&v)
}

// SetSslVerifyCertNil sets the value for SslVerifyCert to be an explicit nil
func (o *RedshiftCredentialsValidateIn) SetSslVerifyCertNil() {
	o.SslVerifyCert.Set(nil)
}

// UnsetSslVerifyCert ensures that no value is present for SslVerifyCert, not even an explicit nil
func (o *RedshiftCredentialsValidateIn) UnsetSslVerifyCert() {
	o.SslVerifyCert.Unset()
}

// GetSslVerifyIdentity returns the SslVerifyIdentity field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RedshiftCredentialsValidateIn) GetSslVerifyIdentity() bool {
	if o == nil || IsNil(o.SslVerifyIdentity.Get()) {
		var ret bool
		return ret
	}
	return *o.SslVerifyIdentity.Get()
}

// GetSslVerifyIdentityOk returns a tuple with the SslVerifyIdentity field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RedshiftCredentialsValidateIn) GetSslVerifyIdentityOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.SslVerifyIdentity.Get(), o.SslVerifyIdentity.IsSet()
}

// HasSslVerifyIdentity returns a boolean if a field has been set.
func (o *RedshiftCredentialsValidateIn) HasSslVerifyIdentity() bool {
	if o != nil && o.SslVerifyIdentity.IsSet() {
		return true
	}

	return false
}

// SetSslVerifyIdentity gets a reference to the given NullableBool and assigns it to the SslVerifyIdentity field.
func (o *RedshiftCredentialsValidateIn) SetSslVerifyIdentity(v bool) {
	o.SslVerifyIdentity.Set(&v)
}

// SetSslVerifyIdentityNil sets the value for SslVerifyIdentity to be an explicit nil
func (o *RedshiftCredentialsValidateIn) SetSslVerifyIdentityNil() {
	o.SslVerifyIdentity.Set(nil)
}

// UnsetSslVerifyIdentity ensures that no value is present for SslVerifyIdentity, not even an explicit nil
func (o *RedshiftCredentialsValidateIn) UnsetSslVerifyIdentity() {
	o.SslVerifyIdentity.Unset()
}

// GetSslSkipCertVerification returns the SslSkipCertVerification field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RedshiftCredentialsValidateIn) GetSslSkipCertVerification() bool {
	if o == nil || IsNil(o.SslSkipCertVerification.Get()) {
		var ret bool
		return ret
	}
	return *o.SslSkipCertVerification.Get()
}

// GetSslSkipCertVerificationOk returns a tuple with the SslSkipCertVerification field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RedshiftCredentialsValidateIn) GetSslSkipCertVerificationOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.SslSkipCertVerification.Get(), o.SslSkipCertVerification.IsSet()
}

// HasSslSkipCertVerification returns a boolean if a field has been set.
func (o *RedshiftCredentialsValidateIn) HasSslSkipCertVerification() bool {
	if o != nil && o.SslSkipCertVerification.IsSet() {
		return true
	}

	return false
}

// SetSslSkipCertVerification gets a reference to the given NullableBool and assigns it to the SslSkipCertVerification field.
func (o *RedshiftCredentialsValidateIn) SetSslSkipCertVerification(v bool) {
	o.SslSkipCertVerification.Set(&v)
}

// SetSslSkipCertVerificationNil sets the value for SslSkipCertVerification to be an explicit nil
func (o *RedshiftCredentialsValidateIn) SetSslSkipCertVerificationNil() {
	o.SslSkipCertVerification.Set(nil)
}

// UnsetSslSkipCertVerification ensures that no value is present for SslSkipCertVerification, not even an explicit nil
func (o *RedshiftCredentialsValidateIn) UnsetSslSkipCertVerification() {
	o.SslSkipCertVerification.Unset()
}

// GetDbName returns the DbName field value
func (o *RedshiftCredentialsValidateIn) GetDbName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DbName
}

// GetDbNameOk returns a tuple with the DbName field value
// and a boolean to check if the value has been set.
func (o *RedshiftCredentialsValidateIn) GetDbNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DbName, true
}

// SetDbName sets field value
func (o *RedshiftCredentialsValidateIn) SetDbName(v string) {
	o.DbName = v
}

func (o RedshiftCredentialsValidateIn) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RedshiftCredentialsValidateIn) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["deployment_id"] = o.DeploymentId
	toSerialize["host"] = o.Host
	toSerialize["port"] = o.Port
	toSerialize["user"] = o.User
	toSerialize["password"] = o.Password
	if o.SslCaData.IsSet() {
		toSerialize["ssl_ca_data"] = o.SslCaData.Get()
	}
	if o.SslDisabled.IsSet() {
		toSerialize["ssl_disabled"] = o.SslDisabled.Get()
	}
	if o.SslVerifyCert.IsSet() {
		toSerialize["ssl_verify_cert"] = o.SslVerifyCert.Get()
	}
	if o.SslVerifyIdentity.IsSet() {
		toSerialize["ssl_verify_identity"] = o.SslVerifyIdentity.Get()
	}
	if o.SslSkipCertVerification.IsSet() {
		toSerialize["ssl_skip_cert_verification"] = o.SslSkipCertVerification.Get()
	}
	toSerialize["db_name"] = o.DbName
	return toSerialize, nil
}

func (o *RedshiftCredentialsValidateIn) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"deployment_id",
		"host",
		"port",
		"user",
		"password",
		"db_name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRedshiftCredentialsValidateIn := _RedshiftCredentialsValidateIn{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRedshiftCredentialsValidateIn)

	if err != nil {
		return err
	}

	*o = RedshiftCredentialsValidateIn(varRedshiftCredentialsValidateIn)

	return err
}

type NullableRedshiftCredentialsValidateIn struct {
	value *RedshiftCredentialsValidateIn
	isSet bool
}

func (v NullableRedshiftCredentialsValidateIn) Get() *RedshiftCredentialsValidateIn {
	return v.value
}

func (v *NullableRedshiftCredentialsValidateIn) Set(val *RedshiftCredentialsValidateIn) {
	v.value = val
	v.isSet = true
}

func (v NullableRedshiftCredentialsValidateIn) IsSet() bool {
	return v.isSet
}

func (v *NullableRedshiftCredentialsValidateIn) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRedshiftCredentialsValidateIn(val *RedshiftCredentialsValidateIn) *NullableRedshiftCredentialsValidateIn {
	return &NullableRedshiftCredentialsValidateIn{value: val, isSet: true}
}

func (v NullableRedshiftCredentialsValidateIn) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRedshiftCredentialsValidateIn) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
