/*
Monte Carlo AI API

Programmatic access to the Monte Carlo AI platform.  Every response with a status of 400 or higher is `application/problem+json`, and carries a `code` naming the failure. That includes failures no single operation declares, such as calling a path with a method it does not support, which returns 405.  Every response carries an `X-Request-Id` header, and an error body repeats it as `request_id`. Quote it when reporting a problem. To choose the value yourself, send an `x-correlation-id` header; a value we cannot accept is replaced by a generated one.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package montecarlo

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"
)

// checks if the LookerCredentialsOut type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LookerCredentialsOut{}

// LookerCredentialsOut Looker API credentials Monte Carlo stores. The client secret is never returned.
type LookerCredentialsOut struct {
	// Unique identifier of the credentials.
	Id string `json:"id"`
	// The connection type the credentials are for, such as `snowflake`. Fixed once created.
	ConnectionType string `json:"connection_type"`
	// Where the secret lives. Fixed once created.
	StorageType CredentialsStorageType `json:"storage_type"`
	// When the credentials were created.
	CreatedTime time.Time `json:"created_time"`
	// URL of the Looker API, such as https://acme.cloud.looker.com.
	BaseUrl string `json:"base_url"`
	// Client ID of the Looker API key.
	ApiClientId string `json:"api_client_id"`
	// Whether to verify Looker's TLS certificate. Verified when left out. Null unless set.
	VerifySsl NullableBool `json:"verify_ssl"`
}

type _LookerCredentialsOut LookerCredentialsOut

// NewLookerCredentialsOut instantiates a new LookerCredentialsOut object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLookerCredentialsOut(id string, connectionType string, storageType CredentialsStorageType, createdTime time.Time, baseUrl string, apiClientId string, verifySsl NullableBool) *LookerCredentialsOut {
	this := LookerCredentialsOut{}
	this.Id = id
	this.ConnectionType = connectionType
	this.StorageType = storageType
	this.CreatedTime = createdTime
	this.BaseUrl = baseUrl
	this.ApiClientId = apiClientId
	this.VerifySsl = verifySsl
	return &this
}

// NewLookerCredentialsOutWithDefaults instantiates a new LookerCredentialsOut object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLookerCredentialsOutWithDefaults() *LookerCredentialsOut {
	this := LookerCredentialsOut{}
	return &this
}

// GetId returns the Id field value
func (o *LookerCredentialsOut) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *LookerCredentialsOut) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *LookerCredentialsOut) SetId(v string) {
	o.Id = v
}

// GetConnectionType returns the ConnectionType field value
func (o *LookerCredentialsOut) GetConnectionType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ConnectionType
}

// GetConnectionTypeOk returns a tuple with the ConnectionType field value
// and a boolean to check if the value has been set.
func (o *LookerCredentialsOut) GetConnectionTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ConnectionType, true
}

// SetConnectionType sets field value
func (o *LookerCredentialsOut) SetConnectionType(v string) {
	o.ConnectionType = v
}

// GetStorageType returns the StorageType field value
func (o *LookerCredentialsOut) GetStorageType() CredentialsStorageType {
	if o == nil {
		var ret CredentialsStorageType
		return ret
	}

	return o.StorageType
}

// GetStorageTypeOk returns a tuple with the StorageType field value
// and a boolean to check if the value has been set.
func (o *LookerCredentialsOut) GetStorageTypeOk() (*CredentialsStorageType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StorageType, true
}

// SetStorageType sets field value
func (o *LookerCredentialsOut) SetStorageType(v CredentialsStorageType) {
	o.StorageType = v
}

// GetCreatedTime returns the CreatedTime field value
func (o *LookerCredentialsOut) GetCreatedTime() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedTime
}

// GetCreatedTimeOk returns a tuple with the CreatedTime field value
// and a boolean to check if the value has been set.
func (o *LookerCredentialsOut) GetCreatedTimeOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedTime, true
}

// SetCreatedTime sets field value
func (o *LookerCredentialsOut) SetCreatedTime(v time.Time) {
	o.CreatedTime = v
}

// GetBaseUrl returns the BaseUrl field value
func (o *LookerCredentialsOut) GetBaseUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BaseUrl
}

// GetBaseUrlOk returns a tuple with the BaseUrl field value
// and a boolean to check if the value has been set.
func (o *LookerCredentialsOut) GetBaseUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BaseUrl, true
}

// SetBaseUrl sets field value
func (o *LookerCredentialsOut) SetBaseUrl(v string) {
	o.BaseUrl = v
}

// GetApiClientId returns the ApiClientId field value
func (o *LookerCredentialsOut) GetApiClientId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ApiClientId
}

// GetApiClientIdOk returns a tuple with the ApiClientId field value
// and a boolean to check if the value has been set.
func (o *LookerCredentialsOut) GetApiClientIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ApiClientId, true
}

// SetApiClientId sets field value
func (o *LookerCredentialsOut) SetApiClientId(v string) {
	o.ApiClientId = v
}

// GetVerifySsl returns the VerifySsl field value
// If the value is explicit nil, the zero value for bool will be returned
func (o *LookerCredentialsOut) GetVerifySsl() bool {
	if o == nil || o.VerifySsl.Get() == nil {
		var ret bool
		return ret
	}

	return *o.VerifySsl.Get()
}

// GetVerifySslOk returns a tuple with the VerifySsl field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *LookerCredentialsOut) GetVerifySslOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.VerifySsl.Get(), o.VerifySsl.IsSet()
}

// SetVerifySsl sets field value
func (o *LookerCredentialsOut) SetVerifySsl(v bool) {
	o.VerifySsl.Set(&v)
}

func (o LookerCredentialsOut) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LookerCredentialsOut) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["connection_type"] = o.ConnectionType
	toSerialize["storage_type"] = o.StorageType
	toSerialize["created_time"] = o.CreatedTime
	toSerialize["base_url"] = o.BaseUrl
	toSerialize["api_client_id"] = o.ApiClientId
	toSerialize["verify_ssl"] = o.VerifySsl.Get()
	return toSerialize, nil
}

func (o *LookerCredentialsOut) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"connection_type",
		"storage_type",
		"created_time",
		"base_url",
		"api_client_id",
		"verify_ssl",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varLookerCredentialsOut := _LookerCredentialsOut{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varLookerCredentialsOut)

	if err != nil {
		return err
	}

	*o = LookerCredentialsOut(varLookerCredentialsOut)

	return err
}

type NullableLookerCredentialsOut struct {
	value *LookerCredentialsOut
	isSet bool
}

func (v NullableLookerCredentialsOut) Get() *LookerCredentialsOut {
	return v.value
}

func (v *NullableLookerCredentialsOut) Set(val *LookerCredentialsOut) {
	v.value = val
	v.isSet = true
}

func (v NullableLookerCredentialsOut) IsSet() bool {
	return v.isSet
}

func (v *NullableLookerCredentialsOut) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLookerCredentialsOut(val *LookerCredentialsOut) *NullableLookerCredentialsOut {
	return &NullableLookerCredentialsOut{value: val, isSet: true}
}

func (v NullableLookerCredentialsOut) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLookerCredentialsOut) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
