/*
Monte Carlo AI API

Programmatic access to the Monte Carlo AI platform.  Every response with a status of 400 or higher is `application/problem+json`, and carries a `code` naming the failure. That includes failures no single operation declares, such as calling a path with a method it does not support, which returns 405.  Every response carries an `X-Request-Id` header, and an error body repeats it as `request_id`. Quote it when reporting a problem. To choose the value yourself, send an `x-correlation-id` header; a value we cannot accept is replaced by a generated one.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package montecarlo

import (
	"encoding/json"
)

// checks if the ConnectionPatch type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConnectionPatch{}

// ConnectionPatch A change to an existing connection. Sent when renaming one.
type ConnectionPatch struct {
	// New display name for the connection. Omit it to leave the name unchanged. An explicit null is ignored, the same as omitting the field.
	Name NullableString `json:"name,omitempty"`
}

// NewConnectionPatch instantiates a new ConnectionPatch object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConnectionPatch() *ConnectionPatch {
	this := ConnectionPatch{}
	return &this
}

// NewConnectionPatchWithDefaults instantiates a new ConnectionPatch object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConnectionPatchWithDefaults() *ConnectionPatch {
	this := ConnectionPatch{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ConnectionPatch) GetName() string {
	if o == nil || IsNil(o.Name.Get()) {
		var ret string
		return ret
	}
	return *o.Name.Get()
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ConnectionPatch) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Name.Get(), o.Name.IsSet()
}

// HasName returns a boolean if a field has been set.
func (o *ConnectionPatch) HasName() bool {
	if o != nil && o.Name.IsSet() {
		return true
	}

	return false
}

// SetName gets a reference to the given NullableString and assigns it to the Name field.
func (o *ConnectionPatch) SetName(v string) {
	o.Name.Set(&v)
}

// SetNameNil sets the value for Name to be an explicit nil
func (o *ConnectionPatch) SetNameNil() {
	o.Name.Set(nil)
}

// UnsetName ensures that no value is present for Name, not even an explicit nil
func (o *ConnectionPatch) UnsetName() {
	o.Name.Unset()
}

func (o ConnectionPatch) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConnectionPatch) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Name.IsSet() {
		toSerialize["name"] = o.Name.Get()
	}
	return toSerialize, nil
}

type NullableConnectionPatch struct {
	value *ConnectionPatch
	isSet bool
}

func (v NullableConnectionPatch) Get() *ConnectionPatch {
	return v.value
}

func (v *NullableConnectionPatch) Set(val *ConnectionPatch) {
	v.value = val
	v.isSet = true
}

func (v NullableConnectionPatch) IsSet() bool {
	return v.isSet
}

func (v *NullableConnectionPatch) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConnectionPatch(val *ConnectionPatch) *NullableConnectionPatch {
	return &NullableConnectionPatch{value: val, isSet: true}
}

func (v NullableConnectionPatch) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConnectionPatch) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
