/*
Monte Carlo AI API

Programmatic access to the Monte Carlo AI platform.  Every response with a status of 400 or higher is `application/problem+json`, and carries a `code` naming the failure. That includes failures no single operation declares, such as calling a path with a method it does not support, which returns 405.  Every response carries an `X-Request-Id` header, and an error body repeats it as `request_id`. Quote it when reporting a problem. To choose the value yourself, send an `x-correlation-id` header; a value we cannot accept is replaced by a generated one.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package montecarlo

import (
	"encoding/json"
	"fmt"
)

// RunStatus Whether a run is still going.  A completed run is final: nothing in it changes again, and polling it a second time returns the same answer.
type RunStatus string

// List of RunStatus
const (
	RUNSTATUS_RUNNING   RunStatus = "running"
	RUNSTATUS_COMPLETED RunStatus = "completed"
)

// All allowed values of RunStatus enum
var AllowedRunStatusEnumValues = []RunStatus{
	"running",
	"completed",
}

func (v *RunStatus) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := RunStatus(value)
	for _, existing := range AllowedRunStatusEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid RunStatus", value)
}

// NewRunStatusFromValue returns a pointer to a valid RunStatus
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewRunStatusFromValue(v string) (*RunStatus, error) {
	ev := RunStatus(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for RunStatus: valid values are %v", v, AllowedRunStatusEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v RunStatus) IsValid() bool {
	for _, existing := range AllowedRunStatusEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to RunStatus value
func (v RunStatus) Ptr() *RunStatus {
	return &v
}

type NullableRunStatus struct {
	value *RunStatus
	isSet bool
}

func (v NullableRunStatus) Get() *RunStatus {
	return v.value
}

func (v *NullableRunStatus) Set(val *RunStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableRunStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableRunStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRunStatus(val *RunStatus) *NullableRunStatus {
	return &NullableRunStatus{value: val, isSet: true}
}

func (v NullableRunStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRunStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
