/*
Monte Carlo AI API

Programmatic access to the Monte Carlo AI platform.  Every response with a status of 400 or higher is `application/problem+json`, and carries a `code` naming the failure. That includes failures no single operation declares, such as calling a path with a method it does not support, which returns 405.  Every response carries an `X-Request-Id` header, and an error body repeats it as `request_id`. Quote it when reporting a problem. To choose the value yourself, send an `x-correlation-id` header; a value we cannot accept is replaced by a generated one.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package montecarlo

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the LookerGitCloneCredentialsValidateIn type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LookerGitCloneCredentialsValidateIn{}

// LookerGitCloneCredentialsValidateIn Candidate LookML repository credentials to validate.
type LookerGitCloneCredentialsValidateIn struct {
	// Deployment that runs the validations. It has to be one `GET /deployments` lists, and it has to be able to reach the system the credentials are for.
	DeploymentId string `json:"deployment_id"`
	// Git user for an HTTPS clone. Send it with `token`.
	Username NullableString `json:"username,omitempty"`
	// PEM certificate of the CA that signed the git server's certificate.
	SslCaData NullableString `json:"ssl_ca_data,omitempty"`
	// Skip verifying the git server's TLS certificate.
	SslSkipCertVerification NullableBool `json:"ssl_skip_cert_verification,omitempty"`
	// Access token of `username`, for an HTTPS clone. Send this or `ssh_key`. Used for this check and not kept.
	Token NullableString `json:"token,omitempty"`
	// Private key for an SSH clone, as PEM text including its BEGIN and END lines. Send this or `username` and `token`. Used for this check and not kept.
	SshKey NullableString `json:"ssh_key,omitempty"`
	// Clone URL of the LookML repository, over HTTPS or SSH.
	RepoUrl string `json:"repo_url"`
}

type _LookerGitCloneCredentialsValidateIn LookerGitCloneCredentialsValidateIn

// NewLookerGitCloneCredentialsValidateIn instantiates a new LookerGitCloneCredentialsValidateIn object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLookerGitCloneCredentialsValidateIn(deploymentId string, repoUrl string) *LookerGitCloneCredentialsValidateIn {
	this := LookerGitCloneCredentialsValidateIn{}
	this.DeploymentId = deploymentId
	this.RepoUrl = repoUrl
	return &this
}

// NewLookerGitCloneCredentialsValidateInWithDefaults instantiates a new LookerGitCloneCredentialsValidateIn object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLookerGitCloneCredentialsValidateInWithDefaults() *LookerGitCloneCredentialsValidateIn {
	this := LookerGitCloneCredentialsValidateIn{}
	return &this
}

// GetDeploymentId returns the DeploymentId field value
func (o *LookerGitCloneCredentialsValidateIn) GetDeploymentId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DeploymentId
}

// GetDeploymentIdOk returns a tuple with the DeploymentId field value
// and a boolean to check if the value has been set.
func (o *LookerGitCloneCredentialsValidateIn) GetDeploymentIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DeploymentId, true
}

// SetDeploymentId sets field value
func (o *LookerGitCloneCredentialsValidateIn) SetDeploymentId(v string) {
	o.DeploymentId = v
}

// GetUsername returns the Username field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *LookerGitCloneCredentialsValidateIn) GetUsername() string {
	if o == nil || IsNil(o.Username.Get()) {
		var ret string
		return ret
	}
	return *o.Username.Get()
}

// GetUsernameOk returns a tuple with the Username field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *LookerGitCloneCredentialsValidateIn) GetUsernameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Username.Get(), o.Username.IsSet()
}

// HasUsername returns a boolean if a field has been set.
func (o *LookerGitCloneCredentialsValidateIn) HasUsername() bool {
	if o != nil && o.Username.IsSet() {
		return true
	}

	return false
}

// SetUsername gets a reference to the given NullableString and assigns it to the Username field.
func (o *LookerGitCloneCredentialsValidateIn) SetUsername(v string) {
	o.Username.Set(&v)
}

// SetUsernameNil sets the value for Username to be an explicit nil
func (o *LookerGitCloneCredentialsValidateIn) SetUsernameNil() {
	o.Username.Set(nil)
}

// UnsetUsername ensures that no value is present for Username, not even an explicit nil
func (o *LookerGitCloneCredentialsValidateIn) UnsetUsername() {
	o.Username.Unset()
}

// GetSslCaData returns the SslCaData field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *LookerGitCloneCredentialsValidateIn) GetSslCaData() string {
	if o == nil || IsNil(o.SslCaData.Get()) {
		var ret string
		return ret
	}
	return *o.SslCaData.Get()
}

// GetSslCaDataOk returns a tuple with the SslCaData field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *LookerGitCloneCredentialsValidateIn) GetSslCaDataOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SslCaData.Get(), o.SslCaData.IsSet()
}

// HasSslCaData returns a boolean if a field has been set.
func (o *LookerGitCloneCredentialsValidateIn) HasSslCaData() bool {
	if o != nil && o.SslCaData.IsSet() {
		return true
	}

	return false
}

// SetSslCaData gets a reference to the given NullableString and assigns it to the SslCaData field.
func (o *LookerGitCloneCredentialsValidateIn) SetSslCaData(v string) {
	o.SslCaData.Set(&v)
}

// SetSslCaDataNil sets the value for SslCaData to be an explicit nil
func (o *LookerGitCloneCredentialsValidateIn) SetSslCaDataNil() {
	o.SslCaData.Set(nil)
}

// UnsetSslCaData ensures that no value is present for SslCaData, not even an explicit nil
func (o *LookerGitCloneCredentialsValidateIn) UnsetSslCaData() {
	o.SslCaData.Unset()
}

// GetSslSkipCertVerification returns the SslSkipCertVerification field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *LookerGitCloneCredentialsValidateIn) GetSslSkipCertVerification() bool {
	if o == nil || IsNil(o.SslSkipCertVerification.Get()) {
		var ret bool
		return ret
	}
	return *o.SslSkipCertVerification.Get()
}

// GetSslSkipCertVerificationOk returns a tuple with the SslSkipCertVerification field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *LookerGitCloneCredentialsValidateIn) GetSslSkipCertVerificationOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.SslSkipCertVerification.Get(), o.SslSkipCertVerification.IsSet()
}

// HasSslSkipCertVerification returns a boolean if a field has been set.
func (o *LookerGitCloneCredentialsValidateIn) HasSslSkipCertVerification() bool {
	if o != nil && o.SslSkipCertVerification.IsSet() {
		return true
	}

	return false
}

// SetSslSkipCertVerification gets a reference to the given NullableBool and assigns it to the SslSkipCertVerification field.
func (o *LookerGitCloneCredentialsValidateIn) SetSslSkipCertVerification(v bool) {
	o.SslSkipCertVerification.Set(&v)
}

// SetSslSkipCertVerificationNil sets the value for SslSkipCertVerification to be an explicit nil
func (o *LookerGitCloneCredentialsValidateIn) SetSslSkipCertVerificationNil() {
	o.SslSkipCertVerification.Set(nil)
}

// UnsetSslSkipCertVerification ensures that no value is present for SslSkipCertVerification, not even an explicit nil
func (o *LookerGitCloneCredentialsValidateIn) UnsetSslSkipCertVerification() {
	o.SslSkipCertVerification.Unset()
}

// GetToken returns the Token field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *LookerGitCloneCredentialsValidateIn) GetToken() string {
	if o == nil || IsNil(o.Token.Get()) {
		var ret string
		return ret
	}
	return *o.Token.Get()
}

// GetTokenOk returns a tuple with the Token field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *LookerGitCloneCredentialsValidateIn) GetTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Token.Get(), o.Token.IsSet()
}

// HasToken returns a boolean if a field has been set.
func (o *LookerGitCloneCredentialsValidateIn) HasToken() bool {
	if o != nil && o.Token.IsSet() {
		return true
	}

	return false
}

// SetToken gets a reference to the given NullableString and assigns it to the Token field.
func (o *LookerGitCloneCredentialsValidateIn) SetToken(v string) {
	o.Token.Set(&v)
}

// SetTokenNil sets the value for Token to be an explicit nil
func (o *LookerGitCloneCredentialsValidateIn) SetTokenNil() {
	o.Token.Set(nil)
}

// UnsetToken ensures that no value is present for Token, not even an explicit nil
func (o *LookerGitCloneCredentialsValidateIn) UnsetToken() {
	o.Token.Unset()
}

// GetSshKey returns the SshKey field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *LookerGitCloneCredentialsValidateIn) GetSshKey() string {
	if o == nil || IsNil(o.SshKey.Get()) {
		var ret string
		return ret
	}
	return *o.SshKey.Get()
}

// GetSshKeyOk returns a tuple with the SshKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *LookerGitCloneCredentialsValidateIn) GetSshKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SshKey.Get(), o.SshKey.IsSet()
}

// HasSshKey returns a boolean if a field has been set.
func (o *LookerGitCloneCredentialsValidateIn) HasSshKey() bool {
	if o != nil && o.SshKey.IsSet() {
		return true
	}

	return false
}

// SetSshKey gets a reference to the given NullableString and assigns it to the SshKey field.
func (o *LookerGitCloneCredentialsValidateIn) SetSshKey(v string) {
	o.SshKey.Set(&v)
}

// SetSshKeyNil sets the value for SshKey to be an explicit nil
func (o *LookerGitCloneCredentialsValidateIn) SetSshKeyNil() {
	o.SshKey.Set(nil)
}

// UnsetSshKey ensures that no value is present for SshKey, not even an explicit nil
func (o *LookerGitCloneCredentialsValidateIn) UnsetSshKey() {
	o.SshKey.Unset()
}

// GetRepoUrl returns the RepoUrl field value
func (o *LookerGitCloneCredentialsValidateIn) GetRepoUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RepoUrl
}

// GetRepoUrlOk returns a tuple with the RepoUrl field value
// and a boolean to check if the value has been set.
func (o *LookerGitCloneCredentialsValidateIn) GetRepoUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RepoUrl, true
}

// SetRepoUrl sets field value
func (o *LookerGitCloneCredentialsValidateIn) SetRepoUrl(v string) {
	o.RepoUrl = v
}

func (o LookerGitCloneCredentialsValidateIn) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LookerGitCloneCredentialsValidateIn) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["deployment_id"] = o.DeploymentId
	if o.Username.IsSet() {
		toSerialize["username"] = o.Username.Get()
	}
	if o.SslCaData.IsSet() {
		toSerialize["ssl_ca_data"] = o.SslCaData.Get()
	}
	if o.SslSkipCertVerification.IsSet() {
		toSerialize["ssl_skip_cert_verification"] = o.SslSkipCertVerification.Get()
	}
	if o.Token.IsSet() {
		toSerialize["token"] = o.Token.Get()
	}
	if o.SshKey.IsSet() {
		toSerialize["ssh_key"] = o.SshKey.Get()
	}
	toSerialize["repo_url"] = o.RepoUrl
	return toSerialize, nil
}

func (o *LookerGitCloneCredentialsValidateIn) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"deployment_id",
		"repo_url",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varLookerGitCloneCredentialsValidateIn := _LookerGitCloneCredentialsValidateIn{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varLookerGitCloneCredentialsValidateIn)

	if err != nil {
		return err
	}

	*o = LookerGitCloneCredentialsValidateIn(varLookerGitCloneCredentialsValidateIn)

	return err
}

type NullableLookerGitCloneCredentialsValidateIn struct {
	value *LookerGitCloneCredentialsValidateIn
	isSet bool
}

func (v NullableLookerGitCloneCredentialsValidateIn) Get() *LookerGitCloneCredentialsValidateIn {
	return v.value
}

func (v *NullableLookerGitCloneCredentialsValidateIn) Set(val *LookerGitCloneCredentialsValidateIn) {
	v.value = val
	v.isSet = true
}

func (v NullableLookerGitCloneCredentialsValidateIn) IsSet() bool {
	return v.isSet
}

func (v *NullableLookerGitCloneCredentialsValidateIn) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLookerGitCloneCredentialsValidateIn(val *LookerGitCloneCredentialsValidateIn) *NullableLookerGitCloneCredentialsValidateIn {
	return &NullableLookerGitCloneCredentialsValidateIn{value: val, isSet: true}
}

func (v NullableLookerGitCloneCredentialsValidateIn) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLookerGitCloneCredentialsValidateIn) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
