/*
Monte Carlo AI API

Programmatic access to the Monte Carlo AI platform.  Every response with a status of 400 or higher is `application/problem+json`, and carries a `code` naming the failure. That includes failures no single operation declares, such as calling a path with a method it does not support, which returns 405.  Every response carries an `X-Request-Id` header, and an error body repeats it as `request_id`. Quote it when reporting a problem. To choose the value yourself, send an `x-correlation-id` header; a value we cannot accept is replaced by a generated one.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package montecarlo

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"
)

// checks if the AzureCollectionDataStoreOut type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AzureCollectionDataStoreOut{}

// AzureCollectionDataStoreOut A data store held in an Azure Blob Storage container.  There is no external id: Monte Carlo assumes no role to reach Azure storage.
type AzureCollectionDataStoreOut struct {
	// Unique identifier of the data store.
	Id string `json:"id"`
	// Display name of the data store. Null when it has no name.
	Name NullableString `json:"name,omitempty"`
	// Identifier of the deployment this data store belongs to.
	DeploymentId string `json:"deployment_id"`
	// Which kind of storage the data store keeps its data in.
	StorageType StorageType `json:"storage_type"`
	// How Monte Carlo authenticates when it reaches the data store.
	AuthenticationType AuthenticationType `json:"authentication_type"`
	// Whether Monte Carlo is using this data store. One that is unregistered, or whose validation failed, is not enabled.
	Enabled bool `json:"enabled"`
	// When the data store was created, which is when its deployment was provisioned.
	CreatedTime NullableTime `json:"created_time,omitempty"`
	// When the data store was last registered, renamed, or given different storage or credentials. Null until one of those has happened.
	LastUpdatedTime NullableTime `json:"last_updated_time,omitempty"`
	// Name of the blob container Monte Carlo uses. Empty until it has been registered. The storage account holding it is part of the credentials, so it is not returned.
	ContainerName string `json:"container_name"`
}

type _AzureCollectionDataStoreOut AzureCollectionDataStoreOut

// NewAzureCollectionDataStoreOut instantiates a new AzureCollectionDataStoreOut object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAzureCollectionDataStoreOut(id string, deploymentId string, storageType StorageType, authenticationType AuthenticationType, enabled bool, containerName string) *AzureCollectionDataStoreOut {
	this := AzureCollectionDataStoreOut{}
	this.Id = id
	this.DeploymentId = deploymentId
	this.StorageType = storageType
	this.AuthenticationType = authenticationType
	this.Enabled = enabled
	this.ContainerName = containerName
	return &this
}

// NewAzureCollectionDataStoreOutWithDefaults instantiates a new AzureCollectionDataStoreOut object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAzureCollectionDataStoreOutWithDefaults() *AzureCollectionDataStoreOut {
	this := AzureCollectionDataStoreOut{}
	return &this
}

// GetId returns the Id field value
func (o *AzureCollectionDataStoreOut) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *AzureCollectionDataStoreOut) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *AzureCollectionDataStoreOut) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AzureCollectionDataStoreOut) GetName() string {
	if o == nil || IsNil(o.Name.Get()) {
		var ret string
		return ret
	}
	return *o.Name.Get()
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AzureCollectionDataStoreOut) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Name.Get(), o.Name.IsSet()
}

// HasName returns a boolean if a field has been set.
func (o *AzureCollectionDataStoreOut) HasName() bool {
	if o != nil && o.Name.IsSet() {
		return true
	}

	return false
}

// SetName gets a reference to the given NullableString and assigns it to the Name field.
func (o *AzureCollectionDataStoreOut) SetName(v string) {
	o.Name.Set(&v)
}

// SetNameNil sets the value for Name to be an explicit nil
func (o *AzureCollectionDataStoreOut) SetNameNil() {
	o.Name.Set(nil)
}

// UnsetName ensures that no value is present for Name, not even an explicit nil
func (o *AzureCollectionDataStoreOut) UnsetName() {
	o.Name.Unset()
}

// GetDeploymentId returns the DeploymentId field value
func (o *AzureCollectionDataStoreOut) GetDeploymentId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DeploymentId
}

// GetDeploymentIdOk returns a tuple with the DeploymentId field value
// and a boolean to check if the value has been set.
func (o *AzureCollectionDataStoreOut) GetDeploymentIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DeploymentId, true
}

// SetDeploymentId sets field value
func (o *AzureCollectionDataStoreOut) SetDeploymentId(v string) {
	o.DeploymentId = v
}

// GetStorageType returns the StorageType field value
func (o *AzureCollectionDataStoreOut) GetStorageType() StorageType {
	if o == nil {
		var ret StorageType
		return ret
	}

	return o.StorageType
}

// GetStorageTypeOk returns a tuple with the StorageType field value
// and a boolean to check if the value has been set.
func (o *AzureCollectionDataStoreOut) GetStorageTypeOk() (*StorageType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StorageType, true
}

// SetStorageType sets field value
func (o *AzureCollectionDataStoreOut) SetStorageType(v StorageType) {
	o.StorageType = v
}

// GetAuthenticationType returns the AuthenticationType field value
func (o *AzureCollectionDataStoreOut) GetAuthenticationType() AuthenticationType {
	if o == nil {
		var ret AuthenticationType
		return ret
	}

	return o.AuthenticationType
}

// GetAuthenticationTypeOk returns a tuple with the AuthenticationType field value
// and a boolean to check if the value has been set.
func (o *AzureCollectionDataStoreOut) GetAuthenticationTypeOk() (*AuthenticationType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AuthenticationType, true
}

// SetAuthenticationType sets field value
func (o *AzureCollectionDataStoreOut) SetAuthenticationType(v AuthenticationType) {
	o.AuthenticationType = v
}

// GetEnabled returns the Enabled field value
func (o *AzureCollectionDataStoreOut) GetEnabled() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value
// and a boolean to check if the value has been set.
func (o *AzureCollectionDataStoreOut) GetEnabledOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Enabled, true
}

// SetEnabled sets field value
func (o *AzureCollectionDataStoreOut) SetEnabled(v bool) {
	o.Enabled = v
}

// GetCreatedTime returns the CreatedTime field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AzureCollectionDataStoreOut) GetCreatedTime() time.Time {
	if o == nil || IsNil(o.CreatedTime.Get()) {
		var ret time.Time
		return ret
	}
	return *o.CreatedTime.Get()
}

// GetCreatedTimeOk returns a tuple with the CreatedTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AzureCollectionDataStoreOut) GetCreatedTimeOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.CreatedTime.Get(), o.CreatedTime.IsSet()
}

// HasCreatedTime returns a boolean if a field has been set.
func (o *AzureCollectionDataStoreOut) HasCreatedTime() bool {
	if o != nil && o.CreatedTime.IsSet() {
		return true
	}

	return false
}

// SetCreatedTime gets a reference to the given NullableTime and assigns it to the CreatedTime field.
func (o *AzureCollectionDataStoreOut) SetCreatedTime(v time.Time) {
	o.CreatedTime.Set(&v)
}

// SetCreatedTimeNil sets the value for CreatedTime to be an explicit nil
func (o *AzureCollectionDataStoreOut) SetCreatedTimeNil() {
	o.CreatedTime.Set(nil)
}

// UnsetCreatedTime ensures that no value is present for CreatedTime, not even an explicit nil
func (o *AzureCollectionDataStoreOut) UnsetCreatedTime() {
	o.CreatedTime.Unset()
}

// GetLastUpdatedTime returns the LastUpdatedTime field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AzureCollectionDataStoreOut) GetLastUpdatedTime() time.Time {
	if o == nil || IsNil(o.LastUpdatedTime.Get()) {
		var ret time.Time
		return ret
	}
	return *o.LastUpdatedTime.Get()
}

// GetLastUpdatedTimeOk returns a tuple with the LastUpdatedTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AzureCollectionDataStoreOut) GetLastUpdatedTimeOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.LastUpdatedTime.Get(), o.LastUpdatedTime.IsSet()
}

// HasLastUpdatedTime returns a boolean if a field has been set.
func (o *AzureCollectionDataStoreOut) HasLastUpdatedTime() bool {
	if o != nil && o.LastUpdatedTime.IsSet() {
		return true
	}

	return false
}

// SetLastUpdatedTime gets a reference to the given NullableTime and assigns it to the LastUpdatedTime field.
func (o *AzureCollectionDataStoreOut) SetLastUpdatedTime(v time.Time) {
	o.LastUpdatedTime.Set(&v)
}

// SetLastUpdatedTimeNil sets the value for LastUpdatedTime to be an explicit nil
func (o *AzureCollectionDataStoreOut) SetLastUpdatedTimeNil() {
	o.LastUpdatedTime.Set(nil)
}

// UnsetLastUpdatedTime ensures that no value is present for LastUpdatedTime, not even an explicit nil
func (o *AzureCollectionDataStoreOut) UnsetLastUpdatedTime() {
	o.LastUpdatedTime.Unset()
}

// GetContainerName returns the ContainerName field value
func (o *AzureCollectionDataStoreOut) GetContainerName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ContainerName
}

// GetContainerNameOk returns a tuple with the ContainerName field value
// and a boolean to check if the value has been set.
func (o *AzureCollectionDataStoreOut) GetContainerNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ContainerName, true
}

// SetContainerName sets field value
func (o *AzureCollectionDataStoreOut) SetContainerName(v string) {
	o.ContainerName = v
}

func (o AzureCollectionDataStoreOut) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AzureCollectionDataStoreOut) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	if o.Name.IsSet() {
		toSerialize["name"] = o.Name.Get()
	}
	toSerialize["deployment_id"] = o.DeploymentId
	toSerialize["storage_type"] = o.StorageType
	toSerialize["authentication_type"] = o.AuthenticationType
	toSerialize["enabled"] = o.Enabled
	if o.CreatedTime.IsSet() {
		toSerialize["created_time"] = o.CreatedTime.Get()
	}
	if o.LastUpdatedTime.IsSet() {
		toSerialize["last_updated_time"] = o.LastUpdatedTime.Get()
	}
	toSerialize["container_name"] = o.ContainerName
	return toSerialize, nil
}

func (o *AzureCollectionDataStoreOut) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"deployment_id",
		"storage_type",
		"authentication_type",
		"enabled",
		"container_name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAzureCollectionDataStoreOut := _AzureCollectionDataStoreOut{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAzureCollectionDataStoreOut)

	if err != nil {
		return err
	}

	*o = AzureCollectionDataStoreOut(varAzureCollectionDataStoreOut)

	return err
}

type NullableAzureCollectionDataStoreOut struct {
	value *AzureCollectionDataStoreOut
	isSet bool
}

func (v NullableAzureCollectionDataStoreOut) Get() *AzureCollectionDataStoreOut {
	return v.value
}

func (v *NullableAzureCollectionDataStoreOut) Set(val *AzureCollectionDataStoreOut) {
	v.value = val
	v.isSet = true
}

func (v NullableAzureCollectionDataStoreOut) IsSet() bool {
	return v.isSet
}

func (v *NullableAzureCollectionDataStoreOut) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAzureCollectionDataStoreOut(val *AzureCollectionDataStoreOut) *NullableAzureCollectionDataStoreOut {
	return &NullableAzureCollectionDataStoreOut{value: val, isSet: true}
}

func (v NullableAzureCollectionDataStoreOut) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAzureCollectionDataStoreOut) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
