/*
Monte Carlo AI API

Programmatic access to the Monte Carlo AI platform.  Every response with a status of 400 or higher is `application/problem+json`, and carries a `code` naming the failure. That includes failures no single operation declares, such as calling a path with a method it does not support, which returns 405.  Every response carries an `X-Request-Id` header, and an error body repeats it as `request_id`. Quote it when reporting a problem. To choose the value yourself, send an `x-correlation-id` header; a value we cannot accept is replaced by a generated one.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package montecarlo

import (
	"encoding/json"
)

// checks if the FileCredentialsPatch type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FileCredentialsPatch{}

// FileCredentialsPatch A change to file credentials.  A field left out is unchanged. An optional field set to null is cleared. `file_path` cannot be cleared.
type FileCredentialsPatch struct {
	// BigQuery project the connection reads from. Only for a BigQuery connection.
	BqProjectId NullableString `json:"bq_project_id,omitempty"`
	// Databricks SQL warehouse the connection runs queries on. Required for a `databricks-sql-warehouse` or `databricks-metastore-sql-warehouse` connection.
	DatabricksWarehouseId NullableString `json:"databricks_warehouse_id,omitempty"`
	// Path of the file on the deployment that holds the connection's credentials.
	FilePath NullableString `json:"file_path,omitempty"`
}

// NewFileCredentialsPatch instantiates a new FileCredentialsPatch object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFileCredentialsPatch() *FileCredentialsPatch {
	this := FileCredentialsPatch{}
	return &this
}

// NewFileCredentialsPatchWithDefaults instantiates a new FileCredentialsPatch object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFileCredentialsPatchWithDefaults() *FileCredentialsPatch {
	this := FileCredentialsPatch{}
	return &this
}

// GetBqProjectId returns the BqProjectId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *FileCredentialsPatch) GetBqProjectId() string {
	if o == nil || IsNil(o.BqProjectId.Get()) {
		var ret string
		return ret
	}
	return *o.BqProjectId.Get()
}

// GetBqProjectIdOk returns a tuple with the BqProjectId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *FileCredentialsPatch) GetBqProjectIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.BqProjectId.Get(), o.BqProjectId.IsSet()
}

// HasBqProjectId returns a boolean if a field has been set.
func (o *FileCredentialsPatch) HasBqProjectId() bool {
	if o != nil && o.BqProjectId.IsSet() {
		return true
	}

	return false
}

// SetBqProjectId gets a reference to the given NullableString and assigns it to the BqProjectId field.
func (o *FileCredentialsPatch) SetBqProjectId(v string) {
	o.BqProjectId.Set(&v)
}

// SetBqProjectIdNil sets the value for BqProjectId to be an explicit nil
func (o *FileCredentialsPatch) SetBqProjectIdNil() {
	o.BqProjectId.Set(nil)
}

// UnsetBqProjectId ensures that no value is present for BqProjectId, not even an explicit nil
func (o *FileCredentialsPatch) UnsetBqProjectId() {
	o.BqProjectId.Unset()
}

// GetDatabricksWarehouseId returns the DatabricksWarehouseId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *FileCredentialsPatch) GetDatabricksWarehouseId() string {
	if o == nil || IsNil(o.DatabricksWarehouseId.Get()) {
		var ret string
		return ret
	}
	return *o.DatabricksWarehouseId.Get()
}

// GetDatabricksWarehouseIdOk returns a tuple with the DatabricksWarehouseId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *FileCredentialsPatch) GetDatabricksWarehouseIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DatabricksWarehouseId.Get(), o.DatabricksWarehouseId.IsSet()
}

// HasDatabricksWarehouseId returns a boolean if a field has been set.
func (o *FileCredentialsPatch) HasDatabricksWarehouseId() bool {
	if o != nil && o.DatabricksWarehouseId.IsSet() {
		return true
	}

	return false
}

// SetDatabricksWarehouseId gets a reference to the given NullableString and assigns it to the DatabricksWarehouseId field.
func (o *FileCredentialsPatch) SetDatabricksWarehouseId(v string) {
	o.DatabricksWarehouseId.Set(&v)
}

// SetDatabricksWarehouseIdNil sets the value for DatabricksWarehouseId to be an explicit nil
func (o *FileCredentialsPatch) SetDatabricksWarehouseIdNil() {
	o.DatabricksWarehouseId.Set(nil)
}

// UnsetDatabricksWarehouseId ensures that no value is present for DatabricksWarehouseId, not even an explicit nil
func (o *FileCredentialsPatch) UnsetDatabricksWarehouseId() {
	o.DatabricksWarehouseId.Unset()
}

// GetFilePath returns the FilePath field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *FileCredentialsPatch) GetFilePath() string {
	if o == nil || IsNil(o.FilePath.Get()) {
		var ret string
		return ret
	}
	return *o.FilePath.Get()
}

// GetFilePathOk returns a tuple with the FilePath field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *FileCredentialsPatch) GetFilePathOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.FilePath.Get(), o.FilePath.IsSet()
}

// HasFilePath returns a boolean if a field has been set.
func (o *FileCredentialsPatch) HasFilePath() bool {
	if o != nil && o.FilePath.IsSet() {
		return true
	}

	return false
}

// SetFilePath gets a reference to the given NullableString and assigns it to the FilePath field.
func (o *FileCredentialsPatch) SetFilePath(v string) {
	o.FilePath.Set(&v)
}

// SetFilePathNil sets the value for FilePath to be an explicit nil
func (o *FileCredentialsPatch) SetFilePathNil() {
	o.FilePath.Set(nil)
}

// UnsetFilePath ensures that no value is present for FilePath, not even an explicit nil
func (o *FileCredentialsPatch) UnsetFilePath() {
	o.FilePath.Unset()
}

func (o FileCredentialsPatch) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FileCredentialsPatch) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.BqProjectId.IsSet() {
		toSerialize["bq_project_id"] = o.BqProjectId.Get()
	}
	if o.DatabricksWarehouseId.IsSet() {
		toSerialize["databricks_warehouse_id"] = o.DatabricksWarehouseId.Get()
	}
	if o.FilePath.IsSet() {
		toSerialize["file_path"] = o.FilePath.Get()
	}
	return toSerialize, nil
}

type NullableFileCredentialsPatch struct {
	value *FileCredentialsPatch
	isSet bool
}

func (v NullableFileCredentialsPatch) Get() *FileCredentialsPatch {
	return v.value
}

func (v *NullableFileCredentialsPatch) Set(val *FileCredentialsPatch) {
	v.value = val
	v.isSet = true
}

func (v NullableFileCredentialsPatch) IsSet() bool {
	return v.isSet
}

func (v *NullableFileCredentialsPatch) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFileCredentialsPatch(val *FileCredentialsPatch) *NullableFileCredentialsPatch {
	return &NullableFileCredentialsPatch{value: val, isSet: true}
}

func (v NullableFileCredentialsPatch) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFileCredentialsPatch) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
