/*
Monte Carlo AI API

Programmatic access to the Monte Carlo AI platform.  Every response with a status of 400 or higher is `application/problem+json`, and carries a `code` naming the failure. That includes failures no single operation declares, such as calling a path with a method it does not support, which returns 405.  Every response carries an `X-Request-Id` header, and an error body repeats it as `request_id`. Quote it when reporting a problem. To choose the value yourself, send an `x-correlation-id` header; a value we cannot accept is replaced by a generated one.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package montecarlo

import (
	"encoding/json"
	"fmt"
)

// checks if the PagedCredentialsSummaryOut type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PagedCredentialsSummaryOut{}

// PagedCredentialsSummaryOut struct for PagedCredentialsSummaryOut
type PagedCredentialsSummaryOut struct {
	// The items on this page, in the list's sort order.
	Items []CredentialsSummaryOut `json:"items"`
	// Pass this as `cursor` to fetch the next page. Null when this is the last page.
	NextCursor NullableString `json:"next_cursor"`
	// Whether there are more items after this page.
	HasMore bool `json:"has_more"`
	// Total number of items across every page. Only returned when the request set `with_count=true`; null otherwise.
	Count                NullableInt32 `json:"count"`
	AdditionalProperties map[string]interface{}
}

type _PagedCredentialsSummaryOut PagedCredentialsSummaryOut

// NewPagedCredentialsSummaryOut instantiates a new PagedCredentialsSummaryOut object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPagedCredentialsSummaryOut(items []CredentialsSummaryOut, nextCursor NullableString, hasMore bool, count NullableInt32) *PagedCredentialsSummaryOut {
	this := PagedCredentialsSummaryOut{}
	this.Items = items
	this.NextCursor = nextCursor
	this.HasMore = hasMore
	this.Count = count
	return &this
}

// NewPagedCredentialsSummaryOutWithDefaults instantiates a new PagedCredentialsSummaryOut object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPagedCredentialsSummaryOutWithDefaults() *PagedCredentialsSummaryOut {
	this := PagedCredentialsSummaryOut{}
	return &this
}

// GetItems returns the Items field value
func (o *PagedCredentialsSummaryOut) GetItems() []CredentialsSummaryOut {
	if o == nil {
		var ret []CredentialsSummaryOut
		return ret
	}

	return o.Items
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
func (o *PagedCredentialsSummaryOut) GetItemsOk() ([]CredentialsSummaryOut, bool) {
	if o == nil {
		return nil, false
	}
	return o.Items, true
}

// SetItems sets field value
func (o *PagedCredentialsSummaryOut) SetItems(v []CredentialsSummaryOut) {
	o.Items = v
}

// GetNextCursor returns the NextCursor field value
// If the value is explicit nil, the zero value for string will be returned
func (o *PagedCredentialsSummaryOut) GetNextCursor() string {
	if o == nil || o.NextCursor.Get() == nil {
		var ret string
		return ret
	}

	return *o.NextCursor.Get()
}

// GetNextCursorOk returns a tuple with the NextCursor field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PagedCredentialsSummaryOut) GetNextCursorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.NextCursor.Get(), o.NextCursor.IsSet()
}

// SetNextCursor sets field value
func (o *PagedCredentialsSummaryOut) SetNextCursor(v string) {
	o.NextCursor.Set(&v)
}

// GetHasMore returns the HasMore field value
func (o *PagedCredentialsSummaryOut) GetHasMore() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.HasMore
}

// GetHasMoreOk returns a tuple with the HasMore field value
// and a boolean to check if the value has been set.
func (o *PagedCredentialsSummaryOut) GetHasMoreOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HasMore, true
}

// SetHasMore sets field value
func (o *PagedCredentialsSummaryOut) SetHasMore(v bool) {
	o.HasMore = v
}

// GetCount returns the Count field value
// If the value is explicit nil, the zero value for int32 will be returned
func (o *PagedCredentialsSummaryOut) GetCount() int32 {
	if o == nil || o.Count.Get() == nil {
		var ret int32
		return ret
	}

	return *o.Count.Get()
}

// GetCountOk returns a tuple with the Count field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PagedCredentialsSummaryOut) GetCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Count.Get(), o.Count.IsSet()
}

// SetCount sets field value
func (o *PagedCredentialsSummaryOut) SetCount(v int32) {
	o.Count.Set(&v)
}

func (o PagedCredentialsSummaryOut) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PagedCredentialsSummaryOut) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["items"] = o.Items
	toSerialize["next_cursor"] = o.NextCursor.Get()
	toSerialize["has_more"] = o.HasMore
	toSerialize["count"] = o.Count.Get()

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PagedCredentialsSummaryOut) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"items",
		"next_cursor",
		"has_more",
		"count",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPagedCredentialsSummaryOut := _PagedCredentialsSummaryOut{}

	err = json.Unmarshal(data, &varPagedCredentialsSummaryOut)

	if err != nil {
		return err
	}

	*o = PagedCredentialsSummaryOut(varPagedCredentialsSummaryOut)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "items")
		delete(additionalProperties, "next_cursor")
		delete(additionalProperties, "has_more")
		delete(additionalProperties, "count")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePagedCredentialsSummaryOut struct {
	value *PagedCredentialsSummaryOut
	isSet bool
}

func (v NullablePagedCredentialsSummaryOut) Get() *PagedCredentialsSummaryOut {
	return v.value
}

func (v *NullablePagedCredentialsSummaryOut) Set(val *PagedCredentialsSummaryOut) {
	v.value = val
	v.isSet = true
}

func (v NullablePagedCredentialsSummaryOut) IsSet() bool {
	return v.isSet
}

func (v *NullablePagedCredentialsSummaryOut) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePagedCredentialsSummaryOut(val *PagedCredentialsSummaryOut) *NullablePagedCredentialsSummaryOut {
	return &NullablePagedCredentialsSummaryOut{value: val, isSet: true}
}

func (v NullablePagedCredentialsSummaryOut) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePagedCredentialsSummaryOut) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
