/*
Monte Carlo AI API

Programmatic access to the Monte Carlo AI platform.  Every response with a status of 400 or higher is `application/problem+json`, and carries a `code` naming the failure. That includes failures no single operation declares, such as calling a path with a method it does not support, which returns 405.  Every response carries an `X-Request-Id` header, and an error body repeats it as `request_id`. Quote it when reporting a problem. To choose the value yourself, send an `x-correlation-id` header; a value we cannot accept is replaced by a generated one.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package montecarlo

import (
	"encoding/json"
	"fmt"
	"time"
)

// checks if the LookerGitCloneCredentialsOut type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LookerGitCloneCredentialsOut{}

// LookerGitCloneCredentialsOut LookML repository credentials Monte Carlo stores. The token and the SSH key are never returned.
type LookerGitCloneCredentialsOut struct {
	// Unique identifier of the credentials.
	Id string `json:"id"`
	// The connection type the credentials are for, such as `snowflake`. Fixed once created.
	ConnectionType string `json:"connection_type"`
	// Where the secret lives. Fixed once created.
	StorageType CredentialsStorageType `json:"storage_type"`
	// When the credentials were created.
	CreatedTime time.Time `json:"created_time"`
	// Clone URL of the LookML repository, over HTTPS or SSH.
	RepoUrl string `json:"repo_url"`
	// Git user. Null for an SSH clone.
	Username NullableString `json:"username"`
	// PEM certificate of the CA that signed the git server's certificate. Null unless set.
	SslCaData NullableString `json:"ssl_ca_data"`
	// Skip verifying the git server's TLS certificate. Null unless set.
	SslSkipCertVerification NullableBool `json:"ssl_skip_cert_verification"`
	AdditionalProperties    map[string]interface{}
}

type _LookerGitCloneCredentialsOut LookerGitCloneCredentialsOut

// NewLookerGitCloneCredentialsOut instantiates a new LookerGitCloneCredentialsOut object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLookerGitCloneCredentialsOut(id string, connectionType string, storageType CredentialsStorageType, createdTime time.Time, repoUrl string, username NullableString, sslCaData NullableString, sslSkipCertVerification NullableBool) *LookerGitCloneCredentialsOut {
	this := LookerGitCloneCredentialsOut{}
	this.Id = id
	this.ConnectionType = connectionType
	this.StorageType = storageType
	this.CreatedTime = createdTime
	this.RepoUrl = repoUrl
	this.Username = username
	this.SslCaData = sslCaData
	this.SslSkipCertVerification = sslSkipCertVerification
	return &this
}

// NewLookerGitCloneCredentialsOutWithDefaults instantiates a new LookerGitCloneCredentialsOut object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLookerGitCloneCredentialsOutWithDefaults() *LookerGitCloneCredentialsOut {
	this := LookerGitCloneCredentialsOut{}
	return &this
}

// GetId returns the Id field value
func (o *LookerGitCloneCredentialsOut) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *LookerGitCloneCredentialsOut) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *LookerGitCloneCredentialsOut) SetId(v string) {
	o.Id = v
}

// GetConnectionType returns the ConnectionType field value
func (o *LookerGitCloneCredentialsOut) GetConnectionType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ConnectionType
}

// GetConnectionTypeOk returns a tuple with the ConnectionType field value
// and a boolean to check if the value has been set.
func (o *LookerGitCloneCredentialsOut) GetConnectionTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ConnectionType, true
}

// SetConnectionType sets field value
func (o *LookerGitCloneCredentialsOut) SetConnectionType(v string) {
	o.ConnectionType = v
}

// GetStorageType returns the StorageType field value
func (o *LookerGitCloneCredentialsOut) GetStorageType() CredentialsStorageType {
	if o == nil {
		var ret CredentialsStorageType
		return ret
	}

	return o.StorageType
}

// GetStorageTypeOk returns a tuple with the StorageType field value
// and a boolean to check if the value has been set.
func (o *LookerGitCloneCredentialsOut) GetStorageTypeOk() (*CredentialsStorageType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StorageType, true
}

// SetStorageType sets field value
func (o *LookerGitCloneCredentialsOut) SetStorageType(v CredentialsStorageType) {
	o.StorageType = v
}

// GetCreatedTime returns the CreatedTime field value
func (o *LookerGitCloneCredentialsOut) GetCreatedTime() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedTime
}

// GetCreatedTimeOk returns a tuple with the CreatedTime field value
// and a boolean to check if the value has been set.
func (o *LookerGitCloneCredentialsOut) GetCreatedTimeOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedTime, true
}

// SetCreatedTime sets field value
func (o *LookerGitCloneCredentialsOut) SetCreatedTime(v time.Time) {
	o.CreatedTime = v
}

// GetRepoUrl returns the RepoUrl field value
func (o *LookerGitCloneCredentialsOut) GetRepoUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RepoUrl
}

// GetRepoUrlOk returns a tuple with the RepoUrl field value
// and a boolean to check if the value has been set.
func (o *LookerGitCloneCredentialsOut) GetRepoUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RepoUrl, true
}

// SetRepoUrl sets field value
func (o *LookerGitCloneCredentialsOut) SetRepoUrl(v string) {
	o.RepoUrl = v
}

// GetUsername returns the Username field value
// If the value is explicit nil, the zero value for string will be returned
func (o *LookerGitCloneCredentialsOut) GetUsername() string {
	if o == nil || o.Username.Get() == nil {
		var ret string
		return ret
	}

	return *o.Username.Get()
}

// GetUsernameOk returns a tuple with the Username field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *LookerGitCloneCredentialsOut) GetUsernameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Username.Get(), o.Username.IsSet()
}

// SetUsername sets field value
func (o *LookerGitCloneCredentialsOut) SetUsername(v string) {
	o.Username.Set(&v)
}

// GetSslCaData returns the SslCaData field value
// If the value is explicit nil, the zero value for string will be returned
func (o *LookerGitCloneCredentialsOut) GetSslCaData() string {
	if o == nil || o.SslCaData.Get() == nil {
		var ret string
		return ret
	}

	return *o.SslCaData.Get()
}

// GetSslCaDataOk returns a tuple with the SslCaData field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *LookerGitCloneCredentialsOut) GetSslCaDataOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SslCaData.Get(), o.SslCaData.IsSet()
}

// SetSslCaData sets field value
func (o *LookerGitCloneCredentialsOut) SetSslCaData(v string) {
	o.SslCaData.Set(&v)
}

// GetSslSkipCertVerification returns the SslSkipCertVerification field value
// If the value is explicit nil, the zero value for bool will be returned
func (o *LookerGitCloneCredentialsOut) GetSslSkipCertVerification() bool {
	if o == nil || o.SslSkipCertVerification.Get() == nil {
		var ret bool
		return ret
	}

	return *o.SslSkipCertVerification.Get()
}

// GetSslSkipCertVerificationOk returns a tuple with the SslSkipCertVerification field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *LookerGitCloneCredentialsOut) GetSslSkipCertVerificationOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.SslSkipCertVerification.Get(), o.SslSkipCertVerification.IsSet()
}

// SetSslSkipCertVerification sets field value
func (o *LookerGitCloneCredentialsOut) SetSslSkipCertVerification(v bool) {
	o.SslSkipCertVerification.Set(&v)
}

func (o LookerGitCloneCredentialsOut) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LookerGitCloneCredentialsOut) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["connection_type"] = o.ConnectionType
	toSerialize["storage_type"] = o.StorageType
	toSerialize["created_time"] = o.CreatedTime
	toSerialize["repo_url"] = o.RepoUrl
	toSerialize["username"] = o.Username.Get()
	toSerialize["ssl_ca_data"] = o.SslCaData.Get()
	toSerialize["ssl_skip_cert_verification"] = o.SslSkipCertVerification.Get()

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *LookerGitCloneCredentialsOut) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"connection_type",
		"storage_type",
		"created_time",
		"repo_url",
		"username",
		"ssl_ca_data",
		"ssl_skip_cert_verification",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varLookerGitCloneCredentialsOut := _LookerGitCloneCredentialsOut{}

	err = json.Unmarshal(data, &varLookerGitCloneCredentialsOut)

	if err != nil {
		return err
	}

	*o = LookerGitCloneCredentialsOut(varLookerGitCloneCredentialsOut)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "connection_type")
		delete(additionalProperties, "storage_type")
		delete(additionalProperties, "created_time")
		delete(additionalProperties, "repo_url")
		delete(additionalProperties, "username")
		delete(additionalProperties, "ssl_ca_data")
		delete(additionalProperties, "ssl_skip_cert_verification")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableLookerGitCloneCredentialsOut struct {
	value *LookerGitCloneCredentialsOut
	isSet bool
}

func (v NullableLookerGitCloneCredentialsOut) Get() *LookerGitCloneCredentialsOut {
	return v.value
}

func (v *NullableLookerGitCloneCredentialsOut) Set(val *LookerGitCloneCredentialsOut) {
	v.value = val
	v.isSet = true
}

func (v NullableLookerGitCloneCredentialsOut) IsSet() bool {
	return v.isSet
}

func (v *NullableLookerGitCloneCredentialsOut) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLookerGitCloneCredentialsOut(val *LookerGitCloneCredentialsOut) *NullableLookerGitCloneCredentialsOut {
	return &NullableLookerGitCloneCredentialsOut{value: val, isSet: true}
}

func (v NullableLookerGitCloneCredentialsOut) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLookerGitCloneCredentialsOut) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
