/*
Monte Carlo AI API

Programmatic access to the Monte Carlo AI platform.  Every response with a status of 400 or higher is `application/problem+json`, and carries a `code` naming the failure. That includes failures no single operation declares, such as calling a path with a method it does not support, which returns 405.  Every response carries an `X-Request-Id` header, and an error body repeats it as `request_id`. Quote it when reporting a problem. To choose the value yourself, send an `x-correlation-id` header; a value we cannot accept is replaced by a generated one.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package montecarlo

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"
)

// checks if the BiContainerOut type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BiContainerOut{}

// BiContainerOut A BI container: one BI tool Monte Carlo observes, and the home of its connections.  Create the container first, then add connections to it. Deleting a container never deletes a connection; remove those first.
type BiContainerOut struct {
	// Unique identifier of the BI container.
	Id string `json:"id"`
	// The BI tool the container represents. Fixed once created.
	Type BiContainerType `json:"type"`
	// Display name of the BI container. Null for a container that was never named.
	Name NullableString `json:"name"`
	// The deployment the container's connections run through. Null for a custom BI connector's container, which has none. The id may name a deployment on Monte Carlo's older collection platform. The deployments endpoints do not list those.
	DeploymentId NullableString `json:"deployment_id"`
	// Display name of the deployment. Null exactly when `deployment_id` is.
	DeploymentName NullableString `json:"deployment_name"`
	// When the BI container was created.
	CreatedTime time.Time `json:"created_time"`
}

type _BiContainerOut BiContainerOut

// NewBiContainerOut instantiates a new BiContainerOut object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBiContainerOut(id string, type_ BiContainerType, name NullableString, deploymentId NullableString, deploymentName NullableString, createdTime time.Time) *BiContainerOut {
	this := BiContainerOut{}
	this.Id = id
	this.Type = type_
	this.Name = name
	this.DeploymentId = deploymentId
	this.DeploymentName = deploymentName
	this.CreatedTime = createdTime
	return &this
}

// NewBiContainerOutWithDefaults instantiates a new BiContainerOut object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBiContainerOutWithDefaults() *BiContainerOut {
	this := BiContainerOut{}
	return &this
}

// GetId returns the Id field value
func (o *BiContainerOut) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *BiContainerOut) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *BiContainerOut) SetId(v string) {
	o.Id = v
}

// GetType returns the Type field value
func (o *BiContainerOut) GetType() BiContainerType {
	if o == nil {
		var ret BiContainerType
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *BiContainerOut) GetTypeOk() (*BiContainerType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *BiContainerOut) SetType(v BiContainerType) {
	o.Type = v
}

// GetName returns the Name field value
// If the value is explicit nil, the zero value for string will be returned
func (o *BiContainerOut) GetName() string {
	if o == nil || o.Name.Get() == nil {
		var ret string
		return ret
	}

	return *o.Name.Get()
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BiContainerOut) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Name.Get(), o.Name.IsSet()
}

// SetName sets field value
func (o *BiContainerOut) SetName(v string) {
	o.Name.Set(&v)
}

// GetDeploymentId returns the DeploymentId field value
// If the value is explicit nil, the zero value for string will be returned
func (o *BiContainerOut) GetDeploymentId() string {
	if o == nil || o.DeploymentId.Get() == nil {
		var ret string
		return ret
	}

	return *o.DeploymentId.Get()
}

// GetDeploymentIdOk returns a tuple with the DeploymentId field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BiContainerOut) GetDeploymentIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DeploymentId.Get(), o.DeploymentId.IsSet()
}

// SetDeploymentId sets field value
func (o *BiContainerOut) SetDeploymentId(v string) {
	o.DeploymentId.Set(&v)
}

// GetDeploymentName returns the DeploymentName field value
// If the value is explicit nil, the zero value for string will be returned
func (o *BiContainerOut) GetDeploymentName() string {
	if o == nil || o.DeploymentName.Get() == nil {
		var ret string
		return ret
	}

	return *o.DeploymentName.Get()
}

// GetDeploymentNameOk returns a tuple with the DeploymentName field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BiContainerOut) GetDeploymentNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DeploymentName.Get(), o.DeploymentName.IsSet()
}

// SetDeploymentName sets field value
func (o *BiContainerOut) SetDeploymentName(v string) {
	o.DeploymentName.Set(&v)
}

// GetCreatedTime returns the CreatedTime field value
func (o *BiContainerOut) GetCreatedTime() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedTime
}

// GetCreatedTimeOk returns a tuple with the CreatedTime field value
// and a boolean to check if the value has been set.
func (o *BiContainerOut) GetCreatedTimeOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedTime, true
}

// SetCreatedTime sets field value
func (o *BiContainerOut) SetCreatedTime(v time.Time) {
	o.CreatedTime = v
}

func (o BiContainerOut) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BiContainerOut) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["type"] = o.Type
	toSerialize["name"] = o.Name.Get()
	toSerialize["deployment_id"] = o.DeploymentId.Get()
	toSerialize["deployment_name"] = o.DeploymentName.Get()
	toSerialize["created_time"] = o.CreatedTime
	return toSerialize, nil
}

func (o *BiContainerOut) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"type",
		"name",
		"deployment_id",
		"deployment_name",
		"created_time",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBiContainerOut := _BiContainerOut{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBiContainerOut)

	if err != nil {
		return err
	}

	*o = BiContainerOut(varBiContainerOut)

	return err
}

type NullableBiContainerOut struct {
	value *BiContainerOut
	isSet bool
}

func (v NullableBiContainerOut) Get() *BiContainerOut {
	return v.value
}

func (v *NullableBiContainerOut) Set(val *BiContainerOut) {
	v.value = val
	v.isSet = true
}

func (v NullableBiContainerOut) IsSet() bool {
	return v.isSet
}

func (v *NullableBiContainerOut) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBiContainerOut(val *BiContainerOut) *NullableBiContainerOut {
	return &NullableBiContainerOut{value: val, isSet: true}
}

func (v NullableBiContainerOut) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBiContainerOut) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
