/*
Monte Carlo AI API

Programmatic access to the Monte Carlo AI platform.  Every response with a status of 400 or higher is `application/problem+json`, and carries a `code` naming the failure. That includes failures no single operation declares, such as calling a path with a method it does not support, which returns 405.  Every response carries an `X-Request-Id` header, and an error body repeats it as `request_id`. Quote it when reporting a problem. To choose the value yourself, send an `x-correlation-id` header; a value we cannot accept is replaced by a generated one.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package montecarlo

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"
)

// checks if the GcpDataformCredentialsOut type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GcpDataformCredentialsOut{}

// GcpDataformCredentialsOut GCP Dataform credentials Monte Carlo stores. The key is never returned.
type GcpDataformCredentialsOut struct {
	// Unique identifier of the credentials.
	Id string `json:"id"`
	// The connection type the credentials are for, such as `snowflake`. Fixed once created.
	ConnectionType string `json:"connection_type"`
	// Where the secret lives. Fixed once created.
	StorageType CredentialsStorageType `json:"storage_type"`
	// When the credentials were created.
	CreatedTime time.Time `json:"created_time"`
	// Google Cloud project that holds the Dataform repositories.
	ProjectId string `json:"project_id"`
	// Google Cloud regions to read Dataform repositories in, such as us-central1.
	Locations []string `json:"locations"`
	// Email address of the service account.
	ClientEmail string `json:"client_email"`
}

type _GcpDataformCredentialsOut GcpDataformCredentialsOut

// NewGcpDataformCredentialsOut instantiates a new GcpDataformCredentialsOut object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGcpDataformCredentialsOut(id string, connectionType string, storageType CredentialsStorageType, createdTime time.Time, projectId string, locations []string, clientEmail string) *GcpDataformCredentialsOut {
	this := GcpDataformCredentialsOut{}
	this.Id = id
	this.ConnectionType = connectionType
	this.StorageType = storageType
	this.CreatedTime = createdTime
	this.ProjectId = projectId
	this.Locations = locations
	this.ClientEmail = clientEmail
	return &this
}

// NewGcpDataformCredentialsOutWithDefaults instantiates a new GcpDataformCredentialsOut object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGcpDataformCredentialsOutWithDefaults() *GcpDataformCredentialsOut {
	this := GcpDataformCredentialsOut{}
	return &this
}

// GetId returns the Id field value
func (o *GcpDataformCredentialsOut) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *GcpDataformCredentialsOut) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *GcpDataformCredentialsOut) SetId(v string) {
	o.Id = v
}

// GetConnectionType returns the ConnectionType field value
func (o *GcpDataformCredentialsOut) GetConnectionType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ConnectionType
}

// GetConnectionTypeOk returns a tuple with the ConnectionType field value
// and a boolean to check if the value has been set.
func (o *GcpDataformCredentialsOut) GetConnectionTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ConnectionType, true
}

// SetConnectionType sets field value
func (o *GcpDataformCredentialsOut) SetConnectionType(v string) {
	o.ConnectionType = v
}

// GetStorageType returns the StorageType field value
func (o *GcpDataformCredentialsOut) GetStorageType() CredentialsStorageType {
	if o == nil {
		var ret CredentialsStorageType
		return ret
	}

	return o.StorageType
}

// GetStorageTypeOk returns a tuple with the StorageType field value
// and a boolean to check if the value has been set.
func (o *GcpDataformCredentialsOut) GetStorageTypeOk() (*CredentialsStorageType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StorageType, true
}

// SetStorageType sets field value
func (o *GcpDataformCredentialsOut) SetStorageType(v CredentialsStorageType) {
	o.StorageType = v
}

// GetCreatedTime returns the CreatedTime field value
func (o *GcpDataformCredentialsOut) GetCreatedTime() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedTime
}

// GetCreatedTimeOk returns a tuple with the CreatedTime field value
// and a boolean to check if the value has been set.
func (o *GcpDataformCredentialsOut) GetCreatedTimeOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedTime, true
}

// SetCreatedTime sets field value
func (o *GcpDataformCredentialsOut) SetCreatedTime(v time.Time) {
	o.CreatedTime = v
}

// GetProjectId returns the ProjectId field value
func (o *GcpDataformCredentialsOut) GetProjectId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProjectId
}

// GetProjectIdOk returns a tuple with the ProjectId field value
// and a boolean to check if the value has been set.
func (o *GcpDataformCredentialsOut) GetProjectIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProjectId, true
}

// SetProjectId sets field value
func (o *GcpDataformCredentialsOut) SetProjectId(v string) {
	o.ProjectId = v
}

// GetLocations returns the Locations field value
func (o *GcpDataformCredentialsOut) GetLocations() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Locations
}

// GetLocationsOk returns a tuple with the Locations field value
// and a boolean to check if the value has been set.
func (o *GcpDataformCredentialsOut) GetLocationsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Locations, true
}

// SetLocations sets field value
func (o *GcpDataformCredentialsOut) SetLocations(v []string) {
	o.Locations = v
}

// GetClientEmail returns the ClientEmail field value
func (o *GcpDataformCredentialsOut) GetClientEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ClientEmail
}

// GetClientEmailOk returns a tuple with the ClientEmail field value
// and a boolean to check if the value has been set.
func (o *GcpDataformCredentialsOut) GetClientEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ClientEmail, true
}

// SetClientEmail sets field value
func (o *GcpDataformCredentialsOut) SetClientEmail(v string) {
	o.ClientEmail = v
}

func (o GcpDataformCredentialsOut) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GcpDataformCredentialsOut) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["connection_type"] = o.ConnectionType
	toSerialize["storage_type"] = o.StorageType
	toSerialize["created_time"] = o.CreatedTime
	toSerialize["project_id"] = o.ProjectId
	toSerialize["locations"] = o.Locations
	toSerialize["client_email"] = o.ClientEmail
	return toSerialize, nil
}

func (o *GcpDataformCredentialsOut) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"connection_type",
		"storage_type",
		"created_time",
		"project_id",
		"locations",
		"client_email",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGcpDataformCredentialsOut := _GcpDataformCredentialsOut{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGcpDataformCredentialsOut)

	if err != nil {
		return err
	}

	*o = GcpDataformCredentialsOut(varGcpDataformCredentialsOut)

	return err
}

type NullableGcpDataformCredentialsOut struct {
	value *GcpDataformCredentialsOut
	isSet bool
}

func (v NullableGcpDataformCredentialsOut) Get() *GcpDataformCredentialsOut {
	return v.value
}

func (v *NullableGcpDataformCredentialsOut) Set(val *GcpDataformCredentialsOut) {
	v.value = val
	v.isSet = true
}

func (v NullableGcpDataformCredentialsOut) IsSet() bool {
	return v.isSet
}

func (v *NullableGcpDataformCredentialsOut) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGcpDataformCredentialsOut(val *GcpDataformCredentialsOut) *NullableGcpDataformCredentialsOut {
	return &NullableGcpDataformCredentialsOut{value: val, isSet: true}
}

func (v NullableGcpDataformCredentialsOut) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGcpDataformCredentialsOut) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
